### PR TITLE
Remove Advance linux-tests-pass and all-tests-pass branches

### PR DESCRIPTION
**Pull request by piotr-iohk**
- [x] remove Advance linux-tests-pass and all-tests-pass branches (a0794bef26c2a1f95492e4d154797867dd9607f4)

### Comments

It's failing and I don't think it has any practical use really.

### CODE REVIEW

**Review by Anviking — APPROVED** [review]
If `./.buildkite/push-branch.sh` was for updating this branch https://github.com/input-output-hk/cardano-wallet/tree/linux-tests-pass it seems it stopped working long time ago. 

We could consider removing the other caller of the script https://github.com/input-output-hk/cardano-wallet/blob/872a25d12dbab16536771bdc8df944fdef416bf5/.github/workflows/windows.yml#L81-L97 and the `.buildkite/push-branch.sh` script itself. I don't _think_ that's doing anything useful either.

But regardless: lgtm 👍

**Comment by piotr-iohk** [comment]
>We could consider removing the other caller of the script

Yes. The whole `windows.yml` needs to be refined, as it tries to get binaries from hydra.

**Comment by HeinrichApfelmus** [comment]
Yeah, the buildkite step mentions branches `windows-tests-pass` and `all-tests-pass`, but they don't even exist anymore.

**Pull request merged**
