### PR TITLE
Update haskell.nix and HLS

### PR DESCRIPTION
**Pull request by Anviking**
- [x] Bump haskell.nix
- [x] Update Haskell Language Server to 1.5.0.0 in `build-tools.nix`
- [x] Bump index-state in `cabal.project`.

### Comments

- Build got stuck locally; trying in CI
- Seems to build fine, but HLS doesn't seem updated (when I tried changing manually, it was reverted by the automatic nix regeneration)

- [Hydra jobset](https://hydra.iohk.io/jobset/Cardano/cardano-wallet-pr-3030#tabs-evaluations)

### Issue Number

None

### CODE REVIEW

**Comment by Anviking** [comment]
Closing for now

**Comment by rvl** [comment]
This is what I got when trying to run nix-shell locally:

```
trace: ERROR: cabal configure failed with:
Warning: The package list for 'hackage.haskell.org-at-2021-10-05T000000Z' is
18954 days old.
Run 'cabal update' to get the latest list of available packages.
Warning: Requested index-state 2021-10-05T00:00:00Z is newer than
'hackage.haskell.org-at-2021-10-05T000000Z'! Falling back to older state
(2021-10-04T22:59:49Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: haskell-language-server-1.5.0.0 (user goal)
[__1] trying: haskell-language-server:+eval
[__2] next goal: hls-eval-plugin (dependency of haskell-language-server +eval)
[__2] rejecting: hls-eval-plugin-1.1.2.0, hls-eval-plugin-1.1.1.0,
hls-eval-plugin-1.1.0.0, hls-eval-plugin-1.0.0.0, hls-eval-plugin-0.2.0.0,
hls-eval-plugin-0.1.0.5, hls-eval-plugin-0.1.0.4, hls-eval-plugin-0.1.0.3,
hls-eval-plugin-0.1.0.2, hls-eval-plugin-0.1.0.1, hls-eval-plugin-0.1.0.0
(conflict: haskell-language-server +eval => hls-eval-plugin^>=1.2.0.0)
[__2] fail (backjumping, conflict set: haskell-language-server,
hls-eval-plugin, haskell-language-server:eval)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: haskell-language-server,
haskell-language-server:eval, hls-eval-plugin
```

On Hydra, the same error appears as:
```
{UNKNOWN}: Died at /nix/store/7r3z8n7a7v62rq1linayx1q4z2kvnf2i-hydra-0.1.20211118.79b8a89/bin/.hydra-eval-jobset-wrapped line 784. at /nix/store/aa6gw57fnahd4824pbhmvcs0jlypmynq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Catalyst/Model/DBIC/Schema.pm line 526
```

**Comment by rvl** [comment]
Let's try again with latest Hackage and index-state.

**Review by rvl — APPROVED** [review]
It's not all finished building yet, but with the index-state change, hls 1.5 seems to work at least, when building locally.

```
haskell-language-server version: 1.5.0.0 (GHC: 8.10.7) (PATH: /nix/store/pgzd2bzrlpa4fd473x974say97gwkzz3-haskell-language-server-exe-haskell-language-server-1.5.0.0/bin/haskell-language-server)
````

**Pull request merged**
