### PR TITLE
Rename UnstableBlocks -> BlockHeaders

### PR DESCRIPTION
**Pull request by rvl**
Relates to #648.

# Overview

This sequence will also be used for the chain consumer local headers state. So UnstableBlocks will no longer be the right name.

It also changes the _k_ type from Natural to Word32, to match BlockchainParameters.

### CODE REVIEW

**Comment by KtorZ** [comment]
@rvl I have no issue with the renaming here, but what exactly do you mean with: "will also be used for the chain consumer local headers state" ?

**Comment by rvl** [comment]
I'm using this block headers sequence as the cursor (local state) in #755.

**Review by KtorZ — APPROVED** [review]

**Pull request merged**
