### PR TITLE
Retry init cursor and improve loggging when intersection isn't found

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

None _yet_

# Overview

- 1e50d2aef597937884ab9a7e6e4ff579f92c6749
  retry fetching intersection and increase timeout delay
  
- 3a7a6ffd110a2afc2932eaa219505ce2e638e608
  Add explicit warning log line when retrying init cursor

# Comments

Investigating -->

```
[31m[cardano-wallet.wallet-engine:Error:253][0m [2020-03-19 15:53:20.14 UTC] Worker has exited unexpectedly: user error (initCursor: intersection not found? This can't happen because we always give at least the genesis point...)
```

### CODE REVIEW

**Comment by Anviking** [comment]
bors try (why isn't hydra starting?)

**Comment by KtorZ** [comment]
bors try

**Comment by KtorZ** [comment]
Damn. We actually give a `nullTracer` to the network layer :man_facepalming:  ..fixing

**Review by Anviking — APPROVED** [review]
lgtm

**Pull request closed without merging**
