### PR TITLE
Upgrade `cardano-node` to 8.1.1 and `ghc`  to `9.2.8`

### PR DESCRIPTION
**Pull request by Unisay**
This PR builds on top of 2 other PRs:

- https://github.com/cardano-foundation/cardano-wallet/pull/3959
- https://github.com/cardano-foundation/cardano-wallet/pull/3995

### Comments

The https://github.com/cardano-foundation/cardano-wallet/pull/3959 is superseded by this one.

### Issue Number

[ADP-2956](https://input-output.atlassian.net/browse/ADP-2956)

### CODE REVIEW

**Comment by sourabhxyz** [comment]
Thanks for bringing this PR! Eagerly waiting for it to make into `master`.

**Review by paolino — APPROVED** [review]
LGTM, I suggest to squash into 2 commits
1) bump ghc
2) bump node

**Comment by paolino** [comment]
the buildkite link to the job that passed all: https://buildkite.com/input-output-hk/cardano-wallet/builds/25990

**Comment by paolino** [comment]
the buildkite benchmarks link https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/1851 . Will be done on Monday :fingercrossed:

**Comment by Unisay** [comment]
Please don't merge or add more commits to this PR, it exists as a history of all the changes needed. We intend to merge the squashed version of this history https://github.com/cardano-foundation/cardano-wallet/pull/4003 once the performance is tested.

**Comment by jonathanknowles** [comment]
> Please don't merge or add more commits to this PR, it exists as a history of all the changes needed. We intend to merge the squashed version of this history https://github.com/cardano-foundation/cardano-wallet/pull/4003 once the performance is tested.

Hi @Unisay @paolino 

I've added a comment on the squashed PR here:
https://github.com/cardano-foundation/cardano-wallet/pull/4003#discussion_r1243176920

**Pull request closed without merging**
