### PR TITLE
Enable faucet random wallets

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

#779 

# Overview

- [x] I have added faucet random wallets for Jörmungandr
- [x] Faucet wallets can be restored via `fixtureByronWallet`, although, we can't make transactions with them.

# Comments

:warning: Somehow, I can't generate the genesis block from the genesis
configuration, jcli isn't happy with the `legacy_fund`, am I missing
something?

### CODE REVIEW

**Review by piotr-iohk — APPROVED** [review]
lgtm!

I couldn't generete genesis block myself too - the same error with `jcli 0.6.1`.
Sadly, without genesis block, it is unusable...

**Comment by piotr-iohk** [comment]
https://github.com/input-output-hk/jormungandr/issues/968 - created a bug in Jormungandr.

**Review by rvl — APPROVED** [review]

**Review by paweljakubas — APPROVED** [review]

**Comment by piotr-iohk** [comment]
Still the same on `jcli 0.7.0-alpha.dev.1`:
```
$ jcli genesis encode --input genesis.yaml --output block0.bin 
genesis file corrupted
  |-> initial[992].legacy_fund[0]: encoding error at line 3068 column 14
```

**Comment by piotr-iohk** [comment]
The fix didn't make it to `0.7.0-alpha.dev.1`. :/

Screenshot from 2019-10-23 16-43-21

**Comment by KtorZ** [comment]
Great.

**Pull request merged**
