### PR TITLE
Remove 30s timeout in for chain-sync requests

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

#1657 

# Overview

- [x] I removed the possibility for chain sync commands to timeout.

# Comments

Without this the wallet would get stuck on the friends and family testnet

```
[cardano-wallet.wallet-engine:Info:37] [2020-05-15 15:39:52.49 UTC] 755ef893: syncProgress: restored
[cardano-wallet.wallet-engine:Info:37] [2020-05-15 15:39:52.49 UTC] 755ef893: discovered 0 new transaction(s)
[cardano-wallet.wallet-engine:Info:37] [2020-05-15 15:39:52.49 UTC] 755ef893: local tip: cf853d5d<-[baba20fd-11.5092#6393]
[cardano-wallet.wallet-engine:Warning:37] [2020-05-15 15:40:22.49 UTC] 755ef893: Failed to get next blocks: ErrGetBlockNetworkUnreachable (ErrNetworkUnreachable "timeout")
[cardano-wallet.wallet-engine:Warning:37] [2020-05-15 15:40:53.47 UTC] 755ef893: Failed to get next blocks: ErrGetBlockNetworkUnreachable (ErrNetworkUnreachable "timeout")
[cardano-wallet.wallet-engine:Warning:37] [2020-05-15 15:41:25.47 UTC] 755ef893: Failed to get next blocks: ErrGetBlockNetworkUnreachable (ErrNetworkUnreachable "timeout")
[cardano-wallet.wallet-engine:Warning:37] [2020-05-15 15:41:59.48 UTC] 755ef893: Failed to get next blocks: ErrGetBlockNetworkUnreachable (ErrNetworkUnreachable "timeout")
[cardano-wallet.wallet-engine:Warning:37] [2020-05-15 15:42:34.49 UTC] 755ef893: Failed to get next blocks: ErrGetBlockNetworkUnreachable (ErrNetworkUnreachable "timeout")
[cardano-wallet.wallet-engine:Warning:37] [2020-05-15 15:43:09.50 UTC] 755ef893: Failed to get next blocks: ErrGetBlockNetworkUnreachable (ErrNetworkUnreachable "timeout")
[cardano-wallet.wallet-engine:Warning:37] [2020-05-15 15:43:44.51 UTC] 755ef893: Failed to get next blocks: ErrGetBlockNetworkUnreachable (ErrNetworkUnreachable "timeout")
```

but on that note, shouldn't it have recovered? 🤔

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]

**Comment by KtorZ** [comment]
@Anviking don't forget the PR label please :+1:

**Comment by Anviking** [comment]
This is not solving a known, released bug, so is this "improving code"?

**Comment by KtorZ** [comment]
I would still label it as resolving issue. But you're right... there no ticket tracking this at the moment :/

**Pull request merged**
