### PR TITLE
[ADP-2367] Orthogonal changes concerning `finalitySlot`

### PR DESCRIPTION
**Pull request by HeinrichApfelmus**
### Overview

This pull request extracts a couple of changes from #3673 that are of independent interest and can be merged as is. These changes are:

* Computation of the `finalitySlot` as `3*k/f` with appropriate types.
* Remove of the field `firstSubmission` from the `LocalTxSubmissionStatus` type.

### Issue Number

ADP-2367

### CODE REVIEW

**Comment by paolino** [comment]
fixed a warning

**Review by paolino — APPROVED** [review]
LGTM (how could it not ? :-) )

**Comment by HeinrichApfelmus** [comment]
Looks like there is a genuine bug in here. Will fix.

**Comment by HeinrichApfelmus** [comment]
bors merge

**Pull request merged**
