### PR TITLE
more HWWallets CLI tests

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

#1416

# Overview

- 9ade256d6f4ba720924c5729af7c8f0b894eef03
  create Test.Integration.Scenario.CLI.HWWallets
  
- f9caf1ad324da954d1998baee1fe5bae6c8fd28f
  reuse pubKeyFromMnemonics
  
- 8146e1d02c6f65b568493c220da8a51af5b897ec
  remove HWWallet test from Wallets.hs
  
- a6248519ab32092177ce6612a806c2c9457efe0e
  more HWWallets CLI tests

# Comments

### CODE REVIEW

**Comment by piotr-iohk** [comment]
bors try

**Review by paweljakubas — APPROVED** [review]
looks fine modulo resolving merging conflicts

**Comment by piotr-iohk** [comment]
rebased, bors r+

**Comment by KtorZ** [comment]
(you can't put anything else in your comment if you want to bors r+)

**Comment by piotr-iohk** [comment]
> (you can't put anything else in your comment if you want to bors r+)

I thought it used to work :man_shrugging:

**Pull request merged**
