### PR TITLE
scripts/bors-stats.rb: fix --force-refresh

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

ADP-970

# Overview

- [x] Fix ` ./scripts/bors-stats.rb list --fetch-system`

# Comments

### CODE REVIEW

**Comment by Anviking** [comment]
Actually, I don't think `--force-refetch` should affect `--fetch-system`.

`--force-refetch` for GitHub data is often useful to fetch recent changes. Re-fetching the os is not useful unless your cache is somehow corrupted.

**Review by rvl — APPROVED** [review]
Fair enough :+1:

**Pull request merged**
