### PR TITLE
Update Buildable instances for BlockHeader and Hash

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

#711 

# Overview

- [x] I added an idea for new `BlockHeader` buildable instance where the prevBlockHash comes first, and the blockHeader points towards it.
- [x] I made `Hash tag` `build` to `424c4f43` instead of `424c4f43...c0dd1877`. 
- [x] I implemented `To/FromText` and `Buildable` instances on `Hash tag` in general, instead of having one instance per tag.

# Comments

```haskell
fmtLn $ build h
-- Old: Block (5.36#1036) -> 424c4f43...434b3033
-- New: 424c4f43 ⬸ [5.36#1036]

fmtLn $ build (prevBlockHash h)
-- Old: 424c4f43...434b3033
-- New: 424c4f43
```

### CODE REVIEW

**Comment by Anviking** [comment]
For the `Block` buildable instance having the `prevBlockHash` last might make sense though 🤔 
```
            "Block (14.19#42) -> dffc3506...6969a73b\n\
            \    - ~> 1st c29d3ea0...13862214\n\
            \      <~ 3823755953610 @ 82d81858...aebb3709\n\
            \      <~ 19999800000 @ 82d81858...37ce9c60\n"
```

Also, the unicode arrow isn't good when printed in error messages in its escaped form.

**Review by KtorZ — APPROVED** [review]
Sounds reasonable to me :+1:

**Comment by Anviking** [comment]
🤔 

```
Failures:

  test/integration/Test/Integration/Jormungandr/Scenario/CLI/Launcher.hs:155:13: 
  1) No backend required, Launcher CLI tests, LAUNCH - cardano-wallet launch [SERIAL], LAUNCH - Invalid block0 file (not a serialized block)
       "\ESC[34m[iohk.cardano-wallet.launch:Info:ThreadId 4]\ESC[0m [2019-09-30 08:39:34.79 UTC] Using state directory: /var/lib/buildkite-agent/.local/share/cardano-wallet/jormungandr/testnet\n\ESC[34m[iohk.cardano-wallet.launch:Info:ThreadId 4]\ESC[0m [2019-09-30 08:39:34.79 UTC] Running as v2019.9.13\n\ESC[34m[iohk.cardano-wallet.launch:Info:ThreadId 4]\ESC[0m [2019-09-30 08:39:34.79 UTC] Wallet backend server starting...\n\ESC[34m[iohk.cardano-wallet.launch:Info:ThreadId 4]\ESC[0m [2019-09-30 08:39:34.79 UTC] Node is J\246rmungandr on testnet\n\ESC[34m[iohk.cardano-wallet.launch:Info:ThreadId 4]\ESC[0m [2019-09-30 08:39:34.79 UTC] Database layer started.\n\ESC[34m[iohk.cardano-wallet.launch:Info:ThreadId 4]\ESC[0m [2019-09-30 08:39:34.79 UTC] Generated J\246rmungandr's configuration to: /var/lib/buildkite-agent/.local/share/cardano-wallet/jormungandr/testnet/jormungandr-config.yaml\n" does not contain "As far as I can tell, this isn't a valid block file: test/data/jormungandr/secret.yaml"

  To rerun use: --match "/No backend required/Launcher CLI tests/LAUNCH - cardano-wallet launch [SERIAL]/LAUNCH - Invalid block0 file (not a serialized block)/"
```

```
Failures:

  src/Test/Integration/Scenario/CLI/Mnemonics.hs:30:5: 
  1) Mnemonics CLI tests CLI_MNEMONICS_01 - Can generate mnemonics with default size
       uncaught exception: IOException of type InvalidArgument
       fd:18: hGetContents: invalid argument (invalid byte sequence)

  To rerun use: --match "/Mnemonics CLI tests/CLI_MNEMONICS_01 - Can generate mnemonics with default size/"

  src/Test/Integration/Framework/DSL.hs:1286:22: 
  2) Server CLI tests, LOGGING - cardano-wallet serve logging, LOGGING - Launch can log --verbose
       "" does not contain "Running as v2019.9.13"

  To rerun use: --match "/Server CLI tests/LOGGING - cardano-wallet serve logging/LOGGING - Launch can log --verbose/"

Randomized with seed 475995922

```

**Comment by Anviking** [comment]
`stack test cardano-wallet-jormungandr:integration --ta '--match "/No backend required/Launcher CLI tests/LAUNCH - cardano-wallet launch [SERIAL]/LAUNCH - Invalid block0 file (not a serialized block)/"'`

fails with same error message on master, for me locally.

**Comment by KtorZ** [comment]
Runs fine for me. I am on `jormungandr 0.5.0` at the moment. Which one are you?

**Comment by Anviking** [comment]
`jormungandr 0.5.0` too

**Review by paweljakubas — APPROVED** [review]

**Comment by Anviking** [comment]
Back to the flaky jormungandr-tests… We had the same failure in #771, so this PR shouldn't be the problem… trying again

bors r+

**Pull request merged**
