### PR TITLE
Clean up Buildkite pipelines

### PR DESCRIPTION
**Pull request by HeinrichApfelmus**
This pull request cleans up our Buildkite pipelines, such that there is one .yml file per granularity. The granularities are:

* `post-commit`
* `pre-merge`
* `nightly`

See "Continuous Integration :: AP".

### CODE REVIEW

**Review by paolino — APPROVED** [review]
LGTM, less is more

**Comment by HeinrichApfelmus** [comment]
bors merge

**Review by piotr-iohk — APPROVED** [review]
lgtm. I've updated badges and buidkite.rb to point to new pipeline.

**Comment by paolino** [comment]
bors try

**Pull request merged**
