### PR TITLE
[ADP-2389] Lean package and ci action

### PR DESCRIPTION
**Pull request by piotr-iohk**
- [x] move files to lean package (e7575ecb0d0995bed3318f23a56c4b749aff8a7c) 
- [x] Add simple CI worflow (ca5821a601ec3f05f224725acd1a364763144b7c) 
- [x] update global gitignore with Lean specific items (996a7c34aae6c4113b7079471a5782efcd90535a) 
- [x] dummy lean package and worflow adjustment (f1d36d88a46d5849792957c4ad4c8435ec931054) 
- [x] adjust worflow (eeae0d71b3885f219384d700ab8aa47b469dea5a) 

### Comments

A proposal for putting lean specs into a package so we can control the lean version and also adding simple CI workflow checking the syntax of lean files.

### Issue Number

ADP-2389

### CODE REVIEW

**Comment by HeinrichApfelmus** [comment]
Thanks! I'm ambivalent — on one hand, I think that specifying the `lean` version in the source code is valuable, on the other hand, I think of the `.lean` files as ["scratch files"](https://leanprover.github.io/reference/using_lean.html#scratch-files) that each stand on their own without being part of a package, i.e. the files are not supposed to work together as a single package. 🤔 In a way, I would like the `specifications` directory to be grouped by subject matter rather than technology used (LaTeX, swagger, Lean, …).

A "scratch file"-based approach would use `./specifications/` as top-level directory. The Github workflow would be mostly the same, but filter on `.lean` files directly,

```
on:
  push:
    branches: [ "master" ]
    paths: ['specifications/**.lean']
  pull_request:
    branches: [ "master" ]
    paths: ['specifications/**.lean']
```

In order to download the right `lean` version, we could use an empty package with `leanpkg configure`. 🤔 In the end, `lean --recursive` works with scratch files, it doesn't need a package.

Thoughts?

**Comment by piotr-iohk** [comment]
>In order to download the right lean version, we could use an empty package with leanpkg configure. thinking In the end, lean --recursive works with scratch files, it doesn't need a package.

@HeinrichApfelmus  sounds good. I've adjusted to that.

**Review by HeinrichApfelmus — APPROVED** [review]
>  I've adjusted to that.

Awesome, thanks! 😊

**Review by paolino — APPROVED** [review]
Great idea. Thanks

**Pull request merged**
