### PR TITLE
Bump to cardano node 1.35.1

### PR DESCRIPTION
**Pull request by sevanspowell**
- [x] I have bumped the version of `cardano-node` used by `cardano-wallet` to `1.35.1`.

### Comments

- No changes to our codebase were required.

### Issue Number

ADP-2007

### CODE REVIEW

**Comment by sevanspowell** [comment]
bors try

**Comment by sevanspowell** [comment]
bors try

**Comment by sevanspowell** [comment]
bors try

**Review by jonathanknowles — APPROVED** [review]

**Review by paweljakubas — APPROVED** [review]

**Review by Anviking — APPROVED** [review]

**Review by piotr-iohk — APPROVED** [review]

**Pull request merged**
