### PR TITLE
Use big pool gap for Icarus wallet first scan

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

#1208 

# Overview

- commit 4f07b8d7b75550667ee7b1f37f739ac32a1a1636

    add special integration test for Icarus wallets with high indexes
    Currently fails as expected with:

    ```
    1) API Specifications BYRON_RESTORE_08 - Icarus wallet with high indexes
         expected: 1000000000000
          but got: 0
    ```

- commit 5783c86dcfac063689cc5ed289419da6659288ca 
    scan genesis block with bigger pool gap for Icarus wallets
    This to compensate the lack of transaction history in the ITN.

- [ ] TODO: Maybe add some unit test for the `shrinkPool` function :grimacing: 

# Comments

This is what an existing non-empty wallet looks like with this (not mentioning the fact that addresses are discovered correctly!):

```
(master) $ ls -lh ~/.local/share/cardano-wallet/jormungandr/testnet/wallets
total 13M
-rw-r--r-- 1 ktorz ktorz 1,2M déc.  23 11:47 ica.f2a072b15fa9a2eabae5472344cdcc85fa82931d.sqlite
```

Without this little pool shrinks, the wallet size was ~960MB :man_shrugging:

### CODE REVIEW

**Review by piotr-iohk — APPROVED** [review]
OK, but have couple of questions/suggestions for tests. (However maybe that's not the scope of this particular task).

Test with other "byron" endpoints:
 - GET
 - LIST (in particular that 12-word and 15-word mnemonic wallets are listed "side-by-side" ordered from oldest to newest.)
 - DELETE
 - list/forget transactions - (btw. not sure if I get the part "the lack of transaction history in the ITN")
 - Migrate/Calculate fee (but I suppose it is out of scope for this task for now)

**Comment by KtorZ** [comment]
@piotr-iohk I've actually extended the byron integration scenarios last week to test every time with Byron and Icarus wallets (e.g. https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/ByronWallets.hs#L149). I've done it for relevant endpoints (MIGRATE, CALCULATE, RESTORE ... ) but haven't done LIST :thinking: 

I haven't tried to _mix_ them though (apart from manual testing) I don't see any reason it wouldn't work. Still, the list endpoint may have a surprising behavior. Icarus wallets would be sorted, Byron wallets would be sorted, but they'll be in two groups (So, like `[ica1, ica2, ica3, byr1, byr2, byr3]`). Can be fixed rather easily though.

> not sure if I get the part "the lack of transaction history in the ITN

For the incentivized testnet, we start from an initial snapshot of the mainnet. The snapshot contains the UTxO at the moment it is taken. Now, if we do sequential discovery and, have a pool gap of let's say `20`, the algorithm says that we must first generate the first `20` addresses, as we discover addresses, we have to generate further. 

Now, what if, the first address in the snapshot starts at index 21 :man_shrugging: ... That's quite possible for a user that has made a few transactions and has used all of its first `20` addresses. Therefore, this PR does 2 things:

- Illustrate the case where a wallet would have addresses that are beyond the initial default gap and that wouldn't be discovered by a "standard discovery"
- Cheat a bit when scanning the genesis block to use a gap as big as 10.000, with the assumption that it would be sufficient for most users...

**Comment by KtorZ** [comment]
bors try

**Pull request merged**
