### PR TITLE
Bump package versions to 2020.3.3

### PR DESCRIPTION
**Pull request by Anviking**
# Overview

```bash
find . -name "*.nix" ! -path "*.stack-work*" | xargs sed -i "s/$OLD_VERSION/$NEW_VERSION/"
# or macOS version:
find . -name "*.nix" ! -path "*.stack-work*" | xargs sed -i "" "s/$OLD_VERSION/$NEW_VERSION/"
```

# Comments

### CODE REVIEW

**Comment by piotr-iohk** [comment]
Looks like there should be few more :thinking: (comparing to -> https://github.com/input-output-hk/cardano-wallet/pull/1352/files)

**Comment by Anviking** [comment]
@piotr-iohk yeah, I notice the command does not change nix files. I wonder if the nix-regenerate CI check will give a patch changing all remaining instances of `2020.2.17`… otherwise I guess the command should be tweaked

**Review by piotr-iohk — APPROVED** [review]
:+1:

**Pull request merged**
