### PR TITLE
Tweak bors-stats.sh to support jira links

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

None

# Overview

- [x] Improve pattern excluding bors try (now removes two recent "try\nTimed out")
- [x] Support `ADP-` as tags for the breakdown

# Comments

### Before
Skärmavbild 2021-01-12 kl  11 47 06

### Now

Skärmavbild 2021-01-12 kl  11 46 06

### CODE REVIEW

**Comment by Anviking** [comment]
I reclassified the ADP-647 failures to #2320 for consistency, still. Maybe we should't allow ADP- then.

**Review by rvl — APPROVED** [review]
Yeah nice - I already did the same change locally yesterday. :-)

**Comment by rvl** [comment]
If the test failure is due to a bug, then we need to be able to link to jira.

It's possible to get jira ticket titles with go-jira.

**Comment by rvl** [comment]
I made some improvements to the script and ran shellcheck over it.

**Comment by Anviking** [comment]
That breaks it for me (macOS) with:
```
ktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
```

**Comment by Anviking** [comment]
You have just a warning, right? I reverted the commit.
bors r+

**Comment by rvl** [comment]
Oops - I was assuming gnu coreutils. Turns on the macOS `mktemp` is [completely different](https://stackoverflow.com/a/31397073)! You need to install a better OS. :smile_cat:

**Pull request merged**
