### PR TITLE
[ADP-1827] enforce value parity for GET /network/parameters in light mode

### PR DESCRIPTION
**Pull request by paolino**
- [ ] ~~fix encoding for rational numbers~~ as the rational encoding is possible in 2 modes
- [x] fix security_param retrieval using the genesis endpoint  in blockfrost
- [ ] ~~resolve minimum_utx_value difference~~ , this depends on story ADP-1944

### Issue Number

ADP-1827

### CODE REVIEW

**Comment by paolino** [comment]
bors  try

**Review by piotr-iohk — APPROVED** [review]
Seems to be reported correctly now -> 2160.

:+1:

**Pull request merged**
