### PR TITLE
Integration Setup Foundation for cardano-node w/ Byron

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

#1347 

# Overview

- 91b6d63e6845b0ac193b93aaa576d4d846aab9d3
  move and rename 'sockAddrPort' to 'unsafePortNumber'
  a. Allow sharing the code outside of the jormungandr package
b. A bit more true about the underlying intent of the function
c. The function had so-to-speak nothing to do with Cardano.Faucet

- 72aad48ffccbf195431c78f767c0f791e7c66c0c
  remove 'nodePort' and 'feePolicy' from 'Context'
  this type is common to various integration setup. However, these constituants are
only used in Jormungandr-specific scenario and do not apply to cardano-node

- beb6032685c132c51a66b5f286ffdb74138877cc
  Remove hard-coded byron parameters from compat functions
  Passing them as arguments instead. Also, currently abusing the
'Testnet' discriminant with integration data. Later, I'll make sure
that serveWallet takes blockchain parameters as arguments instead of
a 'KnownNetwork =>' constraints to allow constructing private blockchain
from arbitrary genesis blocks.

- 9650acec6e362e37123e816bb50e5c8bd22477b5
  remove 'staticBlockchainParameters' from NetworkLayer
  a. Blockchain parameters aren't actually static and comes from genesis + protocol updates.
b. Allow more flexibility for cardano-node in the way the genesis block is passed
c. Remove awkward conversion in the byron compat code for cardano node

- b9bb6d86e91ea4a594729d793df99e04aea4b14d
  Implement 'fromGenesisTxOut' to construct transaction from genesis UTxO
  These transaction are a bit special and by convention, the transaction id is a hash of the genesis address.

- fb193b4146ef54ea7c3a8c7b252442d3aff44905
  Fix wrong checkpoint reference in unstable assertion
    While doing ... something totally different, I noticed that some integration tests, when restoring a wallet were showing something like 1000x "Creating checkpoint at xxxxxxxx-[X.X#X]."

  This caught my attention for a second because:

  a. With the setting I had, it should only create around 10 checkpoints, not a thousand.
  b. This happened not only near the tip, but at any time.

  Inspecting the code responsible for inserting checkpoints, I found this in `Cardano.Wallet#restoreBlocks`

  ```hs
          forM_ (NE.init cps) $ \cp' -> do
              let (Quantity h) = currentTip cp ^. #blockHeight
              when (fromIntegral h `elem` unstable) $ do
                  liftIO $ logCheckpoint cp'
                  putCheckpoint (PrimaryKey wid) cp'
  ```

  Note the `currentTip cp` instead of `currentTip cp'` ! So, the assertion of whether or not a checkpoint should be inserted was based on the current checkpoint from the database, and not on the actual checkpoint. So basically, every time the database checkpoint is considered a stable block, we get to insert ~1000 checkpoints in the database man_facepalming ... That can take some time...

  I am not sure whether this is the cause of the Windows slowness mentioned in #1398 (and why this doesn't really impact Linux then?) but it is definitely wrong.

# Comments

This is only a foundation for setting up the integration tests (still not committed here). I've got the integration setup working and running, though I still need to go through a few fixes to avoid hard-coded some of the genesis parameters and instead, read them from the genesis file.

### CODE REVIEW

**Comment by KtorZ** [comment]
bors try

**Review by paweljakubas — APPROVED** [review]
Amazed that setting `mainnetGenesis` and `blockchainParameters` plus small changes to Jormungandr.Network and extending argument list in several places was enough to make it work :trophy: 

Q: I see that commit of ouroborous-network is month old in stack.yaml. We are ok with that in the context of this PR ? (I bet bumping it is going to be work for another PR and it will affect considerably byron codebase, but maybe also integration testing layer?). 

Also weeder complaining.

**Comment by KtorZ** [comment]
>  I see that commit of ouroborous-network is month old in stack.yaml. We are ok with that in the context of this PR ?

Yes. Locally, I am running a 1.6 cardano-node and the client code is using the libraries from 1.5. It works fine. I'll bump the dependencies at the end.

**Comment by KtorZ** [comment]
3x in a row the same error. But I can't reproduce locally. This is weird.

**Pull request merged**
