### PR TITLE
Update wallet name and utxo statistics for byron

### PR DESCRIPTION
**Pull request by paweljakubas**
# Issue Number

#1483 

# Overview

- [x] I have added putByronWallet
- [x] I have updated swagger for putting wallet metadata
- [x] I have added integration test running within cardano-node
- [x] I have added getUtxoStatistics
- [x] I have updated swagger for getting UTxO statistics
- [x] I have added integration test running within cardano-node

# Comments

### CODE REVIEW

**Comment by paweljakubas** [comment]
bors try

**Review by KtorZ — APPROVED** [review]
:ok_hand:

**Pull request merged**
