### PR TITLE
cardano-node: 1.15.1 -> 1.16.x (master branch)

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

Relates to #1920.

### Overview

This updates cardano-node and cardano-cli from 1.15.1 to ~1.16.0~ [e28c1d3](https://github.com/input-output-hk/cardano-node/commit/e28c1d37832af9c4ec50bb5c64aa83c37dc4aa89), but not the cardano libraries, which will be taken care of in input-output-hk/cardano-wallet#1909.

### CODE REVIEW

**Review by Anviking — APPROVED** [review]

**Comment by Anviking** [comment]
Now seeing
```
[cardano-wallet.integration:Info:790] [2020-07-18 11:53:09.63 UTC] Submitting transaction for pre-registered stake key
[cardano-wallet.integration:Warning:790] [2020-07-18 11:53:09.65 UTC] Failed Submitting transaction for pre-registered stake key with exit code 1:
  Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = "cea1b041dd5465be636b5b88805571f83537bd503bc4db447f088d942673736c"}) 0])))),LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Coin 0) (Coin 10000000000000))))]

[cardano-wallet.integration:Info:790] [2020-07-18 11:53:10.65 UTC] Submitting transaction for pre-registered stake key
[cardano-wallet.integration:Warning:790] [2020-07-18 11:53:10.67 UTC] Failed Submitting transaction for pre-registered stake key with exit code 1:
  Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = "cea1b041dd5465be636b5b88805571f83537bd503bc4db447f088d942673736c"}) 0])))),LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Coin 0) (Coin 10000000000000))))]
```
_maybe just need to regenerate the inputs_ 🤔

**Review by paweljakubas — APPROVED** [review]
should be ok

**Comment by Anviking** [comment]
```
[cardano-wallet.wallet-engine:Error:2409] [2020-07-18 12:22:28.35 UTC] 48ea749c: Unexpected error following the chain: ExceptionInLinkedThread ThreadId 2836 (DeserialiseFailure 974 "Size mismatch when decoding Block.\nExpected 4, but found 2.")
[cardano-wallet.network:Notice:2409] [2020-07-18 12:22:28.35 UTC] Destroying cursor connection at ThreadId 2836
[cardano-wallet.network:Info:2848] [2020-07-18 12:22:28.35 UTC] conn::/private/var/folders/h_/mlzym27d5lz_fx3ph2d547700000gn/T/test-a05fefc6cac08729/node/node.socket Send MsgProposeVersions (fromList [(NodeToClientV_2,TInt 764824073)])
[cardano-wallet.network:Info:2409] [2020-07-18 12:22:28.35 UTC] Looking for an intersection with the node's local chain with: 00000000<-[01010101-0#0]
[cardano-wallet.network:Info:2848] [2020-07-18 12:22:28.35 UTC] conn::/private/var/folders/h_/mlzym27d5lz_fx3ph2d547700000gn/T/test-a05fefc6cac08729/node/node.socket Recv MsgAcceptVersion NodeToClientV_2 (TInt 764824073)
[cardano-wallet.network:Info:2409] [2020-07-18 12:22:28.35 UTC] Intersection found: 01010101
[cardano-wallet.wallet-engine:Error:2409] [2020-07-18 12:22:28.35 UTC] 48ea749c: Unexpected error following the chain: ExceptionInLinkedThread ThreadId 2848 (DeserialiseFailure 974 "Size mismatch when decoding Block.\nExpected 4, but found 2.")
```

> "Size mismatch when decoding Block.\nExpected 4, but found 2.")

@rvl we may need to update the wallet first

(But I should be a able to work on #1920 with this)

**Comment by rvl** [comment]
OK nice.

**Comment by Anviking** [comment]
I think this is included in other PRs and can be closed. It is at least included in #1924 .

**Pull request closed without merging**
