### PR TITLE
Add property and fix for markCharsRedAtIndices

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

#1603 

# Overview

- [x] Add property for and fix questionable behaviour of `markCharsRedAtIndices`

# Comments

- Step by step property failures in  72d5bb9
- Don't think the problems affected the error rendering (or at least not commonly), or I'd noticed yesterday.
- Should still have a another calm look at this to be safe 😬

### CODE REVIEW

**Comment by Anviking** [comment]
bors try

**Review by rvl — APPROVED** [review]
The little functions are usually the tricky ones. :-)

For the property, can I suggest that it be "all the red characters correspond to errors"? So scan through the error string and get all the characters that would appear red in a terminal. Assert that this is equal to the characters of the error indices (sorted).

**Comment by KtorZ** [comment]
merging manually until we figure out how to fix Hydra.

**Pull request merged**
