### PR TITLE
Bump cardano-node to 1.26.2

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

ADP-845

# Overview

Updates from 1.25.1 to [1.26.2](https://github.com/input-output-hk/cardano-node/releases/tag/1.26.2).

- [x] Get things compiling.
- [x] Remove TRANS_EXTERNAL tests to drop cardano-transaction dependency
- [x] Fix any warnings etc in CI 
- [x] Move to Stackage LTS 17.9
- [x] Update nix voodoo
- [x] Fix new failing tests.
- [x] Sync `stack.yaml` to `cabal.project`

# Comments

- Depends on input-output-hk/cardano-haskell#44
- Depends on input-output-hk/cardano-haskell#45

### CODE REVIEW

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
bors try-

**Comment by Anviking** [comment]
bors try

**Review by rvl — APPROVED** [review]
Good stuff.
I rebased, updated the rev in `stack.yaml` to point to cardano-haskell master branch, and made the `allow-newer` tweaks in `cabal.project` more specific.

**Pull request merged**
