### PR TITLE
discard metadata URL based on their hash, not URLs

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

#1805 

# Overview

- [x] I have changed the SQLite filtering to discard metadata URL based on their hash, not URLs

### CODE REVIEW

**Review by disassembler — APPROVED** [review]

**Comment by disassembler** [comment]
tested and this shows stake pools with multiple registrations right away!

**Comment by KtorZ** [comment]
bors retry

**Comment by rvl** [comment]
I opened issue #1811 about the test which just failed in bors - retrying now.

bors r+

**Comment by rvl** [comment]
Doh, forgot that the test result is cached - restarted the test build in Hydra.

bors r+

**Pull request merged**
