### PR TITLE
Bump to cardano-node alonzo-purple-1.0.1

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

ADP-1066

# Overview

- [x] I have bumped to cardano-node alonzo-purple-1.0.1

# Comments

https://github.com/input-output-hk/cardano-haskell/pull/55

### CODE REVIEW

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
I re-added the `--cache /dev/null` to prevent fix the nix regenerate issue.

The other failures simply look like known flaky ones.

bors try

**Review by rvl — APPROVED** [review]
LGTM

**Pull request merged**
