### PR TITLE
Bump cardano-node to pioneer-wave2-38-g1c797366

### PR DESCRIPTION
**Pull request by rvl**
Latest master rev [1c79736](https://github.com/input-output-hk/cardano-node/commit/1c7973665348f6e747d3d5447efc64b4df1cc5f0) fixes an issue where the cardano-node sources can't be checked out on a case-insensitive filesystem (macOS) ⇒ input-output-hk/cardano-node#1131.

### CODE REVIEW

**Review by disassembler — APPROVED** [review]

**Comment by rvl** [comment]
Byron integration tests passed but shelley integration tests failed to finish... Will update the base libraries too.

**Comment by rvl** [comment]
bors r-

Meant to type `bors try`. The integration tests seem to pass now. The stack snapshot yaml ought to be moved to cardano-haskell.

**Comment by Anviking** [comment]
bors try

**Review by Anviking — APPROVED** [review]

**Comment by KtorZ** [comment]
@Anviking Do you think we can merge this and trigger the release, or trigger it first?

**Comment by Anviking** [comment]
> No need for the cardano-haskell snapshot though, since this is still an intermediate release.
>  Let's stick with local snapshots until things stabilize.

— @KtorZ 

bors r+

**Pull request merged**
