### PR TITLE
Bump cardano-base so that shelley-spec-ledger-test compiles

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

Found during #2077.

### Overview

If you are keen enough to build the test suites of all our dependencies, you would have found `shelley-spec-ledger-test` failing to compile, because it needs a later revision of `cardano-base`. This will fix it.

### CODE REVIEW

**Comment by hasufell** [comment]
Maybe not related directly to this, but it would also be good to bump cardano-sl-x509: https://github.com/input-output-hk/cardano-sl-x509/commit/12925934c533b3a6e009b61ede555f8f26bac037

**Review by hasufell — APPROVED** [review]

**Comment by KtorZ** [comment]
@rvl I am afraid Buildkite is running into the same issues as I did because of the cache it's using. We should try purging the cache or; renaming the snapshot to something else otherwise it is going to annoy everyone using stack once this PR is merged.

**Comment by rvl** [comment]
@KtorZ This time I renamed the snapshot file - so I think stack will be able to invalidate its cache. Buildkite master branch still works (the stack build phase at least).

**Pull request merged**
