### PR TITLE
Jörmungandr 0.7.0 rc7 -> 0.7.0

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- [ ]  0.7.0 rc7 -> 0.7.0 

# Comments

### CODE REVIEW

**Comment by KtorZ** [comment]
bors try

**Review by KtorZ — APPROVED** [review]
@Anviking approved #1013 from which commits have been cherry-picked.

**Review by Anviking — APPROVED** [review]

**Comment by KtorZ** [comment]
I can also reproduce locally https://github.com/input-output-hk/cardano-wallet/pull/1012#issuecomment-553012103

:thinking: will look into this.

**edit:** https://github.com/input-output-hk/cardano-wallet/pull/1012/commits/d1300c08aae855ed61b18fdfd4a25ad3508c455d

**Comment by KtorZ** [comment]
bors try

**Review by KtorZ — DISMISSED** [review]
:no_entry_sign: DO NOT MERGE ... _yet_ :no_entry_sign: 

Jörmungandr 0.7.0 won't be deployed for the first phase of the incentivized testnet. Only `0.7.0-rc7` will! So, let's keep this PR hanging a bit in case we need to do some hot fixes for the release to come.

**Comment by KtorZ** [comment]
I've included #1026 in this PR to save some time merging / testing.

**Pull request merged**
