### PR TITLE
Byron migration integration tests

### PR DESCRIPTION
**Pull request by jonathanknowles**
# Issue Number

#778 
#779 

# Overview

This PR adds integration tests to verify that:

- [x] Calculating the migration cost of an empty wallet (with [`getByronWalletMigrateInfo`](https://github.com/input-output-hk/cardano-wallet/issues/778)) returns a value of `0`.
- [x] Migrating an empty wallet (with the [`migrateByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/779) endpoint) should not generate any transactions.
- [x] The actual cost incurred by a migration (with the [`migrateByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/779) endpoint) **exactly** matches the cost returned by the [`getByronWalletMigrateInfo`](https://github.com/input-output-hk/cardano-wallet/issues/778) endpoint.

# Comments

### CODE REVIEW

**Comment by KtorZ** [comment]
>  The actual cost incurred by a migration (with the migrateByronWallet endpoint) exactly matches the cost returned by the getByronWalletMigrateInfo endpoint.

That might actually not be true. We don't enforce any particular order for the UTxO, so we very much rely on how the database yields the result and how `Map.fromList` / `Map.toList` also re-order them. We _could_ add a shuffling of the ordered UTxO with a known seed but that sounds overkill.

**Comment by jonathanknowles** [comment]
@KtorZ wrote:

> That might actually not be true. We don't enforce any particular order for the UTxO, so we very much rely on how the database yields the result and how `Map.fromList` / `Map.toList` also re-order them.

That's a good point I hadn't thought of.

However, AFAIK [`Map.toList`](https://hackage.haskell.org/package/containers-0.4.0.0/docs/src/Data-Map.html#toList) does always yield the same order for maps `a` and `b` if `a == b`:
```hs
toList :: Map k a -> [(k,a)]
toList t = toAscList t
```
This order should be independent of how the map was constructed. In fact, the `Eq` instance for `Map` uses the same function (`toAscList`):
```hs
instance (Eq k,Eq a) => Eq (Map k a) where
  t1 == t2  = (size t1 == size t2) && (toAscList t1 == toAscList t2)
```
We use `Map.toList` (internally `toAscList`) in the definition of `selectCoinsForMigration` like so:
```hs
evalState migrate (Map.toList (getUTxO utxo))
```

So, provided the UTxO data hasn't actually changed between consecutive calls, calling this function twice should result in the same coin selection, and therefore the same fee, unless there is a mistake in my reasoning?

**Comment by KtorZ** [comment]
You're reasoning is correct although incomplete on one part: we can't guarantee that the database yields results in the same order unless we enforce a strict ordering on the results, which we don't. Sqlite does implicitly create a special column `rowid` that uniquely identifies any row that was ever inserted in the database which could be used to "sort" UTxOs according to their `rowid` but I am not sure `persistent` enables us to play with the `rowid` and write something like:

```sql
SELECT * FROM utxo ORDER BY rowid
```

:/

**Comment by jonathanknowles** [comment]
@KtorZ wrote:

> You're reasoning is correct although incomplete on one part: we can't guarantee that the database yields results in the same order

I'm not sure I follow your reasoning here.

Here's my understanding (please feel free to point out any errors):

1. We construct a value of type `UTxO` (which is `Data.Map TxIn TxOut`) from _arbitrarily-ordered_ rows of data that we read from the database, specifically from table `UTxO`.
1. For any two values `m1` and `m2` of type `Data.Map a b`, if `m1 == m2`, then `toList m1 == toList m2` since `toList = toAscList`. The order of operations used to construct `m1` and `m2` is not relevant here, since `toList` yields values in _ascending_ order.
1. The function `selectCoinsForMigration` uses `Map.toList` to pre-process its `UTxO` input value which yields results in _ascending_ order, before passing the list to `evalState migrate`.
1. Therefore, if `selectCoinsForMigration` is applied separately to two different `UTxO` values `u1` and `u2` where `u1 == u2`, it will yield equal values of `[CoinSelection]`.
1. Therefore, repeated calls to calculate the fee (using `getByronWalletMigrationInfo`) should yield identical results, provided that there are no real changes to the UTxO of that wallet in the interim.
1. Therefore, `migrateByronWallet` should produce a set of transactions with exactly the same total fee as `getByronWalletMigrationInfo`, provided that there are no real changes to the UTxO of that wallet in the interim.

The above is my understanding. If there are any errors in my reasoning, please feel free to point them out! :)

**Comment by jonathanknowles** [comment]
bors try

**Comment by KtorZ** [comment]
@jonathanknowles 

The Map is indeed a balanced binary tree underneath, although I wonder if any permutation of the same list always give you the same tree. This doesn't strike me as obvious, but well, let's not use our brain now and simply Quickcheck it :grimacing: ...

**Comment by jonathanknowles** [comment]
@KtorZ wrote:

> This doesn't strike me as obvious, but well, let's not use our brain now and simply Quickcheck it.

Would be happy to oblige :)

**Comment by jonathanknowles** [comment]
@KtorZ I've added a test to demonstrate that `Map.toList . getUTxO` yields elements in a deterministic order: https://github.com/input-output-hk/cardano-wallet/pull/916/commits/00e0f59d31b20529facde2a27e31ededb40ec363

**Comment by jonathanknowles** [comment]
> Don't use liftIO, but use `run` from QuickCheck.Monadic instead. This gives QC the ability to correctly instrument your test and report failures nicely.

Done.

**Comment by KtorZ** [comment]
@jonathanknowles I wanted to wrap up the PR and actually make use of byron wallets and ran into a few blockers... I've updated one scenario to remove all the TODOs (so it currently fails), and opened another PR about fixing those blockers here #934

**Review by rvl — APPROVED** [review]
Looks nice so far.

If there's any doubt about what order our data is in, then we could explicitly sort it after converting to a list.

**Comment by KtorZ** [comment]
@rvl we tried different strategies for the ordering of the UTxO as part of previous PRs and, having it sorted (asc or desc) on the UTxO's amount had some negative impact on the efficiency of the selection.

We could however sort by keys (a.k.a TxIn) though I believe this is more or less already what the fromList/toList does.. To some extend.

**Comment by jonathanknowles** [comment]
@rvl wrote:
> If there's any doubt about what order our data is in, then we could explicitly sort it after converting to a list.

This is a good suggestion. However, here we don't need to do any extra sorting, as [`Map.toList`](https://hackage.haskell.org/package/containers-0.4.0.0/docs/src/Data-Map.html#toList) always yields a list in _ascending order_. The order is independent of how the map was constructed:
```hs
toList :: Map k a -> [(k,a)]
toList t = toAscList t
```
Notably, `Map` uses `toAscList` in its definition of equality:
```hs
instance (Eq k,Eq a) => Eq (Map k a) where
  t1 == t2  = (size t1 == size t2) && (toAscList t1 == toAscList t2)
```


@KtorZ wrote:
> We could however sort by keys (a.k.a TxIn) though I believe this is more or less already what the fromList/toList does.. To some extend.

That's correct. The result of `Map.toList` (in this case) is a list in ascending order of `TxIn`, which is effectively a list in ascending lexicographic order of `(inputId, inputIx)`.

**Comment by jonathanknowles** [comment]
@KtorZ The test `BYRON_ESTIMATE_03` is still failing with the "waited too long for initial transaction" error:

```
  src/Test/Integration/Scenario/API/ByronWallets.hs:159:5:
  1) API Specifications BYRON_ESTIMATE_03 - actual fee for migration is the same as the predicted fee.
       uncaught exception: IOException of type UserError
       user error (fixtureByronWallet: waited too long for initial transaction)

  To rerun use: --match "/API Specifications/BYRON_ESTIMATE_03 - actual fee for migration is the same as the predicted fee./"

Randomized with seed 1448476919
```
I've reproduced this locally with [`jormungandr` version `0.7.0-rc2`](https://github.com/input-output-hk/jormungandr/releases/tag/v0.7.0-rc2). I increased the timeout to 10 minutes, but the failure still occurs.

**Comment by KtorZ** [comment]
> The test BYRON_ESTIMATE_03 is still failing with the "waited too long for initial transaction" error:

@jonathanknowles I know, cf my earliee comment. We still don't lookup old UTxO declarations from the chain, and, more importantly, Jormungandr won't validate any transaction from legacy UTxO.

**Pull request merged**
