### PR TITLE
Foundations for stake-pools integration tests

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

#715

# Overview

- [ ] I have added simple _foundations_ for future integration tests for stake-pools list

# Comments

### CODE REVIEW

**Review by paweljakubas — APPROVED** [review]
LGTM!

**Comment by piotr-iohk** [comment]
The failure looks mysterious...

```

Failures:
--
  |  
  | src/Test/Integration/Scenario/CLI/Mnemonics.hs:30:5:
  | 1) Mnemonics CLI tests CLI_MNEMONICS_01 - Can generate mnemonics with default size
  | uncaught exception: IOException of type InvalidArgument
  | fd:18: hGetContents: invalid argument (invalid byte sequence)

```

**Pull request merged**
