### PR TITLE
jormungandr: Fix "Blockchain tip not set in REST context"

### LINKED ISSUE #1647: Blockchain tip not set in REST context
# Context
 
Unless I'm missing some configuration changes, it appears that the latest two cardano-wallet versions don't work paired with jormungandr. Either with existing or wiped database (chain folder).
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | v2020.5.6 (git revision: cf3d9c91e895d1a01f90e4ab3d10b81e260b3510) with jormungandr v0.8.18 AND v2020-04-28 with jormungandr v0.8.15 or v0.8.18 |
| Platform     | Linux the least          |
| Installation | From Github Release            |

# Steps to Reproduce

`$ cardano-wallet launch --node-port 3100 --genesis-block-hash $(cat genesis-hash.txt) -- --config ./stakepool-config.yaml`

Above referenced files exist and are valid, as previous versions of cardano-wallet and jormungandr v0.8.15 and v0.8.18 on their own run well with them.

## Expected behavior

Jormungandr bootstraps successfully and cardano-wallet starts communicating with it.

## Actual behavior
 
Fails as follows:

```
[cardano-wallet.main:Info:4] [2020-05-08 23:01:04.58 UTC] Running as v2020.5.6 (git revision: cf3d9c91e895d1a01f90e4ab3d10b81e260b3510)
[cardano-wallet.main:Info:4] [2020-05-08 23:01:04.58 UTC] Command line: /home/thevictor/.local/bin/cardano-wallet launch --node-port 3100 --genesis-block-hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676 -- --config ./stakepool-config.yaml
[cardano-wallet.main:Info:4] [2020-05-08 23:01:04.58 UTC] LaunchArgs {_hostPreference = Host "127.0.0.1", _listen = ListenOnPort 8090, _nodePort = Just 3100, _stateDir = Nothing, _syncTolerance = SyncTolerance 300s, _logging = LoggingOptions {loggingMinSeverity = Debug, loggingTracers = Tracers {applicationTracer = Const (Just Info), apiServerTracer = Const (Just Info), walletEngineTracer = Const (Just Info), walletDbTracer = Const (Just Info), stakePoolEngineTracer = Const (Just Info), stakePoolDbTracer = Const (Just Info), networkTracer = Const (Just Info), ntpClientTracer = Const (Just Info)}, loggingTracersDoc = Nothing}, _jormungandrArgs = JormungandrArgs {genesisBlock = Left (Hash {getHash = "\142M*4?=\207\147\&0\173\144\&5\179\232\209h\230r\137\EOT&/,CJO\143\147N\199\182v"}), extraJormungandrArgs = ["--config","./stakepool-config.yaml"]}}
[cardano-wallet.main:Info:4] [2020-05-08 23:01:04.58 UTC] Wallet state: Using directory: /home/thevictor/.local/share/cardano-wallet/jormungandr/testnet
[cardano-wallet.main:Info:4] [2020-05-08 23:01:04.58 UTC] Wallet databases: Using directory: /home/thevictor/.local/share/cardano-wallet/jormungandr/testnet/wallets
[cardano-wallet.application:Info:4] [2020-05-08 23:01:04.58 UTC] Wallet backend server starting. Launching Jörmungandr...
[cardano-wallet.application:Info:4] [2020-05-08 23:01:04.58 UTC] Node is Jörmungandr on testnet (0)
[cardano-wallet.network:Notice:4] [2020-05-08 23:01:04.58 UTC] Starting process jormungandr
     --genesis-block-hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
     --rest-listen 127.0.0.1:3100
     --storage /home/thevictor/.local/share/cardano-wallet/jormungandr/testnet/chain
     --config ./stakepool-config.yaml

[cardano-wallet.network:Info:4] [2020-05-08 23:01:04.58 UTC] [jormungandr.8657] Process started
May 08 23:01:04.594 INFO Starting jormungandr 0.8.18 (HEAD-690eb547, release, linux [x86_64]) - [rustc 1.42.0 (b8cedc004 2020-03-09)], task: init
May 08 23:01:04.594 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
May 08 23:01:04.595 INFO storing blockchain in '"/home/thevictor/.local/share/cardano-wallet/jormungandr/testnet/chain/blocks.sqlite"', task: init
May 08 23:01:05.259 INFO loading from storage, currently at d79f2082-00000001-0.530 processing=0ns (0ns per block) ..., task: bootstrap
[cardano-wallet.network:Info:12] [2020-05-08 23:01:05.59 UTC] Waiting for Jörmungandr to be ready on tcp/3100
[cardano-wallet.network:Notice:12] [2020-05-08 23:01:05.59 UTC] [jormungandr.8657] Terminating child process
[cardano-wallet.main:Debug:4] [2020-05-08 23:01:05.59 UTC] Logging shutdown.
cardano-wallet: ErrUnexpectedNetworkFailure (Link {_segments = ["api","v0","tip"], _queryParams = []}) (FailureResponse (Request {requestPath = (BaseUrl {baseUrlScheme = Http, baseUrlHost = "127.0.0.1", baseUrlPort = 3100, baseUrlPath = ""},"/api/v0/tip"), requestQueryString = fromList [], requestBody = Nothing, requestAccept = fromList [text/plain;charset=utf-8], requestHeaders = fromList []), requestHttpVersion = HTTP/1.1, requestMethod = "GET"} (Response {responseStatusCode = Status {statusCode = 500, statusMessage = "Internal Server Error"}, responseHeaders = fromList [("content-length","38"),("content-type","text/plain; charset=utf-8"),("date","Fri, 08 May 2020 23:01:05 GMT")], responseHttpVersion = HTTP/1.1, responseBody = "Blockchain tip not set in REST context"}))
```

---

# Resolution 

---

# QA

### LINKED ISSUE #1649: DB migration tests failing intermittently
# Context
 
DB migration test seem to be failing intermittently. In last 3 nightly builds (all of them being run on the same revision https://github.com/input-output-hk/cardano-wallet/commit/655a45952f3bbfa862140d12843e6d87a3577a6e) they failed twice, i.e.:

[NB 509](https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/509) - passed (:heavy_check_mark:)
[NB 510](https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/510#60af6023-b991-4dcb-8715-572668288d9f) - failed (:x:)
[NB 511](https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/511#e16f28bd-fab4-4d1b-a3a4-51ad7737a67f) - failed (:x:)

# Test Case

DB migration test

# Failure / Counter-example

**NB 510**
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/510#60af6023-b991-4dcb-8715-572668288d9f

Seems that Wallet stopped working (?) after migrating from `v2020-04-28` => `v2020-05-06`
```

[migration-test:Notice:4] [2020-05-09 01:13:33.74 UTC] Starting process cardano-wallet-jormungandr
--
  | launch
  | --state-dir ./state-migration-test-v2020-04-28
  | --genesis-block /nix/store/8b6in2dygz6hk29p9zpyxzhrs17cb3ni-cardano-wallet-src/lib/jormungandr/test/data/jormungandr/block0.bin
  | --
  | --secret /nix/store/8b6in2dygz6hk29p9zpyxzhrs17cb3ni-cardano-wallet-src/lib/jormungandr/test/data/jormungandr/secret.yaml
  | --config /nix/store/8b6in2dygz6hk29p9zpyxzhrs17cb3ni-cardano-wallet-src/lib/jormungandr/test/data/jormungandr/config.yaml
  |  
  | [migration-test:Info:4] [2020-05-09 01:13:33.74 UTC] [cardano-wallet-jormungandr.128152] Process started
  | [migration-test:Debug:13] [2020-05-09 01:13:33.74 UTC] [cardano-wallet-jormungandr.128152] About to waitForProcess
  | [migration-test:Debug:12] [2020-05-09 01:13:33.74 UTC] [cardano-wallet-jormungandr.128152] Running withBackend action
  | [migration-test:Notice:12] [2020-05-09 01:13:33.74 UTC] Waiting for sync
  | [cardano-wallet.network:Notice:13] [2020-05-09 01:13:33.80 UTC] [jormungandr.128078] Terminating child process
  | [cardano-wallet.main:Debug:4] [2020-05-09 01:13:33.80 UTC] Logging shutdown.
  | [migration-test:Notice:12] [2020-05-09 01:13:33.80 UTC] [cardano-wallet-jormungandr.128152] Terminating child process
  | migration-test: HttpExceptionRequest Request {
  | host                 = "localhost"
  | port                 = 8090
  | secure               = False
  | requestHeaders       = [("User-Agent","haskell wreq-0.5.3.2")]
  | path                 = "/v2/network/information"
  | queryString          = ""
  | method               = "GET"
  | proxy                = Nothing
  | rawBody              = False
  | redirectCount        = 10
  | responseTimeout      = ResponseTimeoutDefault
  | requestVersion       = HTTP/1.1

```

**NB 511**
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/511#e16f28bd-fab4-4d1b-a3a4-51ad7737a67f

This time looks like wallet stopped working at some point on migration `v2020-04-07` => `v2020-05-06`

```

cardano-wallet-jormungandr: ErrUnexpectedNetworkFailure (Link {_segments = ["api","v0","tip"], _queryParams = []}) (FailureResponse (Request {requestPath = (BaseUrl {baseUrlScheme = Http, baseUrlHost = "127.0.0.1", baseUrlPort = 33759, baseUrlPath = ""},"/api/v0/tip"), requestQueryString = fromList [], requestBody = Nothing, requestAccept = fromList [text/plain;charset=utf-8], requestHeaders = fromList []), requestHttpVersion = HTTP/1.1, requestMethod = "GET"} (Response {responseStatusCode = Status {statusCode = 500, statusMessage = "Internal Server Error"}, responseHeaders = fromList [("content-length","38"),("content-type","text/plain; charset=utf-8"),("date","Sun, 10 May 2020 01:20:01 GMT")], responseHttpVersion = HTTP/1.1, responseBody = "Blockchain tip not set in REST context"}))
--
  | [migration-test:Debug:13] [2020-05-10 01:20:01.06 UTC] [cardano-wallet-jormungandr.105008] waitForProcess returned 1
  | [migration-test:Notice:12] [2020-05-10 01:20:01.06 UTC] [cardano-wallet-jormungandr.105008] Terminating child process
  | [migration-test:Error:4] [2020-05-10 01:20:01.06 UTC] Child process cardano-wallet-jormungandr exited with status 1
  | [migration-test:Error:4] [2020-05-10 01:20:01.06 UTC] Process exited with status ExitFailure 1


```

---

# Resolution 

---

# QA

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

Resolves #1647
Resolves #1649

### Overview

Jormungandr seems to have changed the HTTP response status code for bootstrap again. This will fix the resulting error, in such a way that if the status code changes back to 503, things will still work.

### Comments

It may be better to poll the `/api/v0/node/stats`, but that would be a substantially bigger code change.

Tested with:

    cardano-wallet-jormungandr launch --port 8090 --genesis-block-hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676 --state-dir ../blockchains/state-itn_rewards_v1.2020-05-06 -- --config itn_rewards_v1-config.yaml

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]
Arf.

**Comment by KtorZ** [comment]
Nice catch.

**Review by piotr-iohk — APPROVED** [review]
:tada:

**Pull request merged**
