### PR TITLE
update alonzo-genesis.yaml in integration tests with mainnet parameters and adjust tests

### PR DESCRIPTION
**Pull request by piotr-iohk**
- 8b7c19a1344d7b26aa66380bb975299e0eec4dea
  update alonzo-genesis.yaml in integration tests with mainnet parameters and adjust tests
  
- be57e6f64c259777199a5da7a3148f9c493e5b4d
  remove integration tests on mary

### Comments

alonzo-genesis from https://hydra.iohk.io/build/7578887/download/1/index.html.

### Issue Number

ADP-1024

### CODE REVIEW

**Review by paweljakubas — APPROVED** [review]
lgtm (provided integration tests passes and does not incur additional time)

**Comment by piotr-iohk** [comment]
bors try

**Comment by piotr-iohk** [comment]
bors try

**Pull request merged**
