### PR TITLE
re-use 'deleteWallet' function to avoid logic duplication

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

#1071 

# Overview

- [ ] I have re-used 'deleteWallet' function to implement byron delete to avoid logic duplication And seemingly, share fixes when they are done..... !

# Comments

### CODE REVIEW

**Review by paweljakubas — APPROVED** [review]
LGTM!

**Review by Anviking — APPROVED** [review]

**Comment by KtorZ** [comment]
bors retry

**Pull request merged**
