### PR TITLE
[ADP-2565] Split `dbvar` into `delta-store` and `delta-types`

### PR DESCRIPTION
**Pull request by HeinrichApfelmus**
### Overview

This pull request splits the `dbvar` package into two packages:

* `delta-types` — for the pure `Delta` class and various instances
* `delta-store` — for the `Store` class.

In the future, we plan to make the `QueryStore` part of the `delta-store` library, and even absorb it into the `Store` type.

### Issue number

ADP-2565

### CODE REVIEW

**Review by paolino — APPROVED** [review]
LGTM, thanks

**Comment by HeinrichApfelmus** [comment]
bors merge

**Comment by HeinrichApfelmus** [comment]
bors merge

**Comment by HeinrichApfelmus** [comment]
🤔🤔🤔 

bors merge

**Comment by HeinrichApfelmus** [comment]
bors merge

**Comment by HeinrichApfelmus** [comment]
bors merge

**Comment by HeinrichApfelmus** [comment]
Integration tests run out of memory. 🤔 

bors merge

**Pull request merged**
