### PR TITLE
Run tests in nix release build

### PR DESCRIPTION
**Pull request by rvl**
Relates to #703 and #704.
Base branch is #864 - this should be merged first.

# Overview

- [x] This enables test suites under the Nix build.
- [x] Fixes test cases that used symlinks.
- [x] `Cardano.Wallet.Api.TypesSpec` is trying to access a file `/build/core/../../specifications/api/swagger.yaml` which is outside of its package. 
- [x] Some tests in `cardano-wallet-jormungandr:test:integration` required `jcli`.
- [x] Some tests in `cardano-wallet-jormungandr:test:integration` required a writable home directory.
- [x] In LauncherSpec the test scripts used `/usr/bin/env`, which is not in the nix-build sandbox, so i made the tests not need external scripts.
- [x] Adds macOS tests to the Hydra required jobs.

[Hydra jobset](https://hydra.iohk.io/jobset/Cardano/cardano-wallet-pr-766)

# Comments

- Symlinks/references to files in other packages won't work with the nix build because when it builds it copies the package source tree to `/build` and builds from there.

# Remaining failures

These windows-specific failures can be fixed in the next PR.

- [ ] `x86_64-pc-mingw32.tests.cardano-wallet-jormungandr.unit.x86_64-linux` expects UTF-8 encoding, but this is not the encoding that Wine is using.
- [ ] Windows cross build got broken. We now require a fix for Haskell.nix.
- [ ] `cardano-wallet-jormungandr.exe` would fail on windows at startup with
  ```
  NUL: openFile: does not exist (No such file or directory)
  ```

### CODE REVIEW

**Comment by rvl** [comment]
Here is a screenshot of the startup error I was getting before.

VirtualBox_Win10 Clone_22_10_2019_17_36_40

Currently the windows cross build is not working. It was working before. We need to update the Haskell.nix version to fix it.

**Comment by rvl** [comment]
@KtorZ @angerman The tests pass under nix-build now on Linux and macOS, so this is ready to review. We can address the windows build in the next PR.

**Review by KtorZ — APPROVED** [review]
dev / code parts LGTM. Can't tell about the Nix machinery...

**Review by craigem — APPROVED** [review]
Lools good to me.

**Pull request merged**
