### PR TITLE
Bump version from 2020.9.30 to 2020.10.13

### PR DESCRIPTION
**Pull request by jonathanknowles**
Compatible with [`jormungandr@v0.9.0`](https://github.com/input-output-hk/jormungandr/releases/tag/v0.9.0) and [`cardano-node@1.21.1`](https://github.com/input-output-hk/cardano-node/releases/tag/1.21.1).

## New Features

- Added the ability for users to select their own SMASH servers for stakepool listings. (#2214)
- Added transaction expiry slots for pending transactions. (#1879)

## Improvements

- Added a 100-wallet scenario to the latency benchmark. (#2223)
- Added an executable `shelley-test-cluster` which starts an integration test cluster that includes faucets. (#2178)
- Extended `isOurs` to return the derivation path of an address. (#2219)

## Resolved Issues

- Made pool garbage collection handle the case where the current epoch is unknown. (#2203)
- Fixed a case where the API would return incorrect mainnet network parameters. (#2226)

## Known Issues

None.

## Documentation

Cardano (cardano-node)                                                                                             | ITN (Jörmungandr)
---                                                                                                                | ---
[API Documentation](https://input-output-hk.github.io/cardano-wallet/api/v2020-10-13)                              | [API Documentation](https://input-output-hk.github.io/cardano-wallet/api/v2020-10-13)
[CLI Manual](https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface/f71ecb7ece3deaec5bf60f4a4beea1d3950e0d46) | [CLI Manual](https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface-jormungandr/f71ecb7ece3deaec5bf60f4a4beea1d3950e0d46)
[Docker Manual](https://github.com/input-output-hk/cardano-wallet/wiki/Docker/f71ecb7ece3deaec5bf60f4a4beea1d3950e0d46)                     | [Docker Manual](https://github.com/input-output-hk/cardano-wallet/wiki/Docker-jormungandr/f71ecb7ece3deaec5bf60f4a4beea1d3950e0d46)

### Cardano (cardano-node)

1. Install [`cardano-node@1.21.1`](https://github.com/input-output-hk/cardano-node/releases/tag/1.21.1).

2. Download the provided `cardano-wallet` for your platform, and uncompress it in a directory that is on your `$PATH`, e.g. `/usr/local/bin`. Or `%PATH%` on Windows.

4. Start `cardano-wallet --help` and see available parameters.

#### Docker

Pull from DockerHub and verify the version matches 2020.10.13.

```
$ docker pull inputoutput/cardano-wallet:2020.10.13
$ docker run --rm inputoutput/cardano-wallet:2020.10.13 version
```

### ITN (jormungandr)

1. Install [`jormungandr@v0.9.0`](https://github.com/input-output-hk/jormungandr/releases/tag/v0.9.0).

2. Download the provided `cardano-wallet-jormungandr` for your platform, and uncompress it in a directory that is on your `$PATH`, e.g. `/usr/local/bin`. Or `%PATH%` on Windows.

3. (optional) Install the bash/zsh auto-completion script according to the [jormungandr cli manual](https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-Command-Line-Interface/{{JORM_CLI_WIKI_COMMIT}})

4. Start `cardano-wallet --help` and see available parameters.

#### Docker

Pull from DockerHub and verify the version matches 2020.10.13

```
$ docker pull inputoutput/cardano-wallet:2020.10.13-jormungandr
$ docker run --rm inputoutput/cardano-wallet:2020.10.13-jormungandr version
```

## Signatures

Name                           | Role                | Approval
---                            | ---                 | ---:
Matthias Benkort @KtorZ        | Technical Team Lead | :hourglass:
Piotr Stachyra @piotr-iohk     | QA Engineer         | :hourglass:
Tatyana Valkevych @tatyanavych | Release Manager     | :hourglass:

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]

**Comment by KtorZ** [comment]
bors merge

**Comment by tatyanavych** [comment]
Can we change present tense to the past, e.g. "Adds" --> "Added"?

**Comment by KtorZ** [comment]
@tatyanavych this PR is not the release draft, Jonathan included a summary of the release notes as a convenient preview. The release notes will be created in a bit and we'll discuss them on Slack as we usually do :+1:

**Comment by jonathanknowles** [comment]
@tatyanavych wrote:

> Can we change present tense to the past, e.g. "Adds" --> "Added"?

Done.

**Pull request merged**
