### PR TITLE
Remove DaedalusIPC

### PR DESCRIPTION
**Pull request by rvl**
# Issue Number

Relates to [ADP-92](https://jira.iohk.io/browse/ADP-92).

# Overview

The new [cardano-launcher](https://github.com/input-output-hk/cardano-launcher) code pre-allocates TCP ports for the jormungandr backend, uses unix sockets/named pipes for the byron backend, and has a simpler method of ensuring clean shutdown of the cardano-wallet server on Windows (#1314).

# Comments

Can be merged once cardano-launcher integration into Daedalus is complete.

### CODE REVIEW

**Comment by rvl** [comment]
Rebased

**Comment by rvl** [comment]
The cardano-launcher changes are now merged into the Daedalus `develop` branch, so this PR is ready for merge.

**Review by KtorZ — APPROVED** [review]
LGTM

**Pull request merged**
