### PR TITLE
Jörmungandr 0.8.9 bump

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- 06741b82d76d6af7dff06c914d96a028bb63e37f
  regenerate arbitrary blocks
  
- 84aa54f4cc64e2a089684cbe877d42a38b81c4f6
  Bump jormungandr.nix to 0.8.9
  
- 9c19226639c6858e9b035bdebf0fe2bc63d46654
  Bump README compat table

# Comments

### CODE REVIEW

**Review by Anviking — APPROVED** [review]

**Comment by piotr-iohk** [comment]
Maybe let's refrain from merging for now -> https://input-output-rnd.slack.com/archives/GJJSEDM98/p1580361302084000

**Review by paweljakubas — APPROVED** [review]

**Comment by piotr-iohk** [comment]
bors try

**Pull request merged**
