### PR TITLE
Add `ScaleDiv` and `ScaleMod` combinators to `QuickCheck.Extra`.

### PR DESCRIPTION
**Pull request by jonathanknowles**
## Issue Number

ADP-1783

## Summary

This PR adds the `ScaleDiv` and `ScaleMod` combinators to module `QuickCheck.Extra`.

Like the standard [`Small`](https://hackage.haskell.org/package/QuickCheck-2.14.2/docs/Test-QuickCheck.html#t:Small) and [`Large`](https://hackage.haskell.org/package/QuickCheck-2.14.2/docs/Test-QuickCheck.html#t:Large) combinators, these combinators provide a convenient way to scale down the QuickCheck size parameter for a particular property argument. This can be useful if you wish to adjust the distribution of data for one property argument in isolation, without affecting the distribution of data for other property arguments.

Unlike the standard [`Small`](https://hackage.haskell.org/package/QuickCheck-2.14.2/docs/Test-QuickCheck.html#t:Small) and [`Large`](https://hackage.haskell.org/package/QuickCheck-2.14.2/docs/Test-QuickCheck.html#t:Large) combinators, `ScaleDiv` and `ScaleMod` allow more fine-grained control (useful when attempting to satisfy coverage checks) and do not require the modified type to have an `Integral` instance.

## Examples

```hs
prop_foo :: Integer -> ScaleDiv 2 Integer -> Property
prop_foo x (ScaleDiv y) = ...
```

```hs
prop_bar :: Integer -> ScaleMod 8 Integer -> Property
prop_bar x (ScaleMod y) = ...
```

### CODE REVIEW

**Comment by HeinrichApfelmus** [comment]
Looks good to me! 😊 Not sure how useful this is (especially `ScaleMod`), but why not.

My philosophy is that I don't care much for fine-tuning the distribution of QuickCheck generators; I would rather invest that time into proving that my code is correct (e.g. by refactoring and introducing lemmas.)

**Review by HeinrichApfelmus — APPROVED** [review]

**Comment by jonathanknowles** [comment]
> Not sure how useful this is

We do use combinations of `scale`, `div`, and `mod` quite a bit throughout our test suites.

I'm not sure if every single case is justified (probably not!), but here's a random sample:

```hs
lib/core/src/Cardano/Api/Gen.hs
272:                            <$> scale (`div` 3) (listOf genTxIn)
409:              <$> scale (`div` 3) (listOf (genVerificationKeyHash AsPaymentKey))
465:        [ RequireAllOf <$> scale (`mod` 10) (listOf $ recurse n)
467:        , RequireAnyOf <$> scale (`mod` 10) (listOf $ recurse n)
469:        , do ts <- scale (`mod` 10) $ listOf $ recurse n
521:    , (1, AssetName . fromString <$> (scale (min 32) (listOf genAlphaNum)))
556:        [ nub <$> scale (`div` 4) (listOf genAssetIdNoAda)
571:        [ nub <$> scale (`div` 4) (listOf genAssetIdNoAda)
```
Having these combinators gives us the option of applying these common transformations to just one parameter of a property (for example), which can be useful in certain situations.

> (especially ScaleMod)

As for `mod`, I occasionally use it when I want to limit the size parameter to be less than some value `n`, but I want to retain a fairly uniform distribution of values from `0` to `n - 1`, and don't want to artificially increase the frequency of values at the upper limit (which would be the case if we used `scale` with `min`, for example).

**Comment by jonathanknowles** [comment]
> My philosophy is that I don't care much for fine-tuning the distribution of QuickCheck generators; I would rather invest that time into proving that my code is correct (e.g. by refactoring and introducing lemmas.)

Sounds like a great topic for a longer discussion!

Though I would just mention that the ability to fine-tune generators is sometimes useful to limit the running time or memory usage of a property test. This assumes of course that there is value to be gained by having a property test in the first place.

**Comment by jonathanknowles** [comment]
I'm going to merge this PR manually, as:

- all test suites pass locally
- all test suites pass on CI (after retrying)
- all test failures due to flaky tests have been categorized

**Pull request merged**
