### PR TITLE
Split Servant API client code into Cardano.Wallet.Api.Client

### PR DESCRIPTION
**Pull request by rvl**
Relates to #1177

# Overview

- Splits out part of PR #1139.
- The typed client code is useful outside of the CLI.

### CODE REVIEW

**Review by paweljakubas — APPROVED** [review]

**Review by KtorZ — APPROVED** [review]
LGTM

**Comment by rvl** [comment]
Bors said the batch was cancelled - this could have been because a commit was pushed directly to master while it was building.

bors r+

**Comment by KtorZ** [comment]
@rvl yes, I think I merged another PR manually after a "bors try", I thought bors would simply retry.

**Pull request merged**
