### PR TITLE
Only show actual metrics in EKG

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by hasufell** [comment]
Note, we currently have RTS twice though:

<details>
<summary> ekg
</summary>

```
{
  "iohk-monitoring version": {
    "type": "l",
    "val": "0.1.10.1"
  },
  "ekg": {
    "server_timestamp_ms": {
      "type": "c",
      "val": 1607444725345
    }
  },
  "rts": {
    "gc": {
      "gc_cpu_ms": {
        "type": "c",
        "val": 14622
      },
      "mutator_wall_ms": {
        "type": "c",
        "val": 914872
      },
      "mutator_cpu_ms": {
        "type": "c",
        "val": 4376
      },
      "gc_wall_ms": {
        "type": "c",
        "val": 14686
      },
      "wall_ms": {
        "type": "c",
        "val": 929558
      },
      "bytes_copied": {
        "type": "c",
        "val": 7552998936
      },
      "init_wall_ms": {
        "type": "c",
        "val": 1
      },
      "init_cpu_ms": {
        "type": "c",
        "val": 0
      },
      "max_bytes_used": {
        "type": "g",
        "val": 28486488
      },
      "max_bytes_slop": {
        "type": "g",
        "val": 1107112
      },
      "num_bytes_usage_samples": {
        "type": "c",
        "val": 1131
      },
      "peak_megabytes_allocated": {
        "type": "g",
        "val": 49
      },
      "cpu_ms": {
        "type": "c",
        "val": 18998
      },
      "current_bytes_used": {
        "type": "g",
        "val": 21088264
      },
      "bytes_allocated": {
        "type": "c",
        "val": 3101926024
      },
      "par_max_bytes_copied": {
        "type": "g",
        "val": 0
      },
      "current_bytes_slop": {
        "type": "g",
        "val": 681976
      },
      "cumulative_bytes_used": {
        "type": "c",
        "val": 23728950624
      },
      "num_gcs": {
        "type": "c",
        "val": 3775
      },
      "par_tot_bytes_copied": {
        "type": "g",
        "val": 0
      },
      "par_avg_bytes_copied": {
        "type": "g",
        "val": 0
      }
    }
  },
  "cardano-wallet": {
    "metrics": {
      "Net": {
        "IpExt:InOctets": {
          "B": {
            "type": "g",
            "val": 4314844464
          }
        },
        "IpExt:OutOctets": {
          "B": {
            "type": "g",
            "val": 362264407
          }
        }
      },
      "Mem": {
        "size": {
          "int": {
            "type": "g",
            "val": 268616169
          }
        },
        "text": {
          "int": {
            "type": "g",
            "val": 5880
          }
        },
        "data": {
          "int": {
            "type": "g",
            "val": 36081
          }
        },
        "resident": {
          "int": {
            "type": "g",
            "val": 21673
          }
        },
        "shared": {
          "int": {
            "type": "g",
            "val": 6795
          }
        }
      },
      "IO": {
        "rchar": {
          "B": {
            "type": "g",
            "val": 1847595674
          }
        },
        "syscw": {
          "int": {
            "type": "g",
            "val": 123480
          }
        },
        "rbytes": {
          "B": {
            "type": "g",
            "val": 0
          }
        },
        "wchar": {
          "B": {
            "type": "g",
            "val": 233536628
          }
        },
        "cxwbytes": {
          "B": {
            "type": "g",
            "val": 0
          }
        },
        "syscr": {
          "int": {
            "type": "g",
            "val": 496906
          }
        },
        "wbytes": {
          "B": {
            "type": "g",
            "val": 235409408
          }
        }
      },
      "Sys": {
        "Platform": {
          "int": {
            "type": "g",
            "val": 1
          }
        },
        "Pid": {
          "int": {
            "type": "g",
            "val": 24129
          }
        }
      },
      "Stat": {
        "starttime": {
          "int": {
            "type": "g",
            "val": 11206660
          }
        },
        "cputicks": {
          "int": {
            "type": "g",
            "val": 1968
          }
        },
        "startcode": {
          "int": {
            "type": "g",
            "val": 4194304
          }
        },
        "cguesttime": {
          "int": {
            "type": "g",
            "val": 0
          }
        }
      },
      "RTS": {
        "maxUsedMemBytes": {
          "B": {
            "type": "g",
            "val": 51380224
          }
        },
        "gcCpuNs": {
          "ns": {
            "type": "g",
            "val": 14165256000
          }
        },
        "maxCompactBytes": {
          "B": {
            "type": "g",
            "val": 0
          }
        },
        "maxLargeBytes": {
          "B": {
            "type": "g",
            "val": 22008936
          }
        },
        "bytesAllocated": {
          "B": {
            "type": "g",
            "val": 3089737640
          }
        },
        "cpuNs": {
          "ns": {
            "type": "g",
            "val": 18507082000
          }
        },
        "gcMajorNum": {
          "int": {
            "type": "g",
            "val": 1094
          }
        },
        "gcCopiedBytes": {
          "B": {
            "type": "g",
            "val": 6637152
          }
        },
        "elapsedNs": {
          "ns": {
            "type": "g",
            "val": 900058214150
          }
        },
        "liveBytes": {
          "B": {
            "type": "g",
            "val": 22948647520
          }
        },
        "gcNum": {
          "int": {
            "type": "g",
            "val": 3737
          }
        },
        "maxSlopBytes": {
          "B": {
            "type": "g",
            "val": 1107112
          }
        },
        "gcElapsedNs": {
          "ns": {
            "type": "g",
            "val": 14225824435
          }
        },
        "maxLiveBytes": {
          "B": {
            "type": "g",
            "val": 28486488
          }
        },
        "gcLiveBytes": {
          "B": {
            "type": "g",
            "val": 21088648
          }
        }
      }
    }
  }
}
```

</details>

Once from the underlying `ekg` library I believe and once from iohk-monitoring itself. The latter is more powerful. I believe the node doesn't filter out the former either. We could?

**Comment by Anviking** [comment]
Without a reference to an open bug, I think this is an "improvement"? _changed tag_

Trying locally I see:
<details>
<summary>Master
</summary>

```json
{
  "iohk-monitoring version": {
    "type": "l",
    "val": "0.1.10.1"
  },
  "ekg": {
    "server_timestamp_ms": {
      "type": "c",
      "val": 1607520800457
    }
  },
  "rts": {
    "gc": {
      "gc_cpu_ms": {
        "type": "c",
        "val": 1266
      },
      "mutator_wall_ms": {
        "type": "c",
        "val": 147060
      },
      "mutator_cpu_ms": {
        "type": "c",
        "val": 82192
      },
      "gc_wall_ms": {
        "type": "c",
        "val": 1361
      },
      "wall_ms": {
        "type": "c",
        "val": 148420
      },
      "bytes_copied": {
        "type": "c",
        "val": 260218392
      },
      "init_wall_ms": {
        "type": "c",
        "val": 2
      },
      "init_cpu_ms": {
        "type": "c",
        "val": 0
      },
      "max_bytes_used": {
        "type": "g",
        "val": 3437568
      },
      "max_bytes_slop": {
        "type": "g",
        "val": 101592
      },
      "num_bytes_usage_samples": {
        "type": "c",
        "val": 5
      },
      "peak_megabytes_allocated": {
        "type": "g",
        "val": 9
      },
      "cpu_ms": {
        "type": "c",
        "val": 83458
      },
      "current_bytes_used": {
        "type": "g",
        "val": 4202328
      },
      "bytes_allocated": {
        "type": "c",
        "val": 144713428104
      },
      "par_max_bytes_copied": {
        "type": "g",
        "val": 0
      },
      "current_bytes_slop": {
        "type": "g",
        "val": 123048
      },
      "cumulative_bytes_used": {
        "type": "c",
        "val": 11749024
      },
      "num_gcs": {
        "type": "c",
        "val": 139723
      },
      "par_tot_bytes_copied": {
        "type": "g",
        "val": 0
      },
      "par_avg_bytes_copied": {
        "type": "g",
        "val": 0
      }
    }
  },
  "cardano-wallet": {
    "pools-engine": {
      "type": "l",
      "val": "\"\\\"Applying blocks [15954441 ... 15954441]\\\"\""
    },
    "metrics": {
      "Net": {
        "ifn_\"summary\"": {
          "int": {
            "type": "g",
            "val": 0
          }
        },
        "ifd_0-opackets": {
          "int": {
            "type": "g",
            "val": 139758179
          }
        },
        "ifd_0-ipackets": {
          "int": {
            "type": "g",
            "val": 155080721
          }
        },
        "interfaces": {
          "int": {
            "type": "g",
            "val": 15
          }
        },
        "ifd_0-omcast": {
          "int": {
            "type": "g",
            "val": 0
          }
        },
        "ifd_0-collisions": {
          "int": {
            "type": "g",
            "val": 0
          }
        },
        "ifd_0-obytes": {
          "B": {
            "type": "g",
            "val": 1683494912
          }
        },
        "ifd_0-oerrors": {
          "int": {
            "type": "g",
            "val": 47948
          }
        },
        "ifd_0-mtu": {
          "B": {
            "type": "g",
            "val": 37404
          }
        },
        "ifd_0-imcast": {
          "int": {
            "type": "g",
            "val": 1567702
          }
        },
        "ifd_0-ierrors": {
          "int": {
            "type": "g",
            "val": 0
          }
        },
        "ifd_0-ibytes": {
          "B": {
            "type": "g",
            "val": 2915225600
          }
        }
      },
      "Mem": {
        "resident_size": {
          "B": {
            "type": "g",
            "val": 39170048
          }
        },
        "resident_size_max": {
          "B": {
            "type": "g",
            "val": 39170048
          }
        },
        "virtual_size": {
          "B": {
            "type": "g",
            "val": 1104025124864
          }
        },
        "Pid": {
          "int": {
            "type": "g",
            "val": 12774
          }
        }
      },
      "IO": {
        "ndisks": {
          "int": {
            "type": "g",
            "val": 0
          }
        }
      },
      "Sys": {
        "boot_time": {
          "s": {
            "type": "g",
            "val": 1605368207
          }
        },
        "Platform": {
          "int": {
            "type": "g",
            "val": 2
          }
        },
        "SysUserTime": {
          "ns": {
            "type": "g",
            "val": 16758986000
          }
        },
        "SystemTime": {
          "ns": {
            "type": "g",
            "val": 6474368000
          }
        },
        "CPUTime": {
          "ns": {
            "type": "g",
            "val": 23233354000
          }
        },
        "IdleTime": {
          "ns": {
            "type": "g",
            "val": 41387324000
          }
        },
        "NiceTime": {
          "ns": {
            "type": "g",
            "val": 0
          }
        }
      },
      "Stat": {
        "system_time": {
          "ns": {
            "type": "g",
            "val": 4294967296000
          }
        },
        "user_time": {
          "ns": {
            "type": "g",
            "val": 0
          }
        },
        "suspend_count": {
          "int": {
            "type": "g",
            "val": 4294967296
          }
        },
        "Pid": {
          "int": {
            "type": "g",
            "val": 12774
          }
        },
        "policy": {
          "int": {
            "type": "g",
            "val": 1
          }
        }
      },
      "RTS": {
        "maxUsedMemBytes": {
          "B": {
            "type": "g",
            "val": 9437184
          }
        },
        "gcCpuNs": {
          "ns": {
            "type": "g",
            "val": 1002251000
          }
        },
        "maxCompactBytes": {
          "B": {
            "type": "g",
            "val": 0
          }
        },
        "maxLargeBytes": {
          "B": {
            "type": "g",
            "val": 2758376
          }
        },
        "bytesAllocated": {
          "B": {
            "type": "g",
            "val": 116454886328
          }
        },
        "cpuNs": {
          "ns": {
            "type": "g",
            "val": 67430170000
          }
        },
        "gcMajorNum": {
          "int": {
            "type": "g",
            "val": 5
          }
        },
        "gcCopiedBytes": {
          "B": {
            "type": "g",
            "val": 1952
          }
        },
        "elapsedNs": {
          "ns": {
            "type": "g",
            "val": 120014128650
          }
        },
        "liveBytes": {
          "B": {
            "type": "g",
            "val": 11749024
          }
        },
        "gcNum": {
          "int": {
            "type": "g",
            "val": 112438
          }
        },
        "maxSlopBytes": {
          "B": {
            "type": "g",
            "val": 101592
          }
        },
        "gcElapsedNs": {
          "ns": {
            "type": "g",
            "val": 1078659282
          }
        },
        "maxLiveBytes": {
          "B": {
            "type": "g",
            "val": 3437568
          }
        },
        "gcLiveBytes": {
          "B": {
            "type": "g",
            "val": 4058624
          }
        }
      }
    },
    "application": {
      "type": "l",
      "val": "\"\\\"Node is Haskell Node on mainnet.\\\"\""
    },
    "main": {
      "type": "l",
      "val": "\"\\\"Wallet backend server listening on 127.0.0.1:8090\\\"\""
    },
    "ntp-client": {
      "type": "l",
      "val": "\"\\\"local clock is drifting by 1318221\\206\\188s\\\"\""
    },
    "network": {
      "type": "l",
      "val": "\"\\\"Query GetCurrentPParams took 0.00028s\\\"\""
    },
    "pools-db": {
      "type": "l",
      "val": "\"\\\"Will open db at wallet-db3/stake-pools.sqlite\\\"\""
    }
  }
}
```

</details>

<details>
<summary>This PR
</summary>

```json
{
  "iohk-monitoring version": {
    "type": "l",
    "val": "0.1.10.1"
  },
  "ekg": {
    "server_timestamp_ms": {
      "type": "c",
      "val": 1607520426177
    }
  },
  "rts": {
    "gc": {
      "gc_cpu_ms": {
        "type": "c",
        "val": 1283
      },
      "mutator_wall_ms": {
        "type": "c",
        "val": 149775
      },
      "mutator_cpu_ms": {
        "type": "c",
        "val": 82106
      },
      "gc_wall_ms": {
        "type": "c",
        "val": 1384
      },
      "wall_ms": {
        "type": "c",
        "val": 151159
      },
      "bytes_copied": {
        "type": "c",
        "val": 280706472
      },
      "init_wall_ms": {
        "type": "c",
        "val": 2
      },
      "init_cpu_ms": {
        "type": "c",
        "val": 0
      },
      "max_bytes_used": {
        "type": "g",
        "val": 4530192
      },
      "max_bytes_slop": {
        "type": "g",
        "val": 106480
      },
      "num_bytes_usage_samples": {
        "type": "c",
        "val": 4
      },
      "peak_megabytes_allocated": {
        "type": "g",
        "val": 9
      },
      "cpu_ms": {
        "type": "c",
        "val": 83389
      },
      "current_bytes_used": {
        "type": "g",
        "val": 6332656
      },
      "bytes_allocated": {
        "type": "c",
        "val": 156386617840
      },
      "par_max_bytes_copied": {
        "type": "g",
        "val": 0
      },
      "current_bytes_slop": {
        "type": "g",
        "val": 171792
      },
      "cumulative_bytes_used": {
        "type": "c",
        "val": 9738720
      },
      "num_gcs": {
        "type": "c",
        "val": 150990
      },
      "par_tot_bytes_copied": {
        "type": "g",
        "val": 0
      },
      "par_avg_bytes_copied": {
        "type": "g",
        "val": 0
      }
    }
  },
  "cardano-wallet": {
    "metrics": {
      "Net": {
        "ifn_\"summary\"": {
          "int": {
            "type": "g",
            "val": 0
          }
        },
        "ifd_0-opackets": {
          "int": {
            "type": "g",
            "val": 139752668
          }
        },
        "ifd_0-ipackets": {
          "int": {
            "type": "g",
            "val": 155077047
          }
        },
        "interfaces": {
          "int": {
            "type": "g",
            "val": 15
          }
        },
        "ifd_0-omcast": {
          "int": {
            "type": "g",
            "val": 0
          }
        },
        "ifd_0-collisions": {
          "int": {
            "type": "g",
            "val": 0
          }
        },
        "ifd_0-obytes": {
          "B": {
            "type": "g",
            "val": 1682702336
          }
        },
        "ifd_0-oerrors": {
          "int": {
            "type": "g",
            "val": 47948
          }
        },
        "ifd_0-mtu": {
          "B": {
            "type": "g",
            "val": 37404
          }
        },
        "ifd_0-imcast": {
          "int": {
            "type": "g",
            "val": 1567105
          }
        },
        "ifd_0-ierrors": {
          "int": {
            "type": "g",
            "val": 0
          }
        },
        "ifd_0-ibytes": {
          "B": {
            "type": "g",
            "val": 2914417664
          }
        }
      },
      "Mem": {
        "resident_size": {
          "B": {
            "type": "g",
            "val": 39682048
          }
        },
        "resident_size_max": {
          "B": {
            "type": "g",
            "val": 39682048
          }
        },
        "virtual_size": {
          "B": {
            "type": "g",
            "val": 1104008347648
          }
        },
        "Pid": {
          "int": {
            "type": "g",
            "val": 12161
          }
        }
      },
      "IO": {
        "ndisks": {
          "int": {
            "type": "g",
            "val": 0
          }
        }
      },
      "Sys": {
        "boot_time": {
          "s": {
            "type": "g",
            "val": 1605368207
          }
        },
        "Platform": {
          "int": {
            "type": "g",
            "val": 2
          }
        },
        "SysUserTime": {
          "ns": {
            "type": "g",
            "val": 8831659000
          }
        },
        "SystemTime": {
          "ns": {
            "type": "g",
            "val": 23799041000
          }
        },
        "CPUTime": {
          "ns": {
            "type": "g",
            "val": 32630700000
          }
        },
        "IdleTime": {
          "ns": {
            "type": "g",
            "val": 35125727000
          }
        },
        "NiceTime": {
          "ns": {
            "type": "g",
            "val": 0
          }
        }
      },
      "Stat": {
        "system_time": {
          "ns": {
            "type": "g",
            "val": 4294967296000
          }
        },
        "user_time": {
          "ns": {
            "type": "g",
            "val": 0
          }
        },
        "suspend_count": {
          "int": {
            "type": "g",
            "val": 28145195568594944
          }
        },
        "Pid": {
          "int": {
            "type": "g",
            "val": 12161
          }
        },
        "policy": {
          "int": {
            "type": "g",
            "val": 1
          }
        }
      },
      "RTS": {
        "maxUsedMemBytes": {
          "B": {
            "type": "g",
            "val": 9437184
          }
        },
        "gcCpuNs": {
          "ns": {
            "type": "g",
            "val": 1272359000
          }
        },
        "maxCompactBytes": {
          "B": {
            "type": "g",
            "val": 0
          }
        },
        "maxLargeBytes": {
          "B": {
            "type": "g",
            "val": 3192048
          }
        },
        "bytesAllocated": {
          "B": {
            "type": "g",
            "val": 155199737456
          }
        },
        "cpuNs": {
          "ns": {
            "type": "g",
            "val": 82755601000
          }
        },
        "gcMajorNum": {
          "int": {
            "type": "g",
            "val": 4
          }
        },
        "gcCopiedBytes": {
          "B": {
            "type": "g",
            "val": 2000
          }
        },
        "elapsedNs": {
          "ns": {
            "type": "g",
            "val": 150013808556
          }
        },
        "liveBytes": {
          "B": {
            "type": "g",
            "val": 9738720
          }
        },
        "gcNum": {
          "int": {
            "type": "g",
            "val": 149844
          }
        },
        "maxSlopBytes": {
          "B": {
            "type": "g",
            "val": 106480
          }
        },
        "gcElapsedNs": {
          "ns": {
            "type": "g",
            "val": 1372698947
          }
        },
        "maxLiveBytes": {
          "B": {
            "type": "g",
            "val": 4530192
          }
        },
        "gcLiveBytes": {
          "B": {
            "type": "g",
            "val": 6307584
          }
        }
      }
    }
  }
}
```
</details>

But I don't see why the difference is. Both contain both a `rts` and a `."cardano-wallet".metrics.RTS` — is that the duplication? Clearly stating this in the PR description (and/or commit message) wouldn't hurt :)

> Once from the underlying ekg library I believe and once from iohk-monitoring itself. The latter is more powerful. I believe the node doesn't filter out the former either. We could?

Sounds good to me though, but I also don't know for sure.

**Comment by hasufell** [comment]
> But I don't see why the difference is. Both contain both a rts and a ."cardano-wallet".metrics.RTS — is that the duplication?

Yes, hence the question whether we want to drop `rts`. But the PR is more about removing the log messages from the output:

```
    "application": {
      "type": "l",
      "val": "\"\\\"Node is Haskell Node on mainnet.\\\"\""
    },
    "main": {
      "type": "l",
      "val": "\"\\\"Wallet backend server listening on 127.0.0.1:8090\\\"\""
    },
    "ntp-client": {
      "type": "l",
      "val": "\"\\\"local clock is drifting by 1318221\\206\\188s\\\"\""
    },
    "network": {
      "type": "l",
      "val": "\"\\\"Query GetCurrentPParams took 0.00028s\\\"\""
    },
    "pools-db": {
      "type": "l",
      "val": "\"\\\"Will open db at wallet-db3/stake-pools.sqlite\\\"\""
    }
```

These aren't metrics, so we don't want them.

**Review by Anviking — APPROVED** [review]
Ok sure. Although, aren't they cool to have in a way?
Skärmavbild 2020-12-09 kl  15 16 39

I presume we could (in the future) tweak the logging of these to get nice live graphs of the block height of various workers, etc.

**Comment by hasufell** [comment]
> Ok sure. Although, aren't they cool to have in a way?

I believe @KtorZ has a different opinion on that.

**Comment by KtorZ** [comment]
> @Anviking Although, aren't they cool to have in a way?

They are. But not in a format that is not processable by a program. ekg is not for us humans, it's for monitoring systems. Thus, if we want to expose things like the last known tip or the ntp drift offset, we should make sure the output is digestible and not ` "\"\\\"local clock is drifting by 1318221\\206\\188s\\\"\""` :|

**Comment by Anviking** [comment]
bors r-

https://input-output-rnd.slack.com/archives/CAP8NM7N0/p1607953126438000?thread_ts=1607951891.437300&cid=CAP8NM7N0

**Pull request merged**
