### PR TITLE
Bump version numbers for release of v2022-08-16

### PR DESCRIPTION
**Pull request by HeinrichApfelmus**
- [x] Bump dependencies to match `cardano-node` 1.35.3
- [x] Bump dependency on `cardano-addresses`.
- [x] Bump `cardano-wallet` version number to `2022.8.16`.

### Comments

In preparation for a release, this pull request bumps dependencies and the package  version number.

### Issue Number

ADP-1999

### CODE REVIEW

**Comment by HeinrichApfelmus** [comment]
bors try

**Review by jonathanknowles — APPROVED** [review]
LGTM!

**Comment by HeinrichApfelmus** [comment]
bors merge

**Comment by HeinrichApfelmus** [comment]
bors merge

**Comment by HeinrichApfelmus** [comment]
bors retry

**Comment by HeinrichApfelmus** [comment]
I intend to merge this pull request manually, because:

* There is at least one run where all tests pass (https://hydra.iohk.io/build/17841392)
* The flakiness of our integration tests had increased before this pull request
* The pull request only adds version information or bumps dependencies which should unrelated to integration tests.

However, we'll first make another bors attempt with the fixes by @Anviking .

**Comment by HeinrichApfelmus** [comment]
bors merge

**Pull request merged**
