### PR TITLE
Fix jormungandr integration tests on Windows and Wine.

### PR DESCRIPTION
**Pull request by rvl**
### Issue number

#1283 

### Overview

- [x] Fix stuck jormungandr process in launcher cli integration tests on windows.

### CODE REVIEW

**Comment by KtorZ** [comment]
How come this was passing before?

**Comment by rvl** [comment]
> How come this was passing before?

@KtorZ These tests were not testing whether the node was working correctly, just that it was running. What happens when the `--config` file is missing is that jormungandr loops indefinitely printing this message:

    Mar 19 23:15:23.900 ERRO trusted-peers cannot be empty. to avoid bootstrap use 'skip_bootstrap: true', task: bootstrap
    Mar 19 23:15:23.900 INFO bootstrap attempt #1 failed, trying again in 5 seconds..., task: bootstrap

Why these tests do not exit under this circumstance, I do not know, and at this stage we probably don't need to know...

**Comment by Anviking** [comment]
Is this still failing? I cannot find a recent run of the jormungandr integration tests

Skärmavbild 2020-04-07 kl  13 24 08

**Comment by rvl** [comment]
It would probably still be failing except that I removed jormungandr integration tests from Hydra because we are not running them on Buildkite either.
Whether we merge or close this probably doesn't make much difference.

**Review by Anviking — APPROVED** [review]

**Pull request merged**
