### PR TITLE
Lenses integration tests 2

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

#1237 

# Overview

- 5ac1ccb820e2fa5f595b9ea2ce8bd077f3ed233d
  Remove delegation lens
  
- d318824641db81397bc1afa52506f6b9c2f98b51
  Remove passphraseLastUpdate lens
  
- 61c13bbcb38a65e715dec92a5de033b277057f27
  Remove walletName lens
  
- d73ba40e2612a9173db6e02ee7f488116752fc6e
  Remove amount lens
  
- f3f82eb43d4a6fbb81d6abfa2db1d2c9b27454cc
  Remove direction lens
  
- ad59dd0fe9dd7ea462de7e57c33a999e1488662c
  Remove status lens
  
- ae44680fbf2960b24474c16c5cd96095327562d6
  Remove syncProgress lens
  
- 5caaf88507c5529bea13a8e1b73b062560753c12
  Remove apparentPerformance lens
  
- c7c27c4151d84b5a203fce113b2fa74e89e256f9
  Remove metrics, stake, blocks, nextEpoch lenses
  
- dcd45a7ad8bfbb0718a6aec109cefacf2f0a0f86
  Remove feeEstimator lens
  
- 0c3578a6215fba48d67308fdd3562f98e0656490
  Remove input, output lenses
  
- f51cc75508e24df1a2afd13eba775b2f5d5feea6
  Remove coinSelectionInputs, coinSelectionOutputs lenses and rebase

# Comments

All defined lenses removed from `DSL.hs` except for `walletId`, which perhaps we might save, since it seems to be handy?

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]
bors r+

**Review by paweljakubas — APPROVED** [review]
LGTM!

**Comment by piotr-iohk** [comment]
Failed on:

```
Failures:
--
  |  
  | src/Test/Integration/Framework/DSL.hs:319:16:
  | 1) API Specifications TRANS_CREATE_02 - Multiple Output Tx to single wallet
  | expected: Quantity {getQuantity = 800000000000}
  | but got: Quantity {getQuantity = 999999999966}
```
Updated -> https://github.com/input-output-hk/cardano-wallet/issues/1284

**Pull request merged**
