### PR TITLE
Relocate Jörmungandr-specific metadata & pools code inside `cardano-wallet-jormungandr`

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

#1595

# Overview

- 321f18093b0c8e7f0f564efa8964e40553cb3359
  :round_pushpin: **move and rename pool Metadata, Metrics and Performance inside the Jörmungandr package**
  The cardano-node implementation will actually be drastically different, to instead of trying to share any sort of implementation here,
we'll instead revise this implementation completely. This follows the original plan and explains why the 'Pool' modules were kept
isolated from the rest: to be easy to remove and replace.

- 74b8228d36adb4f22daff12da860e4ea35b5685b
  :round_pushpin: **Move 'StakePoolMetadata' inside '..Primitive.Types'**
  Although the underlying implementation of 'how we get metadata' is different, the overall presentation type
remains the same and is fortunately based on the formal specifications description in the case of both
jormungandr and cardano-node. This type can therefore live in the shared part (which is actually mandatory
since also used by the API layer).

- 2271393980a1646dd47a8775a8f2d3be4342be7b
  :round_pushpin: **move servers instanciations in their corresponding backend package**
  Instead of having these awkward declaration side-by-side, this allows for a better division of what's needed by
one package or the other, and better show what actually is the common code between both.

- b09616d28f209b62bb12d3b56c34e095162a3ff6
  :round_pushpin: **Regenerate nix**
  
- 73d57c663640ea3b572084ddda2eb3b08c05ad34
  :round_pushpin: **move testdata zip fake registry for metadata spec**

# Comments

~~/!\ Running jormungandr tests locally to see if everything still holding up there...~~ -> done, passes.

### CODE REVIEW

**Comment by KtorZ** [comment]
bors try

**Review by Anviking — APPROVED** [review]
Lgtm. The relocation sounds like a good idea 👍

**Comment by Anviking** [comment]
From the commits it looked as you didn't change `StakePoolMetadata`, but from the failing golden it looks like you did? 🤔 
```patch
-    "seed": 7984932456561319472,
+    "seed": 2974842441665278901,
     "samples": [
         {
-            "homepage": "m㰹�<91>��jns�<98>��\u0017�<9A>�q�<9C><9D><9C>s�<8B>���<8F>���<8E>�<9A>*Or",
-            "ticker": "TWp\u001b",
-            "pledge_address": "/�<8B><96>��<9F><85>tf\u001dxZ�<90>"
+            "homepage": "e�<9E><84><98>{�<91>���<81><9E><9D>S/rSY\u000b\u001c�<99><89>1𡨷^?p\u001bp44񹭧?񫡮.�<88>n`-\u0000c�<8B><87><8D>2`\u0005\u001fo\u0002\r�<98>N\u0007\u0019y���<86>L�<8A>��2mO�<86>�Y>2i\u00013�<95>�<84>�<99>",
+            "owner": "ed25519_pk1tpjaa33qj2axq42lhjsj8h78jcwa2evwnap4vcas636luxzhg2hs8vhyfu",
+            "name": "-\n'0&^?�<91><90><83>)\u001ag�<96><91><96>\u0000=%,r�<9E>za�<85>�<92>7\u0000Fa�<94>��\u000c\u001dR\u0019d\u001cP_�<88>���<87>�T\"M:\t�<8F>��\u0011!�<9A><81><99><C�
<97>�祡\u0008",
+            "ticker": "x�<95><8E><82>e=\u0005",
+            "pledge_address": "f�<8C>��_�<9D>�<93>�<92><9D>�y�<80>��b\u001f/x\u0006.�<8F><8B>��<85><87>\u0011\u000eT\u0001�<88>���<8B><92>",
+            "description": "C�<94>�\u0014mL_�<9F>�:/�<93>�<96>\u001478t�<97>��<8C>�"
         },
         {
-            "homepage": "�<89><90><87>",
-            "ticker": "񱾬p?`",
-            "pledge_address": "\u0018�<8E>'�<88>��^\u0007�<8C>�"
+            "homepage": "%\u0016\\�<8A>;42�<9F><9D><88>",
+            "owner": "ed25519_pk1yqykca80pfh6a6grf8rg8w3z4py4yqn96s33sft83pku5deqcxmscjuz0g",
+            "name": "[�<99><91><98>\u0004+�<85>��<90>�<85>o.p񩩲Q%t\u0017\u0010\u0001f>�<97>��\u0007|�<91>���<9D><9E>tG9j0�<9E><99>�<90>�<82>R=�<90>�<8C>d=�<91>��<8F><97>�<93>�<89>E$",
+            "ticker": "�<92><9F>�3\u0016�<9A><95>�\u001c",
+            "pledge_address": "^�<9C>���<9A><8F>J<p�<9C><92>�JCyRv2\u0008||毭?#MK\"\"�<8D>7a\u000fr)!�<9A>TgB�<9E>��s�<9E><91>��<80>�<90>&[UB",
+            "description": "�<8E>��<89>��U�<86>jG\u0014�<88><84>�\u0001N�<96>�b&�<90>��\u001d�<88>��#�<91><85>\u0018w�<9D>�Cv�<93>���<99>�<97>3)5�<9A>�󯼣%0g𱮸D�<92>ua)b\u0002�
<8D>T�<94>�<93>�<9E>\u0011mf�<86>�񺛭,\u0019󴰻q&�<98><81><91>C�<87>���<9C><86>�<91>$�<81>q�<81><8D><91>X�<8E>��򵾷`�<8C>Ia�<84>��P\u0013Z�<82><98>z�<99>T㛯vh8R-�<89><9A><93>\u0����01b\u0019;\u000cC-D!<�<88><91><82>mC�<98><8B>^t�<88>��)�<8B><8F>�\u0001�<9D>�q�<84>�<8A>,\u0007<I\u000f�<90><85><82>P\u0019�<89>�󴿷V3L/�<87>�<98>C\u001c󛤹�<80><90>&I\u0016\u000b�
�����<��<9A>'�<89><99>򢩤}\u001b\u0008>{u8i\u0012\u0017󢽧�<81>��=`e򢹛\u001bxT./\u001f%|dv;�<87>tLrTB\t.�<8D><82>\u0003�<8E>�a�<84>]\u0013�<8D>�'�<86>��\u001c>[\u0012�<8D><90>C6>B\r�
�����<���\<96>�<88>m�<81>�<89>C|G~\u000f\u001bL�<8B><9D><86>l\u000f�<83><95>?\u00106To�<9F>�*0$M\u0005~8R�<90>���<93>��<9E><90><89>\r0\u001au}E~SA"
         },
```

**Comment by KtorZ** [comment]
Yes, I am not sure either at the moment. I wonder if the _location of the file_ has an influence on the seed for the golden test :shrug: ... I haven't really got any time to look into this today so I'll tomorrow.

**Review by rvl — APPROVED** [review]

**Pull request merged**
