### PR TITLE
Jormungandr 0.8.0 rc8 -> 0.8.0

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- [x] Jormungandr 0.8.0 rc8 -> 0.8.0
- [x] Update of arbitrary blocks for golden tests
- [x] update of genesis.yaml with optional parameters introduced in 0.8.0 and regenerate genesis block

# Comments

### CODE REVIEW

**Comment by piotr-iohk** [comment]
bors try

**Comment by KtorZ** [comment]
we'll to adjust the integration `genesis.yaml` to accomodate the breaking changes and, re-generate the `block0.bin`

**Comment by piotr-iohk** [comment]
bors try

**Comment by piotr-iohk** [comment]
bors try

**Review by KtorZ — APPROVED** [review]

**Comment by KtorZ** [comment]
sounds like there is a breaking change in the binary format after all...

**Comment by piotr-iohk** [comment]
> sounds like there is a breaking change in the binary format after all...

Yes, but since there is rc11 already, let me grab it first maybe...

**Comment by KtorZ** [comment]
:man_facepalming:

**Comment by piotr-iohk** [comment]
bors try

**Comment by piotr-iohk** [comment]
Now I have:
- updated `jormungandr.nix` to 0.8.0
- regenerated arbotrary-blocks
- updated genesis.yaml with new optional params and regenerated genesis block.

Wallet fails to start:
```
[cardano-wallet:Alert:18] [2019-12-12 08:15:55.89 UTC] As far as I can tell, this isn't a valid block file: ../block0.bin
```

**Pull request merged**
