### PR TITLE
[ADP-2565] Export `Store` from `Data.Store` only

### PR DESCRIPTION
**Pull request by HeinrichApfelmus**
### Overview

This pull request changes the `Data.DBVar` module to no longer export the `Store` type. This pull request also renames `Test.DBVar` to `Test.Store`.

This is a pure refactoring of module exports and imports.

### Issue number

ADP-2565

### CODE REVIEW

**Review by paolino — APPROVED** [review]
import golfing ... hole!

**Comment by HeinrichApfelmus** [comment]
bors merge

**Comment by HeinrichApfelmus** [comment]
Out of memory again. 🙄 

bors merge

**Comment by HeinrichApfelmus** [comment]
bors merge

**Pull request merged**
