### PR TITLE
Jormungandr 0.8.5 -> 0.8.6

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- 7b6ffa5ce9503ea3b1f8d3c365c060807fcec7cc
  Jormungandr 0.8.5 -> 0.8.6

# Comments

### CODE REVIEW

**Comment by piotr-iohk** [comment]
bors try

**Comment by piotr-iohk** [comment]
bors try

**Comment by KtorZ** [comment]
(let's aussi re-generate the genesis file and the arbitrary blocks :+1:)

**Review by KtorZ — APPROVED** [review]
:+1:

**Comment by rvl** [comment]
The integration tests failed when starting jormungandr. It exited with status 12 - trying to listen on 127.0.0.1:8081 for p2p, and the port was already in use. I made a change to the config file for this.

bors try

**Review by rvl — APPROVED** [review]

**Pull request merged**
