### PR TITLE
cardano-addresses: 2.0.0 -> 2.1.0

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

#2197

### Overview

- Updates cardano-addresses to the latest tag.
- Adds cardano-address to the script which reports current program versions.

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]

**Review by piotr-iohk — APPROVED** [review]

**Comment by piotr-iohk** [comment]
It failed to build:

https://buildkite.com/input-output-hk/cardano-wallet/builds/10839#f025ef97-b655-4f4e-bb47-1edc28feff20/3214-3272

```

/build/cardano-wallet/lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs:1082:11: error:
--
  | • Couldn't match type ‘Cardano.Address.Address -> m0 Aeson.Value’
  | with ‘Maybe Aeson.Value’
  | Expected type: ByteString -> Maybe Aeson.Value
  | Actual type: ByteString
  | -> Cardano.Address.Address -> m0 Aeson.Value
  | • Probable cause: ‘(.)’ is applied to too few arguments
  | In the second argument of ‘(.)’, namely
  | ‘inspectShelleyAddress . unsafeMkAddress’
  | In the expression:
  | maybe (Left errMalformedAddress) Right
  | . inspectShelleyAddress . unsafeMkAddress
  | In an equation for ‘inspect’:
  | inspect
  | = maybe (Left errMalformedAddress) Right
  | . inspectShelleyAddress . unsafeMkAddress
  | \|
  | 1082 \|         . inspectShelleyAddress
  | \|           ^^^^^^^^^^^^^^^^^^^^^...
  |  
  | /build/cardano-wallet/lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs:1083:11: error:
  | • Couldn't match type ‘Cardano.Address.Address’ with ‘Maybe XPub’
  | Expected type: ByteString -> Maybe XPub
  | Actual type: ByteString -> Cardano.Address.Address
  | • In the second argument of ‘(.)’, namely ‘unsafeMkAddress’
  | In the second argument of ‘(.)’, namely
  | ‘inspectShelleyAddress . unsafeMkAddress’
  | In the expression:
  | maybe (Left errMalformedAddress) Right
  | . inspectShelleyAddress . unsafeMkAddress
  | \|
  | 1083 \|         . unsafeMkAddress
  | \|           ^^^^^^^^^^^^^^^


```

**Comment by rvl** [comment]
Thanks - I updated the code to fix the tests.

bors r+

**Comment by KtorZ** [comment]
Before merging this, it'd be good to also change the script hash size back to 28 bytes in the wallet too.

**Comment by rvl** [comment]
OK @KtorZ I updated the hash length `swagger.yaml`, but couldn't find any more script address hash length references. The rest would come from the shelley ledger package I think. However the commit messages/comments in cardano-addresses are quite vague about which versions, etc. We also have PR #2212 in progress to update the cardano package versions to 1.21.1.

I also don't know any reason why the SHELLEY_STAKE_POOLS integration tests should consistently fail for this PR.

**Comment by rvl** [comment]
May be lucky today.

bors r+

**Pull request merged**
