### PR TITLE
switch to ProtVer 7 in local test cluster

### PR DESCRIPTION
**Pull request by sadMaxim**
`Builtins.serialiseData` in PlutusTx drops `\"Forbidden builtin function: (builtin serialiseData)\"`. After change `ProtVer to 7` like in this PR it starts to work. Can we update protocol parameters?

### CODE REVIEW

**Review by Anviking — APPROVED** [review]
:+1:

**Comment by Anviking** [comment]
@sadMaxim If you rebase I think I can trigger bors to merge

**Comment by sadMaxim** [comment]
rebased branch on master

**Pull request merged**
