### PR TITLE
[ADP-3072] switch documentation rendering  tool from emanote to mdbook

### PR DESCRIPTION
**Pull request by paolino**
- [x] convert format of docs to mdbook
- [x] fix internal links 
- [x]  fix link to cardano-foundation/cardano-wallet
- [x] not fix external 404 links
- [x]  copy over content from adrestia website links
- [x] copy a pdf from there as well

ADP-3072

### CODE REVIEW

**Review by Unisay — APPROVED** [review]

**Comment by srid** [comment]
Interesting. Is there a particular set of features Emanote could have supported to obviate this change?

**Comment by HeinrichApfelmus** [comment]
> Interesting. Is there a particular set of features Emanote could have supported to obviate this change?

The main reason for switching was actually that I find the default `mdbook` theme to be visually more appealing:

* The theme reserves almost all space for the text (e.g. hides by the navigation bar by default), making the text easier to read.
* The navigation bar is more clear, with section numbers and better scrolling behavior.

That's about it, usability of the executable or configuration did not really factor into the decision. 🤔

**Comment by srid** [comment]
Okay, cool.  So that provides some usefulness to doing https://github.com/srid/emanote/issues/505 especially as another person also asked for it.

**Comment by HeinrichApfelmus** [comment]
> Okay, cool. So that provides some usefulness to doing https://github.com/srid/emanote/issues/505 especially as another person also asked for it.

Absolutely. 👍 To me, the visuals of the generated output are much more important than the method to generate them.

**Pull request merged**
