### PR TITLE
Use mnemonics from cardano addresses

### PR DESCRIPTION
**Pull request by paweljakubas**
# Issue Number

#1601 

# Overview

- [x] I have removed Mnemonic and MnemonicSpec
- [x] I have cleaned AddressDerivation module and decided to leave FromMnemonic only
- [x] I have adjusted all codebase because of this change

# Comments

### CODE REVIEW

**Review by Anviking — APPROVED** [review]

**Review by KtorZ — APPROVED** [review]
:rainbow:

**Comment by paweljakubas** [comment]
the last thing before merging to do is to remove FromMemonic from AddressDerivation and use MkSomeMnemonic from cardano-assdresses - I am on it

**Comment by paweljakubas** [comment]
the filed test : 
```
Failures:

  src/Test/Integration/Scenario/API/Shelley/Wallets.hs:1734:16:
  1) API Specifications, BYRON_WALLETS_RESYNC_01, emptyIcarusWallet - force resync eventually get us back to the same point
       expected: Status {statusCode = 204, statusMessage = "No Content"}
        but got: Status {statusCode = 500, statusMessage = "Internal Server Error"}

       from the following response: Left (DecodeFailure "Something went wrong")

  To rerun use: --match "/API Specifications/BYRON_WALLETS_RESYNC_01/emptyIcarusWallet - force resync eventually get us back to the same point/"
```

**Comment by paweljakubas** [comment]
bors retry

**Comment by paweljakubas** [comment]
the same error as above, but locally I am passing when: 
```
stack test --ta '-m "force resync eventually get us back to the same point"' cardano-wallet-byron:integration
...
    emptyIcarusWallet - force resync eventually get us back to the same point
[cardano-wallet:Notice:29] [2020-04-28 19:14:30.80 UTC] [cardano-node.23226] Terminating child process

Finished in 4.5340 seconds
4 examples, 0 failures

cardano-wallet-byron           > Test suite integration passed
Completed 5 action(s).
```

**Comment by rvl** [comment]
The BYRON_WALLETS_RESYNC_01 test case is pretty flaky. I restarted it a couple times until it succeeded. If the sources don't change, the test result is cached in Hydra.

bors r+

**Comment by rvl** [comment]
There was an interesting result from the integration tests above. I am looking at `cardano-wallet-byron-2020.4.28-test.log` from [build 7193](https://buildkite.com/input-output-hk/cardano-wallet/builds/7193). The network layer received an exception:

    MuxError {errorType = MuxBearerClosed, errorMsg = "<socket: 378> closed when reading data, waiting on next header True

At the time, 110 node clients reported "Connection lost with the node."

Interestingly, cardano-node stays up until the end, but cardano-wallet is unable to communicate with it. The test suite is killed about 4 minutes later, once the 45 minute timeout hits.

It's possible that this is a resource exhaustion failure. Anyway, retrying...

bors r+

**Comment by Anviking** [comment]
> It's possible that this is a resource exhaustion failure. Anyway, retrying...

_In that case_, could be due to #1572 / our infinite error recovery

**Pull request merged**
