### PR TITLE
Bump version from 2020.9.22 to 2020.9.30

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Review by Anviking — APPROVED** [review]

**Comment by hasufell** [comment]
Is `CARDANO_NODE_TAG` and `JORM_TAG` correct?

**Comment by Anviking** [comment]
Yup, there has been no new node bump -> https://github.com/input-output-hk/cardano-wallet/blob/master/nix/sources.json#L3-L8

Same goes for jormungandr. Looks like its version is defined here: https://github.com/input-output-hk/cardano-wallet/blob/master/nix/jormungandr.nix#L41-L47

**Pull request merged**
