### PR TITLE
Jormungandr 0.7.4 -> 0.7.5

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- [ ] Jormungandr 0.7.4 -> 0.7.5 update in `jormungandr.nix`
- [ ] regenerated arbitrary blocks from Jorm v0.7.3-branch

# Comments

### CODE REVIEW

**Comment by piotr-iohk** [comment]
bors try

**Comment by KtorZ** [comment]
*remember to also update the arbitrary block data. That should be done with every new release. That's our gatekeeper for potential binary format changes.

**Comment by piotr-iohk** [comment]
Wouldn't the tests just fail if something is changes with regards to the block format?

**Comment by KtorZ** [comment]
Our tests and in particular, our test genesis block doesn't really cover the whole spectrum of binary objects we may encounter on the real network. Whereas, the arbitrary blocks generated from Jörmungandr cover all fragments and make sure that, at least, our binary decoders can deal with them correctly if encountered.

**Comment by piotr-iohk** [comment]
Gotcha, will update then.

**Review by paweljakubas — APPROVED** [review]

**Review by KtorZ — APPROVED** [review]

**Pull request merged**
