### PR TITLE
add CI using cicero and tullia

### PR DESCRIPTION
**Pull request by dermetfan**

### CODE REVIEW

**Comment by jonathanknowles** [comment]
bors try

**Review by Anviking — APPROVED** [review]
I think [this line in bors.toml](https://github.com/input-output-hk/cardano-wallet/blob/956fa1f62221a789cecb0b6d314411637472875a/bors.toml#L3) would need to be updated to make bors look at cicero instead of hydra. It might make sense to merge this first and do that later though.

**Review by jonathanknowles — APPROVED** [review]

**Comment by jonathanknowles** [comment]
> I think [this line in bors.toml](https://github.com/input-output-hk/cardano-wallet/blob/956fa1f62221a789cecb0b6d314411637472875a/bors.toml#L3) would need to be updated to make bors look at cicero instead of hydra. It might make sense to merge this first and do that later though.

I agree, this seems like a cautious and sensible approach. 👍🏻

**Comment by piotr-iohk** [comment]
@dermetfan can you point us how we can get build binaries from Cicero (ideally for latest master or PR)? We used to use them in e2e tests and they were downloaded from Hydra -> https://github.com/input-output-hk/cardano-wallet/blob/master/test/e2e/helpers/utils.rb#L134-L143.

**Pull request merged**
