### PR TITLE
Integration test for external transaction from Icarus wallet

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

#2041

# Overview

- 4058a8fe1ef02ca42b2b908ea49f773d00244d81
  Integration test for external transaction from Icarus wallet

# Comments

### CODE REVIEW

**Review by paweljakubas — APPROVED** [review]
lgtm!

Worked locally for me
```
$ stack test --ta '-m "TRANS_EXTERNAL_0"' cardano-wallet:integration
API Specifications
  SHELLEY_TRANSACTIONS
[cardano-wallet.integration:Notice:28] [2020-10-06 08:12:22.86 UTC] Configuring cluster in /tmp/test-18a3e15f118e2b0b
[cardano-wallet.integration:Notice:35] [2020-10-06 08:12:24.30 UTC] Transitioning from Byron to Shelley... Please wait 20s...
[cardano-wallet.integration:Notice:35] [2020-10-06 08:12:46.37 UTC] Setting up faucet...
[cardano-wallet.integration:Notice:35] [2020-10-06 08:12:49.87 UTC] 4 stake pools are being registered on chain... Please wait 60s until active... Can be skipped using NO_POOLS=1.
[cardano-wallet.integration:Notice:584] [2020-10-06 08:14:06.49 UTC] http://127.0.0.1:46457/
    TRANS_EXTERNAL_01 - Single Output Transaction - Shelley witnesses
    TRANS_EXTERNAL_02 - Multiple Outputs Transaction - Shelley witnesses
    TRANS_EXTERNAL_03 - Single Output Transaction with Byron witness
      Byron wallet
      Icarus wallet

Finished in 116.9965 seconds
4 examples, 0 failures
```

**Comment by KtorZ** [comment]
bors merge

**Comment by KtorZ** [comment]
(sorry, I merged a concurrent PR manually which would have broken the build here).

**Comment by piotr-iohk** [comment]
bors merge

**Comment by piotr-iohk** [comment]
bors merge

**Pull request merged**
