### PR TITLE
Porting the rest of forget pending tx integration tests to CLI

### PR DESCRIPTION
**Pull request by paweljakubas**
# Issue Number

#836 

# Overview

- [x] I have ported the rest of forgetting pending tx integration tests to CLI

# Comments

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]

**Review by piotr-iohk — APPROVED** [review]

**Review by paweljakubas — COMMENTED** [review]
asserting destination wallet is definitely deterministic here as it was initially empty one

**Pull request merged**
