### PR TITLE
Bump cardano-node dependency to 1.35.0-rc4

### PR DESCRIPTION
**Pull request by sevanspowell**
- [x] Bumped cardano-node dependency to 1.35.0-rc4.
- [x] Updated cardano-wallet code to compile with 1.35.0-rc4.
- [x] Updated balanceTx golden data.
- [x] Fixed updateSealedTx golden data.
   - This is strange, the test reports an error, but there seems to be no difference between the expected and resulting output.
   - Addressed in 6d9635f65bd8a69ea80f0f253ab22fba1d743a10.
   - The CBOR encoding for the `Ledger.Tx` type changed.
   - The `Ledger.Tx` type uses `MemoBytes`. `MemoBytes` uses:
     -  the CBOR encoding of the underlying transaction for comparison (`Eq`).
     -  the `Show` instance of the underlying transaction for printing (`Show`).
   - This means that two transactions can be observably the same, but fail an equality check if the CBOR encoding of the transactions is different.
   - The CBOR encoding of two identical transactions might be different if the CBOR encoding has changed (which is true in this case)
   - I addressed this issue by comparing the equality of `Show` and `Eq`. If there is a discrepancy we presume the CBOR encoding has changed, fail with a helpful error message, and output the new CBOR encoding to a `.rej` file, as we do in other golden tests.
- [x] Updated readme 
- [x] Reverted [b89f351](https://github.com/input-output-hk/cardano-wallet/pull/3349/commits/b89f35100becad79164fe0831065f7e41f89794d) 

### Issue Number

ADP-1908

### CODE REVIEW

**Comment by sevanspowell** [comment]
Is there a discrepancy between `Show` and `Eq` at the ledger level?

**Comment by sevanspowell** [comment]
> Is there a discrepancy between `Show` and `Eq` at the ledger level?

Yeah, there seems to be...

This works:

```
show tx `shouldBe` show tx'
```

This does not:
```
tx `shouldBe` tx'
```

**Comment by sevanspowell** [comment]
Since I suspected cardano-ledger, I managed to bisect this issue to a particular commit:

`3cc007d8b39feecf50cf989e41f0bf5983e3cd76`

The last good cardano-ledger commit was:

`aaca526f8cc0b62c3b36bdd2adb9b3d75b469f03`

**Review by Anviking — APPROVED** [review]
Thanks! 🚀 

Because the "normal form" of alonzo & babbage txs has changed with https://github.com/input-output-hk/cardano-ledger/pull/2863, I suspect we need to update the input binaries to make the failing tests succeed with the intended ledger revision. This can probably be done by manually tweaking them.

Related thread: https://input-output-rnd.slack.com/archives/GBT05825V/p1655206287612259?thread_ts=1654081763.056349&cid=GBT05825V

We should probably be able to enable this now: https://github.com/input-output-hk/cardano-wallet/blob/b89f35100becad79164fe0831065f7e41f89794d/lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs#L1411-L1416

**Comment by paweljakubas** [comment]
@Anviking @sevanspowell  I can produce a PR after this PR is merged into master enabling the `binaryCalculationsSpec` - this will require some more action than just uncommenting - as in both Alonzo and Babbage there is additional field isValid introduced and hence not 3-element array (like in previous eras) but 4-element array. So produced binary is a little bit fatter and we should take that into consideration

**Review by paweljakubas — APPROVED** [review]
nice!

**Comment by sevanspowell** [comment]
bors try

**Comment by sevanspowell** [comment]
bors try

**Pull request merged**
