### PR TITLE
cardano-node: 1.19.0 -> 1.19.1

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

None

### Overview

- Updates cardano-node to [1.19.1](https://github.com/input-output-hk/cardano-node/releases/tag/1.19.1)
- Back to a URL snapshot - hopefully prevents stack snapshot caching issues.
- Completely disable RDRAND in cryptonite using a cabal flag.

### Comments

- Needs input-output-hk/cardano-haskell#26 merged first.

### CODE REVIEW

**Comment by rvl** [comment]
bors try

**Comment by Anviking** [comment]
bors try

**Review by KtorZ — APPROVED** [review]
May you update the matrix in the README before merging :pray: ?

**Comment by rvl** [comment]
Thanks, `README.md` updated now.

bors r+

**Comment by rvl** [comment]
bors try-

**Pull request merged**
