### PR TITLE
Add CI Job That Runs Integration Tests in Previous Era

### PR DESCRIPTION
**Pull request by sevanspowell**
- Adds a CI job to Hydra the runs the integration tests in the previous
era (keeping the integration tests run in the current era).
- So we can test that the wallet still works before the hard-fork to a new era.
- We intend this job to be temporary, it can be removed after we've successfully
navigated the hard-fork.

### Issue Number

ADP-1980

### CODE REVIEW

**Comment by sevanspowell** [comment]
bors try

**Comment by sevanspowell** [comment]
`integration-prev-era` only runs on Linux :heavy_check_mark:

**Review by Anviking — APPROVED** [review]
Thanks - LGTM!

Are you 100% sure the `export LOCAL_CLUSTER_ERA=alonzo` actually makes it all the way to the integration tests? If not might be worth checking that setting it to... say an invalid value makes `clusterEraFromEnv` complain.

**Comment by sevanspowell** [comment]
> Thanks - LGTM!
> 
> Are you 100% sure the `export LOCAL_CLUSTER_ERA=alonzo` actually makes it all the way to the integration tests? If not might be worth checking that setting it to... say an invalid value makes `clusterEraFromEnv` complain.

Yep!

       last 6 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/9kcz93d6zq51rs3jvlrvc2hg7cdz7xj0-cardano-wallet-test-integration-x86_64-unknown-linux-musl-2022.7.1-x86_64-unknown-linux-musl
       > source root is cardano-wallet-test-integration-x86_64-unknown-linux-musl-2022.7.1-x86_64-unknown-linux-musl
       > building
       > Git revision is 0000000000000000000000000000000000000000
       > LOCAL_CLUSTER_ERA: unknown era

**Pull request merged**
