### PR TITLE
Run benchmarks on the dedicated agent.

### PR DESCRIPTION
**Pull request by jbgi**

### CODE REVIEW

**Review by johnalotoski — APPROVED** [review]

**Review by Anviking — APPROVED** [review]

**Comment by Anviking** [comment]
cc @rvl https://github.com/input-output-hk/cardano-wallet/pull/1586/commits/b1c4051a004c363129e3144efdeb591a00d02bad can be dropped

**Comment by jbgi** [comment]
sorry @rvl, missed your commit.

**Comment by rvl** [comment]
Thanks

**Pull request merged**
