### PR TITLE
Disable Jormungandr tests in CI

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- 88bf743cbb47c8f0406df73ae5a179abc75e11be
  Disable Jormungandr tests in CI

# Comments

### CODE REVIEW

**Comment by piotr-iohk** [comment]
hydra failure:
https://hydra.iohk.io/build/4641890/nixlog/1
```
Failures:

  test/unit/Cardano/Wallet/Primitive/FeeSpec.hs:379:9: 
  1) Cardano.Wallet.Primitive.Fee.prop_rebalanceSelection The fee balancing algorithm converges for any coin selection.
       Falsifiable (after 2281 tests):
         SaveMoney
         Coin {getCoin = 31946}
         selection (before):
         inputs:
           - 1st 00f9f187 (~ 163271 @ 61646472...64722d33)
           - 3rd ab297d60 (~ 164465 @ 61646472...64722d33)
           - 2nd e973e54b (~ 165206 @ 61646472...64722d31)
           - 2nd e1a6aa15 (~ 178461 @ 61646472...64722d31)
         withdrawal: 876
         reclaim: 570642
         outputs:
           - 95750 @ 61646472...64722d32
           - 170567 @ 61646472...64722d33
           - 125186 @ 61646472...64722d31
           - 132069 @ 61646472...64722d30
           - 65925 @ 61646472...64722d32
         change: [82782]
         deposit: 381078
         
         selection (after):
         inputs:
           - 1st 00f9f187 (~ 163271 @ 61646472...64722d33)
           - 3rd ab297d60 (~ 164465 @ 61646472...64722d33)
           - 2nd e973e54b (~ 165206 @ 61646472...64722d31)
           - 2nd e1a6aa15 (~ 178461 @ 61646472...64722d31)
         withdrawal: 876
         reclaim: 570642
         outputs:
           - 95750 @ 61646472...64722d32
           - 170567 @ 61646472...64722d33
           - 125186 @ 61646472...64722d31
           - 132069 @ 61646472...64722d30
           - 65925 @ 61646472...64722d32
         change: [31946]
         deposit: 381078
         
         delta (before): 189564
         delta (after):  240400
         total fee:      240400
         remaining fee:  0
         

  To rerun use: --match "/Cardano.Wallet.Primitive.Fee/prop_rebalanceSelection/The fee balancing algorithm converges for any coin selection./"

Randomized with seed 1023422040

Finished in 752.0834 seconds
2315 examples, 1 failure, 6 pending
```

#2215

**Review by rvl — APPROVED** [review]
Does the job - but perhaps it would be easier to fork off the cardano-wallet-jormungandr repo now, then completely remove anything jormungandr from the main cardano-wallet repo.

**Pull request merged**
