### PR TITLE
Few more cases in SQLite specs

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- [ ] I have added few more cases into `SqliteSpec` and `SqliteFileModeSpec`

# Comments

### CODE REVIEW

**Comment by KtorZ** [comment]
@piotr.stachyra, I believe most of those cases are already checked by the statemachine tests, have you checked the labels there?

**Comment by piotr-iohk** [comment]
> I believe most of those cases are already checked by the statemachine tests, have you checked the labels there?

I thought they might, but I haven't wrapped my head around them quite yet :)

**Comment by rvl** [comment]
The high level idea of the state machine tests is that they randomly generate a list of commands. Then these commands are run against the real implementation and model implementation at the same time. At every step, the results are compared and must be the same.

We need to verify:
1. That the model is correct -- the model is supposed to be as simple as possible.
2. The coverage of commands is sufficient -- so we tag generated test cases.

So, model and tags, they are the important parts.

The state machine tests print the coverage of tags. If there's something we think might not be covered then we should add a tag and see.

**Comment by piotr-iohk** [comment]
@rvl - thanks! I chatted with @KtorZ yesterday also. I'm closing this pr as it just partially duplicates the state machine tests.

**Pull request closed without merging**
