### PR TITLE
Use fee estimator instead of hard-coded fee value for stake pools joining

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

#1144

# Overview

- [x] I have removed the hard-coded `stakePoolFee` and used a proper fee estimator which computes expected fee from a transaction description and values from the genesis block.
- [x] I have added some non-null fees for the "coefficient" part of the fee policy, so that inputs/outputs would also cost something.
- [x] I have fixed fee calculation at the boundaries, especially, when the reduction of change outputs modifies the fees. 
- [x] I have fixed the external tx builder to not use hard-coded fees but instead, use fees from the genesis file

# Comments

~~- The behavior and amounts in most tests are currently wrong, I'll fix in another PR.~~ Done.

### CODE REVIEW

**Review by piotr-iohk — APPROVED** [review]
:+1:

**Comment by KtorZ** [comment]
nix _"reliable builds"_ failing again with:

> /var/lib/buildkite-agent/.stack/setup-exe-cache/x86_64-linux-nix/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory

**Comment by KtorZ** [comment]
bors retry

**Pull request merged**
