### PR TITLE
Create Sparse Checkpoint & prune address discovery state

### LINKED ISSUE #769: wallet.db size significantly big
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration v Environment v Human v Unknown |

# Context
`wallet.db` size for the server with transaction between wallets is much bigger comparing to the size of wallet.db with the same wallets that were restored on the fresh node.

I had a script running transactions between 3 wallets back and forth for few hours. in total all 3 wallets had ~6k transactions spanning through 1 epoch (between slots 6k - 20k).
`wallet.db` for that backend server is 2.2GB.

The same wallets restored on fresh node and wallet server make `wallet.db` weight only 213MB.

Both wallets dbs can be accessed [here](https://drive.google.com/drive/folders/1pOVEZ5ePLiVaJEObZ1QvWhXzJoAafbXb).

# Steps to Reproduce

1. Start jormungandr testnet and a wallet server with `--database wallet1.db`

[node_config.yaml.txt](https://github.com/input-output-hk/cardano-wallet/files/3671092/node_config.yaml.txt)

```
jormungandr --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --config node_config.yaml

cardano-wallet-jormungandr serve --genesis-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --database wallet1.db
```

2. Create two wallets and run a [script](https://github.com/piotr-iohk/big-wallet-creator/blob/master/script.rb) `./script test <wid1> <wid2>` for a few hours. (runs transactions between two wallets)
3. Monitor `wallet1.db` size
4. Restore the same wallets using different wallet server and wallet.db file (`--database wallet2.db`).
## Expected behavior

`wallet1.db` and `wallet2.db` sizes shouldn't be significantly different. (The same?)
## Actual behavior
 
`wallet1.db` ~ 2.2GB
`wallet2.db` ~ 200MB

---

# Resolution Plan

- Review `purgeCheckpoints` in SQLite, something is probably off there
- Analyze the 2GB database looking for something bizarre, likely, one table is not getting cleaned up correctly.

# PR

| Number   | Base      |
| ---      | ---       |
| #791       | `master` |
| #786       | `master` |
| #801       | `master` |

# QA 

- Wallet layer now makes sparse checkpoints instead of contiguous ones
- Address discovery state now cleaned up as part of the checkpoint pruning
- Added property to verify that pruning is happening as expected 
- See full analysis on #791 and #786
- In #801, we've also added some measurement in the benchmark tests to get good estimate of the database size with various size of data:

```
File size /1000 CP x 1000 UTxO   
  bench13668-10.db                          166 MB
  bench13668-10.db-shm                       32 KB
  bench13668-10.db-wal                        4 MB
  bench13668-10.db (closed)                 166 MB

File size /10000 w/ 10i + 20o    
  bench24335-2.db                            57 MB
  bench24335-2.db-shm                       128 KB
  bench24335-2.db-wal                        57 MB
  bench24335-2.db (closed)                   57 MB
                                 
File size /100000 w/ 10i + 20o   
  bench24335-3.db                           580 MB
  bench24335-3.db-shm                         1 MB
  bench24335-3.db-wal                       584 MB
  bench24335-3.db (closed)                  580 MB

File size /10000 w/ 50i + 100o   
  bench24335-6.db                           297 MB
  bench24335-6.db-shm                       608 KB
  bench24335-6.db-wal                       299 MB
  bench24335-6.db (closed)                  297 MB
```

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

#769 

# Overview

- [x] I have created sparse checkpoints every `n=97` slots in the unstable epoch during "restoration". This number is arbitrary but has nice properties:
    - Is small enough in front of the epoch stability
    - Is small enough that it's not too long to recover missing blocks from a checkpoint to another
    - Is big enough that is reduces by 2 orders of magnitude the number of checkpoints stored in db

- [x] I have added a property that verifies that checkpoints are purged correctly from database (i.e., there's no checkpoints older than `k` in the database). An example of failure is given below.

- [x] I have made sure to clean-up the address discovery state when clearing old checkpoint. This should effectively fix #769 as the analysis below showed it was (at least one of) the problem.

# Comments

### Property test failure

```
Wallet s t
   Tip: 68617368-[0.0#0]
   Parameters:
        Genesis block hash: 67656e65736973
        Genesis block date: 1970-01-01 00:00:00 UTC
        Fee policy:         14.0x + 42.0
        Slot length:        1s
        Epoch length:       21600
        Tx max size:        8192
        Epoch stability:    2160
   UTxO: []
   RndState:
       Account ix:       2954704361
       Random Generator: 86 2
       Known addresses:  {}
       Change addresses: {}

35333663-[59.20817#439942] ∅
35333663-[59.20818#439943] ∅
35333663-[59.20819#439944] ∅
35333663-[59.20820#439945] ∅
35333663-[59.20821#439946] ∅
35333663-[59.20822#439947] ∅
35333663-[59.20823#439948] ∅
35333663-[59.20824#439949] ∅
35333663-[59.20825#439950] ∅


most recent header (before rollback):
35333663-[59.20825#439950]

k=4

most recent header (after rollback):
35333663-[59.20822#439944]

there's no checkpoint older than k ✗
```

### CODE REVIEW

**Comment by KtorZ** [comment]
bors try

**Comment by Anviking** [comment]
I thought the initial idea was to have really lightweight checkpoints on every unstable slot.

This did not work out? Is it not possible to just cleanup some addresses instead?

**Review by paweljakubas — APPROVED** [review]
It is quite low-space-cost strategy to have stored every 97 checkpoints and maximum last 10 (not going deeper than sparse checkpoint). It should handle shallow rollbacks (1-2 blocks) well as it should affect last 10 checkpoints part. If we experience deep rollback or unfortunate shallow rollback when we are at cp(N*97), then we should go backwards to cp((N-1)*97), and then apply many blocks, and proceed as usual. 

I am thinking if unit tests showing these boundary conditions should not be introduced. So,
**Case 1**. 
```
- cp0
- cp97
- cp194
- cp195
- cp196
``` 
rollback to cp195
**Case2**
rollback to cp190
**Case3** 
a number of rollbacks applied, here maybe we should have property that establishes the number of checkpoints and introduces their accounting. So,
```
- cp0
- cp97
```
*2*
```
- cp0
- cp97
- cp98
```
*3*
```
- cp0
- cp97
- cp100
...
- cp110
```
*12*
etc
and when applying rollback this accounting should stay consistent

Also the test handling inter-epoch rollbacks, checkpoint accounting when epoch changes would be valuable

**Comment by piotr-iohk** [comment]
I'm just trying out this branch on `http-bridge` testnet. Performance improvement is huge! :tada: 

 - https://github.com/input-output-hk/cardano-wallet/issues/769 - not an issue. My wallets, that used to weight 5.4GB on wallet.db have now ~73MB!
- also don't see any trace of https://github.com/input-output-hk/cardano-wallet/issues/756 and https://github.com/input-output-hk/cardano-wallet/issues/760

**Comment by KtorZ** [comment]
> I thought the initial idea was to have really lightweight checkpoints on every unstable slot.

This did not work out? Is it not possible to just cleanup some addresses instead?

@Anviking this PR does actually 2 things sorry, I'll split into 2 PRs. 

One part makes sure to prune the address discovery states with the checkpoints, effectively fixing the enormous DB. 
One other part (will move in another PR) is trying to reduce the number of checkpoints we have to make as it turns out that making a chcekpoint for every unstable slot is quite expensive (in both space and time). Though, I am currently refining this after a discussion with @paweljakubas. I'll move sparse checkpoint creation to the DB layer only (and let the wallet layer store everything in the unstable epoch). Here's the gist

```
-- | Storing EVERY checkpoints in the database is quite expensive and useless.
-- We make the following assumptions:
--
-- - We can't rollback for more than `k=epochStability` blocks in the past
-- - It is pretty fast to re-sync a few hundred blocks
-- - Small rollbacks may occur more often than long one
--
-- So, as we insert checkpoints, we make sure to: 
--
-- - Prune any checkpoint that more than `k` blocks in the past
-- - Keep only one checkpoint every 100 blocks
-- - But still keep ~10 most recent checkpoints to cope with small rollbacks
--
-- __Example 1__: Inserting `cp153`
--
-- ℹ: `cp142` is discarded and `cp153` inserted.
--
-- @
-- Currently in DB:
--┌───┬───┬───┬─  ──┬───┐
--│cp000 │cp100 │cp142 │..    ..│cp152 │
--└───┴───┴───┴─  ──┴───┘
-- Want in DB:
--┌───┬───┬───┬─  ──┬───┐
--│cp000 │cp100 │cp143 │..    ..│cp153 │
--└───┴───┴───┴─  ──┴───┘
-- @
--
--
-- __Example 2__: Inserting `cp111`
--
-- ℹ: `cp100` is kept and `cp111` inserted.
--
-- @
-- Currently in DB:
--┌───┬───┬───┬─  ──┬───┐
--│cp000 │cp100 │cp101 │..    ..│cp110 │
--└───┴───┴───┴─  ──┴───┘
-- Want in DB:
--┌───┬───┬───┬─  ──┬───┐
--│cp000 │cp100 │cp101 │..    ..│cp111 │
--└───┴───┴───┴─  ──┴───┘
-- @
```

**Comment by KtorZ** [comment]
Will open a new PR about sparse checkpoints.
Address pruning now in #791

**Pull request closed without merging**
