### PR TITLE
[ADP-2373] Split `selectTxHistory`

### PR DESCRIPTION
**Pull request by HeinrichApfelmus**
This pull request is a refactoring that splits the `selectTxHistory` function into two parts:

* Selecting and filtering `TxMeta` from the wallet
* Populate TransactionInfo by paring the `TxMeta` with transaction data

This splits will facilitate moving transaction data back to disk.

This pull request is part of the transitional architecture for the introduction of DBVar.

### Issue Number

ADP-2373

### CODE REVIEW

**Review by paolino — APPROVED** [review]
LGTM, thanks

**Comment by paolino** [comment]
CI failed: 

  To rerun use: --match "/Cardano.Wallet.Api.Server.Tls/TLS Client Authentication/Deny client with wrong certificate if TLS is enabled/"

Randomized with seed 1110626759

**Comment by paolino** [comment]
bors try

**Comment by HeinrichApfelmus** [comment]
bors merge

**Pull request merged**
