### PR TITLE
stack.yaml: Add flags to reduce iohk-monitoring dependencies

### PR DESCRIPTION
**Pull request by rvl**
Relates to issue #350.

~~:warning: DO NOT MERGE YET (see https://github.com/input-output-hk/cardano-wallet/pull/443#issuecomment-503919689) :warning:~~

# Overview

- This will prune dependencies that we don't currently use.

# Comments

- We can bump the iohk-monitoring revision once input-output-hk/iohk-monitoring-framework#356 is merged.

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]
LGTM.

We would have to re-generate the cache for this to take effect. Will do on "dead" hours.

**Comment by rvl** [comment]
OK, could we wait for the above PR to be merged, then update to the latest rev of iohk-monitoring-framework? That will give us maximum pruning.

**Comment by KtorZ** [comment]
Sounds reasonable to me :)

**Comment by KtorZ** [comment]
@rvl The PR above (https://github.com/input-output-hk/iohk-monitoring-framework/pull/356) has been merged so I've updated the commit revision to point to the latest master. Waiting for travis and merging :+1:

**Pull request merged**
