### PR TITLE
Update to jorm 0.8.18

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

I figured I'll update...

# Overview

- 5100dbd5c795f4f0106ff3195f2926f51e40a85d
  Bump jormungandr.nix
  
- ab1ac1b49ff7551722c859e7fdb7c368403fd412
  arbitrary blocks

# Comments

There are two cases failing, I don't quite understand yet why... cannot reproduce locally:

```
Failures:

  test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs:506:17: 
  1) API Specifications, STAKE_POOLS_JOIN/QUIT_02 - Passphrase must have appropriate length, Join: passphrase is too short: expected at least 10 characters
       expected: Status {statusCode = 400, statusMessage = "Bad Request"}
        but got: Status {statusCode = 403, statusMessage = "Forbidden"}
       
       from the following response: Left (DecodeFailure "Error in $: parsing Cardano.Wallet.Api.Types.ApiTransaction(ApiTransaction) failed, key \"id\" not found: Response {responseStatus = Status {statusCode = 403, statusMessage = \"Forbidden\"}, responseVersion = HTTP/1.1, responseHeaders = [(\"Transfer-Encoding\",\"chunked\"),(\"Date\",\"Wed, 22 Apr 2020 15:08:08 GMT\"),(\"Server\",\"Warp/3.3.5\")], responseBody = \"{\\\"code\\\":\\\"cannot_cover_fee\\\",\\\"message\\\":\\\"I'm unable to select enough coins to pay for a delegation certificate. I need: 56 Lovelace.\\\"}\", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}")

  To rerun use: --match "/API Specifications/STAKE_POOLS_JOIN/QUIT_02 - Passphrase must have appropriate length/Join: passphrase is too short: expected at least 10 characters/"

  test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs:506:17: 
  2) API Specifications, STAKE_POOLS_JOIN/QUIT_02 - Passphrase must have appropriate length, Quit: passphrase is too short: expected at least 10 characters
       expected: Status {statusCode = 400, statusMessage = "Bad Request"}
        but got: Status {statusCode = 403, statusMessage = "Forbidden"}
       
       from the following response: Left (DecodeFailure "Error in $: parsing Cardano.Wallet.Api.Types.ApiTransaction(ApiTransaction) failed, key \"id\" not found: Response {responseStatus = Status {statusCode = 403, statusMessage = \"Forbidden\"}, responseVersion = HTTP/1.1, responseHeaders = [(\"Transfer-Encoding\",\"chunked\"),(\"Date\",\"Wed, 22 Apr 2020 15:08:08 GMT\"),(\"Server\",\"Warp/3.3.5\")], responseBody = \"{\\\"code\\\":\\\"not_delegating_to\\\",\\\"message\\\":\\\"It seems that you're trying to retire from delegation although you're not even delegating, nor won't be in an immediate future.\\\"}\", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}")
```

### CODE REVIEW

**Comment by rvl** [comment]
Those two failures seem related somehow to the recent changes in passphrase validation. This was to allow importing wallets from the previous codebase which did not have a password set.

**Comment by piotr-iohk** [comment]
>Those two failures seem related somehow to the recent changes in passphrase validation. This was to allow importing wallets from the previous codebase which did not have a password set.

Indeed. I have updated the stake pool tests. Hopefully all tests should be passing now.

**Review by rvl — APPROVED** [review]

**Comment by piotr-iohk** [comment]
bors try

**Review by paweljakubas — APPROVED** [review]
LGTM

**Pull request merged**
