### PR TITLE
Bump to Jormungandr 0.8.11

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- 77da64d5f04e0f963bfbceb5128fac722ff12b79
  Update arbitrary blocks with Jorm 0.8.11
  
- b82a6557b5bca1c7c82a9ef02d6067baf893b8a9
  update README compat
  
- 743d4664f4b05601f6536d3c5751339531137614
  Update config.yaml
  
- 6b98777f745c3db6bdbaecc504b4eb92a9a9a0fb
  nix/jormungandr: set correct default value for commonLib
  
- a457926f47095254e67b13affd92806c05ea876a
  Bump jormungandr.nix to 0.8.11

# Comments
~:warning: currently stuck at -> https://input-output-rnd.slack.com/archives/C819S481Y/p1582280809070500~

### CODE REVIEW

**Comment by KtorZ** [comment]
bors try

**Comment by KtorZ** [comment]
bors try

**Comment by KtorZ** [comment]
bors try

**Comment by piotr-iohk** [comment]
bors try

**Pull request merged**
