### PR TITLE
Update tests / pending test against ADP-1738

### PR DESCRIPTION
**Pull request by piotr-iohk**
- 58dbe4a7a7132668e9193f188177ed5b1bf98a7b
  Adjust e2e tests after API changes from #3249
  
- 71969cb5c9de1cad0a49a6c96025b79768b2f910
  Pending integration tests against ADP-1738

### Comments
Pending integration test `TRANS_NEW_CREATE_MINT_SCRIPTS` for ADP-1738
Screenshot from 2022-05-06 13-17-16

### Issue Number

ADP-1738, ADP-1193

### CODE REVIEW

**Review by HeinrichApfelmus — APPROVED** [review]
LGTM! 😊 

I was wondering whether `runResourceT` should be called only once in first line (starting with `describe` …) rather be called again and again for each scenario, but I believe that the latter approach is perfectly fine.

**Comment by piotr-iohk** [comment]
bors merge

**Comment by piotr-iohk** [comment]
bors merge

**Pull request merged**
