### PR TITLE
Remove local copy of `bech32` library.

### PR DESCRIPTION
**Pull request by jonathanknowles**
# Issue Number

#1333 

# Overview

This PR:

- [x] Removes our local copy of the `bech32` library.
- [x] Specifies [version `1.0.1` of the library from Hackage](https://hackage.haskell.org/package/bech32-1.0.1) as an extra dependency within `stack.yaml`.
- [x] Updates all the relevant `nix` machinery.

### CODE REVIEW

**Comment by KtorZ** [comment]
@jonathanknowles we should also update the `stack.yaml` file to use the "remote" bech32 as an external dep instead of a local package. For this one at least, I think it makes sense to treat it as an external lib. What do you think?

Pros:

- We don't have to rebuild it all the time
- Tests will be executed on a different CI for the bech32 package

Cons:

- Can be counter-intuitive if we make modifications to the submodule without changing the reference in the stack.yaml and expect them to show up straight away in the rest of the code.

**Comment by jonathanknowles** [comment]
> @jonathanknowles we should also update the `stack.yaml` file to use the "remote" bech32 as an external dep instead of a local package. For this one at least, I think it makes sense to treat it as an external lib. What do you think?

I'd definitely be happy with adding it as an  `extra-dep` within `stack.yaml`.

If we do that though, should we remove the git submodule, to keep things simple?

(If later on we need to start working intensively with the `bech32` code base later in such a way that it requires iteration within  `cardano-wallet`, then perhaps it will be worthwhile adding a submodule back in again.)

I was going to suggest just relying on `stackage` to select the latest version for us, but `bech32` still isn't included in any LTS versions. (Though it is starting to appear in the [nightly builds](https://www.stackage.org/package/bech32/snapshots), starting from the end of last week.)

So we could add an entry in `extra-deps` for now, and then remove it later on after `stackage` includes it in an LTS version.

What do you think?

**Comment by jonathanknowles** [comment]
@KtorZ 

I've updated the PR so that it:

- [x] Specifies [version `1.0.1` of the library from Hackage](https://hackage.haskell.org/package/bech32-1.0.1) as an extra dependency within `stack.yaml`.
- [x] Updates all the relevant `nix` machinery.

I've **removed** the `git` submodule for now. If we need it later on, we can add it back in again.

**Review by KtorZ — APPROVED** [review]

**Pull request merged**
