### PR TITLE
Fix silly mistake in latency benchmark setup

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

Resolves ADP-638.

### Overview

It was trying to create the wallets directory twice.

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]

**Comment by KtorZ** [comment]
bors merge

**Comment by KtorZ** [comment]
bors retry

**Comment by KtorZ** [comment]
bors retry

**Review by piotr-iohk — APPROVED** [review]
LGTM. Works on my computer.

**Pull request merged**
