### PR TITLE
expose foreign keys control switch

### PR DESCRIPTION
**Pull request by paolino**
- [x] I have exposed the switch to control foreign keys check so that stores that have cross dependencies can be tested in separation
- [x] I have removed old code that I had already factored up to be shared among all `StoreSpec` modules

### Issue Number

ADP-1983

### CODE REVIEW

**Review by HeinrichApfelmus — APPROVED** [review]
Looks good to me, thanks! 😊 As the base branch `paolino/ADP-1955/substitute-dblayer-transactions-history` is still in flux — is there a chance to rebase this on master so that we can merge it before the base branch? (Without picking up the unrelated changes in `Layer`).

**Comment by paolino** [comment]
bors try

**Comment by paolino** [comment]
> Looks good to me, thanks! blush As the base branch `paolino/ADP-1955/substitute-dblayer-transactions-history` is still in flux — is there a chance to rebase this on master so that we can merge it before the base branch? (Without picking up the unrelated changes in `Layer`).

done

**Pull request merged**
