### PR TITLE
[ADP-1963] publish mint and burn data in ApiTransaction from stored cbor

### PR DESCRIPTION
**Pull request by paolino**
I have added mint and burn fields to get /transaction and get /transactions by parsing the CBOR from the transaction history

### Issue Number

ADP-1963

### CODE REVIEW

**Review by piotr-iohk — APPROVED** [review]
recreated from https://github.com/input-output-hk/cardano-wallet/pull/3514

**Comment by paolino** [comment]
bors try

**Comment by paolino** [comment]
bors retry

**Review by HeinrichApfelmus — APPROVED** [review]
Still looks good to me! 😊

**Pull request merged**
