### PR TITLE
Add shell completions

### PR DESCRIPTION
**Pull request by hasufell**
This is created via optpars-applicative, see:
  https://github.com/pcapriotti/optparse-applicative/wiki/Bash-Completion

### CODE REVIEW

**Comment by KtorZ** [comment]
This is already mentioned in our user guide: https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface

Also, I'd rather give the command to generate the auto-completion scripts than the scripts themselves, don't you think ?

**Comment by hasufell** [comment]
> This is already mentioned in our user guide: https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface

That's only for bash afais.

> Also, I'd rather give the command to generate the auto-completion scripts than the scripts themselves, don't you think ?

I think either is fine. I don't have a strong opinion, but it seems the upstream doc suggests to ship the output:
https://github.com/pcapriotti/optparse-applicative/wiki/Bash-Completion#introduction

> Normally, the output of --bash-completion-script should be shipped with the program and copied to the appropriate directory (usually /etc/bash_completion.d/) during installation.

**Review by Anviking — APPROVED** [review]
Personally, I think this makes more sense than having it in the wiki. Nice to have zsh + fish too! 🙏

**Comment by rvl** [comment]
We should generate the completion scripts for all shells for all programs when building the [release archives](https://github.com/input-output-hk/cardano-wallet/releases). This could be done with nix or travis - choose your poison.

That will be more helpful to users than having these scripts in either the git repo or the wiki.

**Comment by hasufell** [comment]
@rvl are you gonna take a shot at that? I'm not familiar with either of those.

**Comment by rvl** [comment]
I can coach you if you have time. Travis is just glorified shell scripts embedded in YAML. Nix is just shell scripts embedded in an obscure functional language - start looking in [`nix/linux-release.nix`](https://github.com/input-output-hk/cardano-wallet/blob/master/nix/linux-release.nix#L32).

**Review by KtorZ — APPROVED** [review]
Discussed in DMs with @hasufell on Slack. Approving my own changes on his behalf.

**Comment by KtorZ** [comment]
bors merge

**Comment by rvl** [comment]
Try the integration tests again...

bors r+

**Pull request merged**
