### PR TITLE
DBSpec: More testing of saving UTxO

### PR DESCRIPTION
**Pull request by rvl**
Relates to #643 

# Overview

With rollback, we want to ensure that checkpoints are correctly rolled back, and the utxo is included in that. So we need to make sure the database tests are generating utxo data in checkpoints.

- This adds random utxo to the checkpoint wallets used in the database property tests and QSM tests.
- The existing property `prop_sequentialPut putCheckpoint` will cover inserting many checkpoints.

# Comments

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]
LGTM

**Comment by KtorZ** [comment]
~~Interestingly enough, the state-machine tests are failing but only for the Sequential State, regardless of whether the last commit is included or not (which is the one containing a change in the SeqState after all...).~~ This is simply because the PR doesn't change the generator for `instance Arbitrary (Wallet (RndState DummyTarget) DummyTarget)` which still generates empty checkpoints!

**edit:** 

Okay, so the way SQLite now works may require more complexe generators for the checkpoints... We use to say something like: `read . put cp == cp`. Which doesn't hold for any arbitrary checkpoints anymore. `putCheckpoint` doesn't `put` actually, it `appends`. New UTxOs from a checkpoint are added to the database, and existing ones are left untouched. 
Then, we "soft-delete" some them by marking every UTxO in a tx input. 

So, what we get from `readCheckpoint` doesn't solely depend on what was given to `putCheckpoint` before. If some UTxOs already existed in the DB, they'll be selected by `readCheckpoint` and boom, discrepancy in the state-machine and db `readAfterPut` property (because we do `createWallet` with a non empty checkpoint!). 

I think the problem here is that our database has some "notions" of what the business logic is and therefore, doesn't simply put checkpoints we tell it in a dumb way, it does some complex merging to avoid storing multiple times the same UTxO row. 

I need to think about this a bit. Not sure what's the best approach here. It's kinda sad that we can't just read . put anymore, but maybe it's a necessary evil.

**Comment by KtorZ** [comment]
**Idea**

Instead of marking every UTxO corresponding to a spent input (which is where the business logic gets mixed in), make a diff with the previous checkpoint and mark all missing UTxO as spent.
This would effectively create checkpoints without any notion of what "spent" means. I think This could be done "easily" by doing it backward:

When inserting a new checkpoint,

1. Mark all existing UTxOs with spent=null as spent at the current slot (simple UPDATE statement) 
2. Put all new UTxOs, with spent=null (simple batch INSERT) 
3. Mark as spent=null every UTxO that exists twice. Or said differently, undo 1. but only for the duplicates (should be doable with an UPDATE and an aggregation similar to what's in 4.)
4. Remove all duplicate UTxO and keep the oldest ones (query is already there, DELETE with aggregation) 


**(edit)**: 
see https://www.db-fiddle.com/f/cTTg5Koc4hDfnoVMd7rPUS/7 and 0c35de0daecd8fe6ad378de064e8f3b196db457e

All Sqlite tests now pass :tada:

**Comment by KtorZ** [comment]
bors try

**Comment by KtorZ** [comment]
There's one gotcha though... If we insert checkpoints in an arbitrary order, then it screws everything :grimacing: .. This is something that shouldn't happen in practice, because we only insert checkpoints by ascending slot id, and we rollback otherwise to a previous point. 

Yet, the testing becomes trickier. At the moment, the `Arbitrary` instance for blockheader currently is always: 

```hs
    pure $ BlockHeader (SlotId 0 0) (Hash "hash")
``` 

which is kinda unsatisfactory, but for both the state-machine tests and the db properties, we can't simply rely on `BlockHeader <$> arbitrary <*> arbitrary` as it will create headers in a very arbitrary order (as it should). 

Adding an invariant to `putCheckpoint` would be a good idea too I think, to make sure that we don't by accident call it for a wrong checkpoint which would screw the db consistency.

**Comment by rvl** [comment]
Should I work on making the arbitrary UTxO more "realistic"? E.g. UTxO changed by applying transactions. It may be a non-small chunk of work though.

It's just that by generating random junk data for tests I have made things difficult for us. Because we need to get the tests to pass with data that is impossible on a valid chain.

---

Creating a UTxO diff is a good idea, rather than re-implementing part of the `updateUTxO` logic in the DBLayer.

I do like what you have done with subqueries as raw SQL queries. Maybe we will be using more raw queries in future because the Persistent query functions are limited to basic operations, and sometimes run different SQL than what I had expected.

**Comment by rvl** [comment]
I was looking at the db benchmarks and actually the cost of saving the entire utxo per checkpoint doesn't seem too great, and it's definitely simpler. I don't think we wouldn't even need to bother with sparse checkpoints.

So I have pushed that change here.

If we need to optimise, I would like to make a rollback-aware `applyBlocks` which returns the new checkpoint, and the difference in state (i.e. new txs, utxo added, utxo removed). It's easy to write and test a `putCheckpoint` that just applies differences.

**Comment by KtorZ** [comment]
> I was looking at the db benchmarks and actually the cost of saving the entire utxo per checkpoint doesn't seem too great, and it's definitely simpler. I don't think we wouldn't even need to bother with sparse checkpoints.

In a sense, we were already storing the entire UTxO for every checkpoint (and removing the duplicates right after). My worries was more about the size it'd take to have duplicate rows in the database, especially for exchanges.

Having said that, I agree with you, let's go for what seems easiest now, and see later if we can optimize a bit. The sparse checkpoints would probably be a first direction to go. 

Thanks for checking this!

**Pull request merged**
