### PR TITLE
Jormungandr 0.3.9999 > 0.5.0

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- [ ] Jormungandr 0.3.9999 > 0.5.0

# Comments

There's another release. Apparently there's breaking change so regenerated genesis block.
Integration tests fail though. It seems that all tx are in `pending` state on the node:

```
---
- fragment_id: 628fd59e245983e97d6fa30256576beae3cf09c4409686e8204bf81b6c8de558
  last_updated_at: "2019-09-23T21:27:55.236096002+00:00"
  received_at: "2019-09-23T21:27:55.236095959+00:00"
  received_from: Rest
  status: Pending
```

### CODE REVIEW

**Comment by piotr-iohk** [comment]
bors try

**Review by rvl — APPROVED** [review]
Approved pending tests passing again.

**Comment by piotr-iohk** [comment]
bors try

**Comment by piotr-iohk** [comment]
bors try

**Comment by piotr-iohk** [comment]
It wasn't creating blocks, because I haven't updated `secret.yaml` before. (hence `pending` transactions)

**Review by paweljakubas — APPROVED** [review]
lgtm

**Pull request merged**
