### PR TITLE
cardano-node: 1.24.1 -> 1.24.2

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

None

### Overview

Updates cardano-node to latest [1.24.2 tag](https://github.com/input-output-hk/cardano-node/releases/tag/1.24.2).

### Comments

I pushed the cardano-haskell snapshot update straight to master branch because it is a pretty small diff for this release.

### CODE REVIEW

**Review by jonathanknowles — APPROVED** [review]

**Comment by rvl** [comment]
I also changed the Buildkite cabal version from 3.0 to 3.2.0.0 (to support a `cabal.project` change) ~and stack version from 1.9.3 to 2.3.3 (just because)~.

The cabal configure step now works, but let's see if the stack build still works... (if it doesn't work, then we can revert)... edit: reverted.

**Comment by KtorZ** [comment]
bors merge

**Comment by KtorZ** [comment]
bors retry

**Pull request merged**
