### PR TITLE
Rollback in network layer

### PR DESCRIPTION
**Pull request by rvl**
Relates to #648.

# Overview

This changes `nextBlocks` to be able to return a "roll back" response.

It calculates the intersection of the local chain with the node chain.

I realised that there needs to be per-wallet state in order to calculate intersection. So that is the `Cursor` which gets passed between `nextBlocks` calls.

There are unit tests for the `greatestCommonBlockHeader` function.

The unit tests of node rollback use a randomly generated mock jormungandr node.

`WalletLayer` does not handle `RollBackward` yet (#650).

I needed to add back the `target` type parameter to `NetworkLayer`.

# Comments

- Rollback only fully implemented in cardano-wallet-jormungandr. Http-bridge goes forward only.
- No integration tests yet (does someone have a good way of making jormungandr switch chains?).

### CODE REVIEW

**Comment by KtorZ** [comment]
> does someone have a good way of making jormungandr switch chains?

I've asked the question to the rust guys and no, there's no simple ways. To create forks, we would need to keep two nodes running separately for a while, and, after some point, connect them together. Also, since several nodes might be elected for the same slot in Praos, we could _hope for_ small forks by running a small cluster with many many pools... but that's somewhat unreliable.

**Comment by rvl** [comment]
Yeah I thought so. Maybe we could delete/add rows from its sqlite db, but that wouldn't make a very nice test. I am implementing a mock node that simulates rollbacks, etc.

**Review by KtorZ — APPROVED** [review]
Okay, managed to review and rebase this PR and, updated it with our recent additions and modifications in the network layer. 
The chain following and `Cursor` are very nice now, love it. 

I've made some clean-up in the `Jormungandr.Network` module; in particular, I've extracted the Jormungandr API Client into its own module, as well as helper functions related to its module. 

Also did some renaming here and there and, left a few comments "FIXME" or "TODO" during my review. I have ideas on how to tackle some or them, but I'll issue an other PR for that.

**Comment by rvl** [comment]
@KtorZ thanks for the review and improvements; they look good to me.

**Comment by KtorZ** [comment]
bors try

**Comment by rvl** [comment]
bors r+

Integration tests running locally still haven't finished but I think they will succeed.

**Pull request merged**
