### PR TITLE
Better response example in api doc for network/clock

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- 62128be5b54998fdc014f82d2fc606cc3fb10411
  Better response example in api doc for network/clock
  
- e632629f8a5f3818d4b49689482603185b88f596
  Fix for failng validateEveryToJSON test: "Cardano.Wallet.Api.Types, verify that every type used with JSON content type in a servant API has compatible ToJSON and ToSchema instances using validateToJSON., ApiNetworkClock"

# Comments

| Before | After  |
|--|--|
|Screenshot from 2020-03-13 13-13-39 | Screenshot from 2020-03-13 13-13-57|

### CODE REVIEW

**Review by paweljakubas — APPROVED** [review]
:+1:

**Comment by paweljakubas** [comment]
hmm wonder if the changes you adopted will not induce errors in `Cardano.Wallet.Api.Types` :thinking:  probably (swagger vs Types.Api we have)

**Comment by piotr-iohk** [comment]
I think this should fix this -> e632629f8a5f3818d4b49689482603185b88f596.
Nice tests btw. I suppose they are running against the "active examples" in swagger only, so after changed the example it failed. (because the `minimum` was there before)

**Comment by piotr-iohk** [comment]
bors try

**Comment by piotr-iohk** [comment]
Timed out... :(

bors r+

**Pull request merged**
