### PR TITLE
Jormungandr 0.6.0 in CI

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- [ ] Jormungandr ~0.5.6~ ~0.6.0-rc1~ 0.6.0 in CI

# Comments

### CODE REVIEW

**Comment by piotr-iohk** [comment]
There is one test failing for me locally for 0.5.6:
```
  test/integration/Cardano/Wallet/Jormungandr/NetworkSpec.hs:157:9: 
  1) No backend required, Cardano.Wallet.NetworkSpec, Happy Paths, returns an error when the block header is unknown
       uncaught exception: ErrUnexpectedNetworkFailure
       ErrUnexpectedNetworkFailure (Link {_segments = ["v0","block","d4f3e6dbff0d32969914166b5bc463a1452e1346b296f45fb2e4e8403e4a0e86","next_id"], _queryParams = [SingleParam "count" "10000"]}) (FailureResponse (Response {responseStatusCode = Status {statusCode = 404, statusMessage = "Not Found"}, responseHeaders = fromList [("content-length","0"),("date","Thu, 10 Oct 2019 10:03:14 GMT")], responseHttpVersion = HTTP/1.1, responseBody = ""}))
```

**Comment by rvl** [comment]
Fix for the Buildkite failure coming soon:
* input-output-hk/haskell.nix#263
* input-output-hk/iohk-nix#196

**Review by rvl — APPROVED** [review]
bors r+

**Comment by rvl** [comment]
See #821 for an attempted fix for the CLI integration tests build failure.

**Comment by rvl** [comment]
bors r+

(Some tests are flaky.)

**Pull request merged**
