### PR TITLE
Fix link to list stake keys in swagger

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- 6e5bab93ac9fe161216489e3c2235caf3dad6f36
  Fix link to list stake keys in swagger

# Comments

### CODE REVIEW

**Review by Anviking — APPROVED** [review]
Ah, thanks

**Comment by Anviking** [comment]
Looking now, maybe "list stake keys" should be in the "Shelley wallets" section? 🤔 

Instead of here

Skärmavbild 2021-06-02 kl  11 17 51

**Comment by piotr-iohk** [comment]
> Looking now, maybe "list stake keys" should be in the "Shelley wallets" section?

Could be... I kind of like it in Stake Pools cause it is related to delegation in the end. Similarly delegation fees could be also in the "Shelley wallets" section... Perhaps in future it'll deserve a separate section, like Multi-delegation when more eps arrive.

**Pull request merged**
