### PR TITLE
List Pools uses Bech32-encoded ids.

### PR DESCRIPTION
**Pull request by Unisay**
`GET /v2/stake-pools` returns bech32-encoded pool ids.

### Issue Number

ADP-2252

### CODE REVIEW

**Comment by piotr-iohk** [comment]
List stake pools are shown again in bech32 format. However the fix does not address the pool metadata fetching issue.

To reproduce on 'preview' by hand (the case with 'direct' fetching):
 - have preview synced with node and wallet
 - set 'direct' metadata fetch for pools:
```
curl -X PUT http://localhost:8090/v2/settings \
-d '{"settings":{"pool_metadata_source":"direct"}}' \
-H "Content-Type: application/json"
```
 - list pools:
```
curl -X GET http://localhost:8090/v2/stake-pools?stake=1000000000
```
see there is "metadata": null, for every pool despite there should be some.
In the log there is:
```
[cardano-wallet.pools-engine:Warning:1510] [2022-10-19 17:13:10.44 UTC] Failed to fetch metadata with hash 6074e009: Metadata server(s) didn't reply in a timely manner.
[cardano-wallet.pools-engine:Info:1511] [2022-10-19 17:13:10.44 UTC] Fetching metadata with hash 028d6627 from https://stakeside.xyz/poolmeta.json
[cardano-wallet.pools-engine:Warning:1511] [2022-10-19 17:13:10.44 UTC] Couldn't reach server at .
```
But if we follow https://stakeside.xyz/poolmeta.json the metadata is there.

**Comment by piotr-iohk** [comment]
Checking locally it seems OK. 
 - `direct` option works fine on `preview` and metadata is fetched from the chain.
 - on `mainnet` it also works with both `direct` and from the SMASH server.

Once Hydra builds the latest changes I's also like to run full e2e suite against the branch.

**Comment by Unisay** [comment]
bors try

**Review by piotr-iohk — APPROVED** [review]
I've triggered e2e tests against PR and they passed:
 - [Linux](https://github.com/input-output-hk/cardano-wallet/actions/runs/3319291704) :heavy_check_mark: 
 - [MacOS](https://github.com/input-output-hk/cardano-wallet/actions/runs/3318719216) :heavy_check_mark:
 - [Windows](https://github.com/input-output-hk/cardano-wallet/actions/runs/3319292503) :heavy_check_mark:

**Pull request merged**
