### PR TITLE
cardano-node: pioneer-3 -> 1.12.0

### PR DESCRIPTION
**Pull request by rvl**
### Overview

Updates to [cardano-node-1.12.0](https://github.com/input-output-hk/cardano-node/releases/tag/1.12.0).

### Comments

WIP

- [x] Builds successfully
- [ ] Test data regenerated
- [x] All tests pass

### CODE REVIEW

**Comment by Anviking** [comment]
It passed!
_squashed all the commits_
bors r+

**Review by Anviking — APPROVED** [review]

**Comment by rvl** [comment]
Changed cardano-haskell branch to master...

bors r+

**Comment by rvl** [comment]
Going to merge without bors pending #1688.

**Pull request merged**
