### PR TITLE
Can run Windows integration tests under Wine

### PR DESCRIPTION
**Pull request by rvl**
Relates to #703.

# Overview

- [ ] It's possible to execute `cardano-wallet-jormungandr:test:integration` under Wine.

# Comments

The tests run on Windows but there is something weird going on with Wine.

2019-11-12-14-30-53-wine-integration-tests

To build and run the tests under wine, use:
```
wine $(nix-build release.nix -A x86_64-pc-mingw32.tests.cardano-wallet-jormungandr.integration.x86_64-linux -o integration-windows)/cardano-wallet-jormungandr-2019.11.7/integration.exe
```

### CODE REVIEW

**Comment by angerman** [comment]
After boiling down the example to a tiny C program, and ending up enquiring on the wine-devel mailign list, we end up with: piping the wine call through `cat` and it work. For reference: the wine-devel thread: https://www.winehq.org/pipermail/wine-devel/2019-November/154508.html

**Comment by KtorZ** [comment]
My fix apparently did nothing: 

```
  test/integration/Cardano/Wallet/Jormungandr/NetworkSpec.hs:143:9: 
  1) No backend required, Cardano.Wallet.NetworkSpec, Happy Paths, get network tip
       uncaught exception: IOException of type OtherError
       Network.Socket.connect: <socket: 120>: failed (Connection refused (WSAECONNREFUSED))

  To rerun use: --match "/No backend required/Cardano.Wallet.NetworkSpec/Happy Paths/get network tip/"
```

... Perhaps it's not in the servant client, but, elsewhere when the network manager is created.

**Comment by KtorZ** [comment]
Haha! Seems like I found it (see my latest commit). At least, I am not getting any connection error and it seems that Jörmungandr is starting. However, I am running into some weird issues now which seems to be attributed to Jörmungandr inside wine :thinking: ... 

Screenshot from 2019-11-13 20-24-27

Screenshot from 2019-11-13 20-26-48

**Comment by rvl** [comment]
Can we review and merge this now, so that we have the isPortOpen bug fix in master?
I have removed the testing code, etc.

**Review by KtorZ — APPROVED** [review]
bors r+

**Comment by rvl** [comment]
Oops, I accidentally forced push over a fix.

bors r+

**Pull request merged**
