### PR TITLE
[ADP-3005] Merge `Store` and `QueryStore`

### PR DESCRIPTION
**Pull request by HeinrichApfelmus**
### Overview

This pull requests merges the `QueryStore` type with the `Store` type and updates the documentation.

The type synonym `UpdateStore` takes the role of the previous `Store` type.

### Comments

Future pull requests should:

* Move the contents of `*.Layer` modules (which have implemented `QueryStore`) into the `*.Model` modules (→ `Query` instance) and `*.Store` modules (→ `queryS` implementation).
* Add the properties explained in the documentation to the `Test.Store` module.

### Issue number

ADP-3005

### CODE REVIEW

**Review by paolino — APPROVED** [review]
Great move, thanks

**Comment by HeinrichApfelmus** [comment]
bors merge

**Comment by HeinrichApfelmus** [comment]
bors merge

**Comment by HeinrichApfelmus** [comment]
Integration tests pass on branch.

bors retry

**Pull request merged**
