### PR TITLE
Ensure faucet setup runs on BFT node without rollbacks

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

ADP-970, #2720, #2428

# Overview

- [x] Ensure faucet setup runs on BFT node, such that rollbacks can't mess it up

# Comments

### CODE REVIEW

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
Hydra failed with
```
     PATCH /wallets/0000000000000000000000000000000000000000/signatures/utxo_external/0H
     DELETE /wallets/0000000000000000000000000000000000000000/signatures/utxo_external/0H
     CONNECT /wallets/0000000000000000000000000000000000000000/signatures/utxo_external/0H
building of '/nix/store/mmrl1n9p85h3r0r3vqvjwyj4lhiys9h5-cardano-wallet-core-test-unit-2021.6.11-check' timed out after 900 seconds of silence
```

**Comment by rvl** [comment]
> :flushed: New location.

I believe this means that you owe me 5 kr. :stuck_out_tongue_closed_eyes:

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
> I believe this means that you owe me 5 kr.

Still worthwhile experiment, plus in that failure, we saw it pass the Sqlite properties and state machine tests.

**Review by rvl — APPROVED** [review]
Good idea :+1:
It's good we have Instafork now so that the BFT node is already in the target era at startup.

**Pull request merged**
