### PR TITLE
Use Cabal common stanzas and internal library

### PR DESCRIPTION
**Pull request by rvl**
## Overview

These Cabal 2.0/2.2 features remove duplication in the cabal file.

- [Internal libraries](https://www.haskell.org/cabal/users-guide/developing-packages.html#sublibs)
- [Common stanzas](https://www.haskell.org/cabal/users-guide/developing-packages.html#common-stanzas)

## QA

Ensure that the project still builds.

    stack build --test

### CODE REVIEW

**Comment by KtorZ** [comment]
Wow. Sweet stuff :tada: 

Neat-picking a bit but, I'd suggest a different name than `base` which is rather confusing with the hackage's `base` package in this context.

**Comment by rvl** [comment]
OK I have changed it from `base` → `cardano-wallet-common`.

**Review by KtorZ — APPROVED** [review]
LGTM, TIL that we could have internal libraries now in cabal files :tada: 
That's great!

I'll rebase and get it merge.

**Review by KtorZ — CHANGES_REQUESTED** [review]
Hmm.. After re-basing this, it seems that it completely messes up weeder actually which isn't able to detect unused dependencies anymore and is confused by quite a few things.
I'll be inclined to only merge if we can get this to work fine with weeder as we loose quite some helpful warnings otherwise :/

**Comment by rvl** [comment]
In my view, _internal libraries > Weeder_. So if Weeder doesn't work, weed Weeder.

**Comment by KtorZ** [comment]
>  internal libraries > Weeder

I slightly disagree here :no_mouth:  ... Unless internal libraries allow us for computing coverage on them too but it seems to me that the stack toolkit hasn't quite caught up with this cabal features as well. This requires a bit more work I think before we can merge it, to make sure we keep our current tooling working fine with internal libraries / stanzas (I am not sure which one is causing issues here).

**Comment by rvl** [comment]
OK, closing this for now :frowning_face: until we can fix Weeder.

@KtorZ What is the issue with stack and code coverage? Has a bug report been made to the HPC or SHC projects?

**Pull request closed without merging**
