### PR TITLE
pick another input when dangling fees are too big

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

N/A

# Overview

- [x] I have slightly adjusted the `remainingFee` function to not fail, but instead, allow for picking additional inputs (making for a slightly more expensive transaction) 

# Comments

Only tested manually on the example I shown on slack. Fees returned are now oscillating between `800000` and `900000`, as expected.

### CODE REVIEW

**Comment by KtorZ** [comment]
bors try

**Review by paweljakubas — APPROVED** [review]

**Comment by KtorZ** [comment]
bors bors r+

**Comment by KtorZ** [comment]
bors retry

**Pull request merged**
