### PR TITLE
Add haskell program coverage reports to Hydra tests

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

ADP-99

### Overview

This is a bit of an assortment of nix build improvements.

1. Add a code test coverage report for the Hydra build - implemented by PR input-output-hk/haskell.nix#762
2. Add a nix-shell with profiled packages. Profiled packages will be built on Hydra for master branch but not PRs. This means you can download haskell dependencies with profiling enabled, rather than having to build everything yourself.
3. Update versions of build tools in the nix-shell to latest hackage release - ghcide, hlint and stylish-haskell updated.

### Comments

- [Hydra jobset](https://hydra.iohk.io/jobset/Cardano/cardano-wallet-pr-2124)
- [Coverage report job](https://hydra.iohk.io/job/Cardano/cardano-wallet-pr-2124/musl64.testCoverageReport.x86_64-linux/latest)
- [Coverage report from bors try](https://hydra.iohk.io/build/4328848/download/2/hpc_index.html)

<details>
  <summary>Stack coverage report for comparison</summary>

  #### Command

  ```
  stack build --coverage --fast --test --skip integration --skip jormungandr-integration
  ```

  #### Result:
```
...
Generating unified report            
 26% expressions used (26186/98111)
 44% boolean coverage (136/305)
      42% guards (102/240), 72 always True, 7 always False, 59 unevaluated
      52% 'if' conditions (33/63), 4 always True, 8 always False, 18 unevaluated
      50% qualifiers (1/2), 1 always True
 40% alternatives used (849/2108)
 58% local declarations used (859/1456)
 50% top-level declarations used (1769/3533)
The unified report is available at /home/rodney/iohk/cardano-wallet/.stack-work/install/x86_64-linux/2cecc28bf3aab8c8c3e4a07c1c6c1c846ec8861df3d8a5e9247bce185aeb7542/8.6.5/hpc/combined/all/hpc_index.html
                
An index of the generated HTML coverage reports is available at /home/rodney/iohk/cardano-wallet/.stack-work/install/x86_64-linux/2cecc28bf3aab8c8c3e4a07c1c6c1c846ec8861df3d8a5e9247bce185aeb7542/8.6.5/hpc/index.html
                
--  While building package cardano-wallet-2020.9.30 using:
      /home/rodney/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build lib:cardano-wallet exe:cardano-wallet test:unit --ghc-options "-hpcdir .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/hpc -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Progress 335/336
```
</details>

### CODE REVIEW

**Review by sevanspowell — APPROVED** [review]
LGTM!

**Comment by rvl** [comment]
bors try

**Comment by rvl** [comment]
Big rebuild...

bors r+

**Comment by KtorZ** [comment]
bors merge

**Pull request merged**
