### PR TITLE
DBLayer: Add basic logging to the Sqlite backend

### PR DESCRIPTION
**Pull request by rvl**
Relates to #354

# Overview

- Adds logging to Sqlite dblayer
- Queries are logged to a separate tracer at debug level.
- Query parameters are removed before logging.

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]
:+1: LGTM

**Comment by KtorZ** [comment]
Hmmm... Somehow was merged (see https://github.com/input-output-hk/cardano-wallet/commit/30d840bff689d2cbcf0110559253d5a1a5e74df5) but the PR still appear as opened in GH :man_shrugging:

**Comment by KtorZ** [comment]
Hmmm... Somehow was merged (see https://github.com/input-output-hk/cardano-wallet/commit/30d840bff689d2cbcf0110559253d5a1a5e74df5) but the PR still appear as opened in GH :man_shrugging:

**Comment by rvl** [comment]
Weird!

**Pull request closed without merging**
