### PR TITLE
Fix documentation for `Wallet` type

### PR DESCRIPTION
**Pull request by HeinrichApfelmus**
# Issue Number

`Nothing`

# Overview

- Fixes the haddock documentation of the `Wallet` type. The type has only one type parameter.

# Comments

- This is my first PR. If there's anything I should do differently, please let me know!
- I've attempted to sign the commit with my iohk.io email address as required; I hope this worked as intended.

### CODE REVIEW

**Comment by piotr-iohk** [comment]
It appears your commit is marked as Unverified:
Screenshot from 2021-06-30 15-37-37

Perhaps you need to add your GPG key to https://github.com/settings/keys?

**Comment by HeinrichApfelmus** [comment]
> Perhaps you need to add your GPG key to https://github.com/settings/keys?

Ah, yes. I have done so now. Thanks!

**Review by piotr-iohk — APPROVED** [review]
LGTM :+1:

**Comment by piotr-iohk** [comment]
>lock Permission denied

>Existing reviewers: click here to make HeinrichApfelmus a reviewer

Some access permissions needed which I'm not able to set it seems (link gives me 404). Summoning @rvl... :mage:

**Review by rvl — APPROVED** [review]
:+1:

**Comment by rvl** [comment]
Please try the `bors r+` command again today @HeinrichApfelmus.
The bors-ng "reviewers list" is periodically updated from the list of github users with push access, but I don't know how often this happens...

P.S. Here is a link to the IOHK bors-ng web interface: https://bors-ng.aws.iohkdev.io/repositories/12

**Pull request merged**
