### PR TITLE
use a special 'WholeDomain' index with range going from 0 to 2^32 

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

#1041 

# Overview

- [x] I have used a special 'ByronHybrid' index with range going from 0 to 2^32 for the address path.

# Comments

:question: Should we also worry about the account path :question:

### CODE REVIEW

**Review by Anviking — APPROVED** [review]
Tested to restore an old wallet with addresses from 05/26 2018 or prior and it worked.

I have not given "Should we also worry about the account path" any thought now.

**Comment by Anviking** [comment]
Maybe some comment would be nice.

**Review by paweljakubas — APPROVED** [review]
unfortunately this is needed. VO of cardano-sl has erroneously implemented `generateUnique` and did opposite to what they intended to do, ie. instead of using hardened indices starting from 2^31 they use from 0 to 2^31-1, so we need to cover from 0 to 2^32

**Comment by darko-mijic** [comment]
@KtorZ, can you mention what this PR fixes in the PR title and description? This is very cryptic. The point of this is fixing the balance issue, right?

**Comment by piotr-iohk** [comment]
@darko-mijic yes. have a look at the bug connected with this PR -> https://github.com/input-output-hk/cardano-wallet/issues/1041

**Comment by carl-IOHK** [comment]
Linked to https://iohk.myjetbrains.com/youtrack/issue/IOHKS-152

**Comment by KtorZ** [comment]
Can we please not link tickets and discuss on a PULL REQUEST, but instead, use the actual ISSUE this pull requests is attached to :)?

**Pull request merged**
