### PR TITLE
Switch to use separate Win32-network repository

### PR DESCRIPTION
**Pull request by newhoggy**
# Issue Number
N/A

# Overview
`Win32-network` has been move to a separate repository.  Updating dependencies accordingly.

# Comments
N/A

### CODE REVIEW

**Review by rvl — CHANGES_REQUESTED** [review]
Thanks @newhoggy - we mainly use stack, so could you please also update `stack.yaml` and the latest snapshot in [`cardano-haskell/snapshots/`](https://github.com/input-output-hk/cardano-haskell/blob/master/snapshots`).

**Comment by newhoggy** [comment]
Something like this? https://github.com/input-output-hk/cardano-haskell/pull/41

**Comment by rvl** [comment]
Yes - thanks.

**Review by rvl — APPROVED** [review]

**Pull request merged**
