### PR TITLE
Add shelley mainnet and testnet to nightly restore tests

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

ADP-356 / #1919 

### Overview

- Ports restore benchmark to shelley backend, using cardano-mode mainnet and testnet networks.
- Add option handling to restore benchmark instead of using environment variables.
- Change restore benchmark to use cardano-node configuration in such a way that it can easily be run without the assistance of nix.

### Comments

- CLI usage below.

### CODE REVIEW

**Comment by Anviking** [comment]
I rebased and made `cardano-wallet-shelley:bench:restore` compile, but I don't know what arguments to pass it in order to test.

**Comment by rvl** [comment]
Thanks @Anviking. The way you start the benchmark now is this.

1. Ensure you have configuration files in a directory like so:
   ```
   ./configs
   ├── mainnet
   │   ├── configuration.json
   │   └── topology.json
   └── testnet
       ├── configuration.json
       └── topology.json
   ```

2. Run something like:
   ```
   stack run cardano-wallet-shelley:bench:restore -- testnet -c ./configs
   ```

   Alternatively, use the `$CARDANO_NODE_CONFIGS` environment variable coming from nix-shell. (This is the default if `-c` option is not provided.

3. If you wish to re-use the node chain data between runs, apply the `--node-db` option or set the `$NODE_DB` environment variable.

**Comment by Anviking** [comment]
Not sure why they are not starting here: https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/588#_

**Review by Anviking — APPROVED** [review]
Is the BenchShared good to have even though we are about to remove the byron component, and only have a shelley restore bench?

LGTM pending that it works.

**Comment by rvl** [comment]
I fixed the buildkite pipeline. Some things needed updating after moving the benchmark to shelley.
The new build will be here: https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/595

**Pull request merged**
