### PR TITLE
Improve error when running out of integration test faucet wallets

### PR DESCRIPTION
**Pull request by Anviking**
- <s>[x] Change from `-j 2`/`-j 3` to `-j 4` for integration tests</s>
- [x] Improve error message when running out of faucets 

### Comments

- Not sure if `-j 4` is too much. Would like to see it pass `bors try` first.

### CODE REVIEW

**Comment by Anviking** [comment]
bors try

**Review by sevanspowell — APPROVED** [review]

**Comment by jonathanknowles** [comment]
bors try

**Comment by sevanspowell** [comment]
I'm ok with this change, but it doesn't seem to have any effect on the likelihood of the mac builds passing.

**Comment by Anviking** [comment]
I'll leave the `-j` as it is for now, but merging the more descriptive "out of faucets" error message.

bors r+

**Pull request merged**
