### PR TITLE
Mark LoggingSpec pending on macOS to alleviate timeouts

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

ADP-970

# Overview

- [x] Mark LoggingSpec pending on macOS

### CODE REVIEW

**Comment by Anviking** [comment]
bors try

**Review by rvl — CHANGES_REQUESTED** [review]
I originally thought we should remove the entire spec as you have done, but then @piotr-iohk reminded me that there are some useful tests such as those checking that sensitive data is not logged.

If it's a problem only on macOS but _not at all_ on Linux, then that's a possible concern, and we should investigate a little bit.

Otherwise, how about adding a `pendingOnMacOS` function to `Test.Utils`? And/or removing the worst-offending tests, if there are such tests?

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
> Otherwise, how about adding a pendingOnMacOS function to Test.Utils? 

Done. 

> worst-offending tests, if there are such tests?

I think @jonathanknowles's investigation would suggest the properties are the worst-offending tests, but this is not at all clear from the CI logs. I marked the whole of LoggingSpec pending on macOS to be sure. (If we see that this reduces timeouts, we could try un-mark some of them later.)

**Review by rvl — APPROVED** [review]

**Comment by Anviking** [comment]
https://hydra.iohk.io/build/6660598
Another non-unit test timeout - probably related to [this](https://input-output-rnd.slack.com/archives/CAP8NM7N0/p1623673087192600?thread_ts=1623673065.192500&cid=CAP8NM7N0)
```
deleting '/nix/store/30jzd3cxgvnwh90230cdppl32r6kil63-lsp-lib-lsp-1.2.0.0'
deleting '/nix/store/j7j4886753kp7gx5sm7z3gi20x643v4k-lsp-lib-lsp-1.2.0.0-ghc-8.10.5-env'
deleting '/nix/store/hncwhl41ayjr1ln0naqzm4kq531w5rv5-lsp-lib-lsp-1.2.0.0-config'
deleting '/nix/store/0k501d4bn65zz2mw2xw6vcf2ypsg136k-lsp-types-lib-lsp-types-1.2.0.0-ghc-8.10.5-env'
deleting '/nix/store/5l9b69fimjzcqknrmwi1jxnbw0lmc987-lsp-types-lib-lsp-types-1.2.0.0'
deleted or invalidated more than 20024074240 bytes; stopping
deleting '/nix/store/trash'
error (ignored): chmod '/nix/store/trash/vwsf9k289lk5gl5kxbs067cd7iib1vrv-hls-brittany-plugin-lib-hls-brittany-plugin-1.0.0.1-ghc-8.10.5-env/exactDeps/ghc-boot-th': No such file or directory
building of '/nix/store/p148a9y1sjn71zxqc3q0xpj10in2vy21-cardano-wallet-core-lib-cardano-wallet-core-2021.6.11' timed out after 900 seconds of silence
```

**Pull request merged**
