### PR TITLE
Faster transaction fee estimation

### PR DESCRIPTION
**Pull request by Unisay**
Moved these things out of the estimation sample function:

- [x] UTxO index construction.
- [x] Wallet state retrieval.

### Issue Number

ADP-2842

### CODE REVIEW

**Comment by Unisay** [comment]
bors try

**Comment by Anviking** [comment]
If you e.g. run the integration tests and look at the endpoint timing information in the output, are you able to confirm this speeds up things?

**Comment by Unisay** [comment]
> If you e.g. run the integration tests and look at the endpoint timing information in the output, are you able to confirm this speeds up things?

Here are the latency benchmark results:
```
    Latencies for 2 fixture wallets scenario
        postTransactionFee  - 9.0 ms
    Latencies for 10 fixture wallets scenario
        postTransactionFee  - 9.2 ms
    Latencies for 100 fixture wallets
        postTransactionFee  - 16.7 ms
    Latencies for 2 fixture wallets with 10 txs scenario
        postTransactionFee  - 10.3 ms
    Latencies for 2 fixture wallets with 20 txs scenario
        postTransactionFee  - 10.8 ms
    Latencies for 2 fixture wallets with 100 txs scenario
        postTransactionFee  - 12.5 ms
    Latencies for 10 fixture wallets with 10 txs scenario
        postTransactionFee  - 11.1 ms
    Latencies for 10 fixture wallets with 20 txs scenario
        postTransactionFee  - 11.8 ms
    Latencies for 10 fixture wallets with 100 txs scenario
        postTransactionFee  - 13.9 ms
    Latencies for 2 fixture wallets with 100 utxos scenario
        postTransactionFee  - 11.9 ms
    Latencies for 2 fixture wallets with 200 utxos scenario
        postTransactionFee  - 14.2 ms
    Latencies for 2 fixture wallets with 500 utxos scenario
        postTransactionFee  - 21.5 ms
    Latencies for 2 fixture wallets with 1000 utxos scenario
        postTransactionFee  - 32.0 ms

    Latencies for 2 fixture wallets scenario
        postTransactionFee  - 9.3 ms
    Latencies for 10 fixture wallets scenario
        postTransactionFee  - 9.6 ms
    Latencies for 100 fixture wallets
        postTransactionFee  - 16.5 ms
    Latencies for 2 fixture wallets with 10 txs scenario
        postTransactionFee  - 10.0 ms
    Latencies for 2 fixture wallets with 20 txs scenario
        postTransactionFee  - 10.5 ms
    Latencies for 2 fixture wallets with 100 txs scenario
        postTransactionFee  - 12.2 ms
    Latencies for 10 fixture wallets with 10 txs scenario
        postTransactionFee  - 10.8 ms
    Latencies for 10 fixture wallets with 20 txs scenario
        postTransactionFee  - 10.8 ms
    Latencies for 10 fixture wallets with 100 txs scenario
        postTransactionFee  - 12.6 ms
    Latencies for 2 fixture wallets with 100 utxos scenario
        postTransactionFee  - 12.0 ms
    Latencies for 2 fixture wallets with 200 utxos scenario
        postTransactionFee  - 13.4 ms
    Latencies for 2 fixture wallets with 500 utxos scenario
        postTransactionFee  - 21.2 ms
    Latencies for 2 fixture wallets with 1000 utxos scenario
        postTransactionFee  - 25.7 ms
```

**Comment by piotr-iohk** [comment]
> Here are the latency benchmark results:

Is that before vs. after?
Looks like the fee estimation is rather within the same range performance wise. 

I've started restoration benchmark (https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/1728#01870339-f64d-463a-ac80-a3f6b4388678) there is an estimate_fee measure there too, but it's done on slightly bigger wallet, perhaps it will reveal improvement...

**Comment by Anviking** [comment]
Note that `postDelegationFee` is the only fee-estimation endpoint currently reusing balanceTx. I suspect there's no benchmark for `postDelegationFee` specifically. My suggestion was to run the relevant integration tests and observe the logged timing info for the API endpoint calls. (And yes, before vs after would be nice)

**Comment by Anviking** [comment]
<s>However... it seems we're not even testing `getDelegationFee` in an integration tests </s> No it's here: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/wallet/integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs#L974-L982

**Comment by Unisay** [comment]
I ran IT many 5-6 times and can hardly notice any difference:

image

**Comment by Unisay** [comment]
Even without noticeable speedup I am still in favor of merging this PR as it does code refactoring in a semantically proper direction: we don't want to rebuild index and re-read wallet state every loop iteration. I like the idea of passing UTxO index from the outside, and it also removes the need to pass a set of pending txs, which felt like a wart anyway.

**Review by Anviking — APPROVED** [review]
I see a 13s to 0.2s speedup locally compared to recent master 🎉 

```
[cardano-wallet.api-server:Error:891] [2023-03-22 14:13:01.16 UTC] [RequestId 2] GET /v2/wallets/2d4cc31a4b3116ab86bfe529d30d9c362acd0b44/delegation-fees 200 OK in 13.220051s
```

```
[cardano-wallet.api-server:Info:887] [2023-03-22 14:19:53.39 UTC] [RequestId 2] GET /v2/wallets/2d4cc31a4b3116ab86bfe529d30d9c362acd0b44/delegation-fees 200 OK in 0.206966s
```
(Calling `CARDANO_WALLET_TRACING_MIN_SEVERITY=Info cabal test cardano-wallet:integration --test-options '--match "STAKE_POOLS_ESTIMATE_FEE_01"'`)

**Comment by Unisay** [comment]
bors merge

**Comment by Unisay** [comment]
bors merge

**Pull request merged**
