### PR TITLE
Initial decimals support

### PR DESCRIPTION
**Pull request by sevanspowell**
# Issue Number

ADP-915

# Overview

- [x] I have added initial support for the asset metadata "decimals" field

### CODE REVIEW

**Review by rvl — APPROVED** [review]
Looks good.
Could you please also remove "unit" - I never got around to doing it.

**Comment by piotr-iohk** [comment]
@sevanspowell Just to note. Using wallet from this branch on testnet I'm not able to see decimals:
1. I have added metadata with decimals: https://github.com/input-output-hk/metadata-registry-testnet/pull/109/files
2. Decimals seem to be there on metadata server -> https://metadata.cardano-testnet.iohkdev.io/metadata/6b1b1cc20a8d37d1d7bea2ca5427335c7f4c586e70692333153ef38354455354444543494d414c533
3. However in wallet I cannot see them...
```
$ curl -X GET http://localhost:8090/v2/wallets/1ceb45b37a94c7022837b5ca14045f11a5927c65/assets/6b1b1cc20a8d37d1d7bea2ca5427335c7f4c586e70692333153ef383/54455354444543494d414c5330 | jq
  
{
  "asset_name": "54455354444543494d414c5330",
  "fingerprint": "asset13sewuyf7e6hau2fjav3qmsev4jfdfxzlvakqmt",
  "policy_id": "6b1b1cc20a8d37d1d7bea2ca5427335c7f4c586e70692333153ef383",
  "metadata": {
    "name": "DECIMALSCOIN",
    "description": "Test Decimals"
  }
}

```

**Comment by rvl** [comment]
Flakiness, sorry.

bors r+

**Pull request merged**
