### PR TITLE
Remove `{mint,burn}` fields from API, primitive transaction types, and DB schema.

### PR DESCRIPTION
**Pull request by jonathanknowles**
## Issue Number

ADP-1654

## Summary

In this PR, we:

1. Remove (currently unused) field `mint` from `Api.Types.ApiTransaction`.
2. Remove fields `{mint,burn}` from `Primitive.Types.Tx`.
3. Remove fields `txInfo{Mint,Burn}` from `Primitive.Types.TransactionInfo`.
4. Remove types `Primitive.Types.Tx{Mint,Burn}`.
5. Remove database relations `Tx{Mint,Burn}`.

### CODE REVIEW

**Comment by jonathanknowles** [comment]
bors try

**Comment by jonathanknowles** [comment]
bors try

**Comment by jonathanknowles** [comment]
bors cancel

**Comment by jonathanknowles** [comment]
bors try

**Comment by jonathanknowles** [comment]
bors try

**Comment by jonathanknowles** [comment]
bors try

**Review by piotr-iohk — APPROVED** [review]
LGTM.

**Pull request merged**
