### PR TITLE
Update NodeToClientV_6 → NodeToClientV_8

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

ADP-672

### Overview

- LocalStateQuery protocol codec change, allows to acquire tip point.
- Replace multiple definitions of NodeToClientVersion.

### Comments
- Based on PR #2459 branch - merge that first.

### CODE REVIEW

**Review by Anviking — APPROVED** [review]

**Review by KtorZ — APPROVED** [review]

**Comment by KtorZ** [comment]
It doesn't compile yet :sweat_smile:

**Comment by rvl** [comment]
Oops, it did compile then I removed an import...

bors r+

**Comment by Anviking** [comment]
😅 I was just thinking bors was stuck again 🎉

**Comment by rvl** [comment]
Looks like a github problem. Usually it says "iohk-bors [bot] added a commit that referenced this pull request: b1a93198bc676e7c241417cb91d94ffec142ce55"

**Comment by Anviking** [comment]
It took a while for bors to succeed after both buildkite and hydra had passed

**Pull request merged**
