### PR TITLE
Bump cardano-node

### PR DESCRIPTION
**Pull request by Anviking**
- Appears to break compatibility with the most recent FF genesis
- Should include what we need to get non myopic member rewards

### CODE REVIEW

**Comment by Anviking** [comment]
bors try

**Comment by rvl** [comment]
Looks like there is a proper build failure in `cardano-node/cardano-config`. I have asked about it on slack.

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
Do we merge this now even if it breaks FF compatibility? Maybe we do still…?

**Review by rvl — APPROVED** [review]
Looks good to me. I am not sure whether we should wait for a ff respin before merging.

**Comment by piotr-iohk** [comment]
> Looks good to me. I am not sure whether we should wait for a ff respin before merging.

I'd be for waiting a bit unless it is blocking further development.

**Review by KtorZ — APPROVED** [review]

**Comment by Anviking** [comment]
It compiles locally for me, and it seems rebased 🤔

**Comment by Anviking** [comment]
Ah, maybe due to other PRs in the same batch

**Pull request merged**
