### PR TITLE
Bump version from 2020.12.08 to 2020.12.21

### PR DESCRIPTION
**Pull request by jonathanknowles**
# Issue Number

None.

# Overview

Bumps the version from `2020.12.08` to `2020.12.21`, in preparation for release.

### CODE REVIEW

**Comment by piotr-iohk** [comment]
@jonathanknowles I think you didn't commit the "outcome" of the make_release.sh, (i.e. version bump on various *.nix files etc.)

**Comment by jonathanknowles** [comment]
> @jonathanknowles I think you didn't commit the "outcome" of the make_release.sh, (i.e. version bump on various *.nix files etc.)

This should now be fixed. (I had to run `nix/regenerate.sh` manually.)

**Review by piotr-iohk — APPROVED** [review]
LGTM

**Comment by rvl** [comment]
The `make_release.sh` script checks for remaining instances of the old tag. If the version bump worked properly, it should not find anything. It looks like the script did not work properly ⇒ #2407.

**Pull request merged**
