### PR TITLE
Fix caching in first scenarion latency benchmarking

### PR DESCRIPTION
**Pull request by paweljakubas**
# Issue Number

Just make all network measurements comparable in all scenarios and runs. Always rely on cashing present.

# Overview

- [ ] I have ...

# Comments

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]

**Review by piotr-iohk — APPROVED** [review]

**Comment by paweljakubas** [comment]
another occurrence of : 
```
  src/Test/Integration/Scenario/API/Byron/Wallets.hs:557:9:
  1) API Specifications, BYRON_WALLETS_RESYNC_01, emptyRandomWallet - force resync eventually get us back to the same point
       uncaught exception: IOException of type UserError
       user error (waited more than 3min for action to eventually resolve. Action: "Wallet re-syncs successfully")

  To rerun use: --match "/API Specifications/BYRON_WALLETS_RESYNC_01/emptyRandomWallet - force resync eventually get us back to the same point/"

  src/Test/Integration/Scenario/API/Byron/Wallets.hs:560:9:
  2) API Specifications, BYRON_WALLETS_RESYNC_01, emptyIcarusWallet - force resync eventually get us back to the same point
       uncaught exception: IOException of type UserError
       user error (waited more than 3min for action to eventually resolve. Action: "Wallet re-syncs successfully")

  To rerun use: --match "/API Specifications/BYRON_WALLETS_RESYNC_01/emptyIcarusWallet - force resync eventually get us back to the same point/"
```

**Review by rvl — APPROVED** [review]
Maybe "warming up" caches should be part of the `measureLatency` function, if you want to measure like that.

Which value is being cached? Is it the node tip? Because the way that's fetched has changed with #1580.

**Pull request merged**
