### PR TITLE
Trezor mnemonics in genesis file + README update

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

N/A

# Overview

- [x] I have added 12,18 and 24 words faucet wallets in the integration genesis file. 
- [x] I added the latest release to the README
- [x] I did some gratuitous updates to the README 

# Comments

### CODE REVIEW

**Comment by KtorZ** [comment]
bors try

**Review by piotr-iohk — APPROVED** [review]

**Comment by KtorZ** [comment]
Nix nix nix...

**Comment by rvl** [comment]
It's not nix, it's lack of disk space.

**Comment by darko-mijic** [comment]
❤️

**Comment by KtorZ** [comment]
I know it's not "Nix" ... but the error are sooooo confusing / misleading. It's like you need a side manual to interpret the errors from the Nix builds and understand what's the cause. 

Nix itself has most likely nothing to do with this... but our CI is sort of... clunky.

**Review by rvl — APPROVED** [review]

**Pull request merged**
