### PR TITLE
Manual test for syncProgress

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

#921 

# Overview

- [x] I have added a manual test making sure 1. State is `Ready`, 2. syncProgress drops when node is killed, 3. syncProgress reaches `Ready` again when node is re-started.

# Comments

### CODE REVIEW

**Review by piotr-iohk — APPROVED** [review]
lgtm!

**Review by KtorZ — APPROVED** [review]
cc @piotr-iohk

**Comment by KtorZ** [comment]
@Anviking I just noticed the file location. 
May we put this in `cardano-wallet-jormungandr` :pray: ?

**Comment by piotr-iohk** [comment]
> May we put this in cardano-wallet-jormungandr...

Actually, I think it is more convenient to have all manual procedures in the same location, so one doesn't have to switch dirs too much when going from one to another... we don't have a lot of them but still.. What do you think @KtorZ, @Anviking ?

**Comment by Anviking** [comment]
> have all manual procedures in the same location

Maybe. There is already an existing `lib/jormungandr/test/manual/TrackBlockHeight.md` however.

I just renamed the addition to `lib/jormungandr/test/manual/SyncProgress.md` to match it.

What would feel off to me is that this test is really testing functionality in `core`. But it does that _using_  using `jormungandr`. 🤔

**Comment by piotr-iohk** [comment]
@Anviking that makes sense. Maybe it'd be better actually to have an additional file with an index/table of contents with links to all manual procedures for convenience.
Something I can think of and add later, no worries.

**Comment by KtorZ** [comment]
> Actually, I think it is more convenient to have all manual procedures in the same location 

I agree. Then, it makes sense to have them all in a parent location, at the root of the project perhaps? Let's move them all in a `test/manual` folder located in the root.

**Pull request merged**
