### PR TITLE
Remove the `strict-non-empty-containers` library. 🚮

### PR DESCRIPTION
**Pull request by jonathanknowles**
## Issue

ADP-3061

## Summary

This PR removes the `strict-non-empty-containers` library, which is made obsolete by the following PRs:
- https://github.com/input-output-hk/cardano-wallet/pull/3980
- https://github.com/input-output-hk/cardano-wallet/pull/3981
- https://github.com/input-output-hk/cardano-wallet/pull/3982
- https://github.com/input-output-hk/cardano-wallet/pull/3983

### CODE REVIEW

**Review by Unisay — APPROVED** [review]
lgtm

**Comment by jonathanknowles** [comment]
I have manually verified that this PR does not cause any failures in the following test suites:
- `cardano-wallet-primitive:test:test`
- `cardano-wallet:test:unit`
- `cardano-wallet:test:integration`

**Comment by HeinrichApfelmus** [comment]
I'm afraid, but this pull request fails CI — The "Check Hlint" step fails.

https://buildkite.com/cardanofoundation/cardano-wallet/builds/62

**Comment by jonathanknowles** [comment]
> I'm afraid, but this pull request fails CI — The "Check Hlint" step fails.

My apologies! I see that @paolino has thankfully fixed this in #4011. Thank-you @paolino!

**Pull request merged**
