### PR TITLE
Replace CLI `--min-log-severity` argument with `--quiet` and `--verbose` switches.

### PR DESCRIPTION
**Pull request by jonathanknowles**
# Issue Number

#350 

# Overview

This PR replaces the `--min-log-severity` argument with two new switches:

* `--quiet`
* `--verbose`

These switches have the following semantics:

| Switch | Help Text | Minimum Log Severity Level |
| -- | -- | -- |
| `--quiet` | suppress all log output apart from errors | [`Error`](https://github.com/input-output-hk/iohk-monitoring-framework/blob/master/iohk-monitoring/src/Cardano/BM/Data/Severity.lhs#L39) |
| `--verbose` | display debugging information in the log output | [`Debug`](https://github.com/input-output-hk/iohk-monitoring-framework/blob/master/iohk-monitoring/src/Cardano/BM/Data/Severity.lhs#L35) |
| (none) | (default) | [`Info`](https://github.com/input-output-hk/iohk-monitoring-framework/blob/master/iohk-monitoring/src/Cardano/BM/Data/Severity.lhs#L36) |

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]
Looking good. 
Remains to update our CI to use a version of the bridge supporting this. I've updated my fork (used in CI) and now provide a pre-compiled binary that can be used in Travis:

https://github.com/KtorZ/cardano-http-bridge/releases/tag/v0.0.2

So, let's update `travis.yml` and remove the old file located inside our repository:

https://github.com/input-output-hk/cardano-wallet/blob/master/.travis.yml#L43-L44

**Comment by jonathanknowles** [comment]
> So, let's update `travis.yml` and remove the old file located inside our repository:
> 
> https://github.com/input-output-hk/cardano-wallet/blob/master/.travis.yml#L43-L44

This should now be done with the following changes:
* https://github.com/input-output-hk/cardano-wallet/pull/450/commits/f553db4fe6bdd6315baf95c420fcd94ab81c1a0d
* https://github.com/input-output-hk/cardano-wallet/pull/450/commits/d1f38fcfd517afa0bc66152b0671e8a9cc15695a

**Comment by jonathanknowles** [comment]
> Arf... The file isn't executable?

It seems `curl` does not set the executable bit. I'm guessing that it doesn't have this capability.

**Comment by KtorZ** [comment]
I don't think the problem is `cURL`, the file isn't executable in a first place. Let me fix that :+1:

**Comment by KtorZ** [comment]
@jonathanknowles 

```
$ curl -L https://github.com/KtorZ/cardano-http-bridge/releases/download/v0.0.2/cardano-http-bridge-v0.0.2-x86_64-linux.tar.gz | tar xz -C $HOME/.local/bin
$ ls -lh $HOME/.local/bin/cardano-http-bridge
-rwxr-xr-x 1 ktorz ktorz 12M juin  21 10:43 /home/ktorz/.local/bin/cardano-http-bridge
$ cardano-http-bridge start --help
cardano-http-bridge-start 
start explorer server

USAGE:
    cardano-http-bridge start [FLAGS] [OPTIONS]

FLAGS:
    -h, --help       Prints help information
        --no-sync    disable synchronizing with the upstream network
        --quiet      suppress all log output apart from errors
        --silent     suppress all log output
    -V, --version    Prints version information
        --verbose    display debugging information in the log output

OPTIONS:
        --networks-dir <NETWORKS DIRECTORY>    the relative or absolute directory of the networks to server
        --port <PORT NUMBER>                   set the port number to listen to [default: 80]
        --template <TEMPLATE>...               either 'mainnet' or 'testnet'; may be given multiple times [default: mainnet]
```

**Pull request merged**
