### PR TITLE
Track block height in `Wallet` checkpoints

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

#640

# Overview

- [x] I have extended `Wallet` to contain the chain height as a `Quantity "block" Natural`
- [x] I have stored it in the Sqlite database as a `Word64`
- [x] I log the block height in `restoreBlocks`
- [x] I have added two property test in `ModelSpec` that states the block height starts at 0 and increases by 1 on each `applyBlock`

# Comments
- ~Terminology: chain height vs block height?~ Block height seems to be the accepted term indeed

### CODE REVIEW

**Comment by rvl** [comment]
Looks good so far.

I'm not sure about the terminology chain height vs block height. I suppose they are interchangeable terms. Do you have a reference where chain height is used?

It would be great to have structured logging of the block/chain height, but in a subsequent PR.

**Comment by Anviking** [comment]
> Do you have a reference where chain height is used?

Good point, thanks. No. Thought `blockHeight` sounded more like an attribute of a block rather than one of a chain/checkpoint, but I see it is the term used. Changed.

**Comment by Anviking** [comment]
I added two properties in `ModelSpec`. 

I think it would be comforting to check that our `blockHeight` state matches `blockNo` of shelley blocks, but we can't do that before we support the new haskell node.

Also, I'm not sure if we need to be concerned with say EBBs, or other unpleasant details. In a slack-search I saw something about EBBs not affecting the block height 🤔

**Review by rvl — APPROVED** [review]
Looks good to me!

**Pull request merged**
