### PR TITLE
[draft] split up logic from Byron/Network and work from abstract block

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

# Overview

- f6ccdae2aee3bb6f5d78020f38e5daf7078a0677
  :round_pushpin: **[draft] split up logic from Byron/Network and work from abstract block**
  
- c95429a1a9c896330ab463f338ed91f5df941387
  :round_pushpin: **Regenerate nix**
  
- 74b90f1b06bf9a5b62e04136f38b9d320ea93423
  :round_pushpin: **wip start remove**
  
- 4e594a5258a4f34fae03ade52529cae074e9f5db
  :round_pushpin: **continue extracting local state query and local tx submission clients**
  
- a1debd652be3f9b97da2024ab5f80dd66ea303ee
  :round_pushpin: **start re-using extracted client in Byron/Network [WIP]**
  
- 12386371b47f172a983668f7e3bbe3b910a327e6
  :round_pushpin: **finish re-using extracted code in Ouroboros.Network.Client.Wallet**
  
- 5fea8b9273994fdc7063257bebd76debd23fa282
  :round_pushpin: **remove last redundant imports from Ouroboros.Network.Client.Wallet**

# Comments

Possible further code-sharing / re-use after this PR:

- Logic for initiating the connection, managing retries etc ..
- The network layer logs
- Use the default codecs whenever possible instead of writing them by hand

Yet, I'd maybe suggest another PR for these :thinking:

### CODE REVIEW

**Comment by KtorZ** [comment]
bors try

**Review by Anviking — APPROVED** [review]
lgtm!

**Comment by KtorZ** [comment]
Failed on #1644 , unrelated but annoying.

**Pull request merged**
