### PR TITLE
use a patched openapi3 lib

### PR DESCRIPTION
**Pull request by paolino**
- this is a separate PR just to update the git sources to use a modified openlib3
- stack and cabal are modified and in sync 
- a todo is added to a tech debt ticket to remind us to remove this change when the patch is absorbed
- no use of anyOf is in the code, for now,  it  will become useful in the next PR

### Issue Number
ADP-1596

### CODE REVIEW

**Review by Anviking — APPROVED** [review]
lgtm! (assuming you've tested it locally) One nitpick: https://github.com/paolino/openapi3/commit/0e941808658896fe0d2b521af9fd4af1015c84c5#r71817634

**Review by Unisay — APPROVED** [review]
Makes sense to me

**Comment by paolino** [comment]
bors try

**Comment by paolino** [comment]
bors try

**Comment by paolino** [comment]
bors try

**Pull request merged**
