### PR TITLE
Add basic infrastructure for logging.

### PR DESCRIPTION
**Pull request by jonathanknowles**
# Issue Number

#350

# Overview

I have:

- [x] added `iohk-monitoring-framework` as a dependency.
- [x] added basic logging support.
- [x] used new logging functionality within `Cardano.Wallet` (instead of `putStrLn`).

# Comments

### CODE REVIEW

**Comment by rvl** [comment]
Rather than wrapping logging, I would pass around the `Trace` object and use the functions in `Cardano.BM.Trace` on it.

**Comment by jonathanknowles** [comment]
@rvl wrote:

> Rather than wrapping logging, I would pass around the `Trace` object and use the functions in `Cardano.BM.Trace` on it.

We could certainly do that.

I had initially assumed that there was no way to create a mock `Tracer` object, and so I created the wrapper to make it easy to disable logging in our tests. But now I see that there is a [`nullTracer`](https://github.com/input-output-hk/iohk-monitoring-framework/blob/master/contra-tracer/src/Control/Tracer.lhs#L133) available. So we could use that instead.

**Comment by jonathanknowles** [comment]
@rvl wrote:
> Rather than wrapping logging, I would pass around the `Trace` object and use the functions in `Cardano.BM.Trace` on it.

I've pushed a [change](https://github.com/input-output-hk/cardano-wallet/pull/390/commits/b360c3a78a6b89c2e219e1826ab0355a5e7b4d40) which passes around the `Trace` object directly, rather than using a wrapper.

**Review by rvl — APPROVED** [review]
Looks good

**Pull request merged**
