### PR TITLE
Light-mode: protocol parameters contain era infos.

### PR DESCRIPTION
**Pull request by Unisay**
Protocol  parameters contain information on when each era starts also in light mode.

Before:
```
http http://localhost:8090/v2/network/parameters | jq .eras
{
  "allegra": null,
  "alonzo": null,
  "babbage": null,
  "byron": null,
  "mary": null,
  "shelley": null
}
```

After:
```
http http://localhost:8090/v2/network/parameters | jq .eras
{
  "allegra": {
    "epoch_number": 102,
    "epoch_start_time": "2020-12-15T20:20:16Z"
  },
  "alonzo": {
    "epoch_number": 154,
    "epoch_start_time": "2021-09-01T20:20:16Z"
  },
  "babbage": null,
  "byron": {
    "epoch_number": 0,
    "epoch_start_time": "2019-07-24T20:20:16Z"
  },
  "mary": {
    "epoch_number": 112,
    "epoch_start_time": "2021-02-03T20:20:16Z"
  },
  "shelley": {
    "epoch_number": 74,
    "epoch_start_time": "2020-07-28T20:20:16Z"
  }
}
```

### Issue Number

ADP-1827

### CODE REVIEW

**Review by paolino — APPROVED** [review]
LGTM, thanks

**Comment by paolino** [comment]
CI failed:

  To rerun use: --match "/Cardano.Wallet.Api.Server.Tls/TLS Client Authentication/Deny client with wrong certificate if TLS is enabled/"

**Comment by paolino** [comment]
bors try

**Comment by paolino** [comment]
CI failed:

To rerun use: --match "/API Specifications/SHELLEY_MIGRATIONS/SHELLEY_MIGRATE_09 - Can migrate a wallet that has rewards./"

**Comment by paolino** [comment]
bors try

**Comment by Unisay** [comment]
bors merge

**Pull request merged**
