### PR TITLE
jira: update endpoint URL

### PR DESCRIPTION
**Pull request by rvl**
We have a new jira server. Update the go-jira config and links.

### Comments

To make go-jira work again, you will need to get a new API token and update your go-jira config.

### CODE REVIEW

**Review by jonathanknowles — APPROVED** [review]

**Comment by sevanspowell** [comment]
Oooh yay! I've got a couple of helpful things to add, for people who don't use an explicit keyring...

**Comment by sevanspowell** [comment]
Completely optional PR: https://github.com/input-output-hk/cardano-wallet/pull/2871

**Comment by rvl** [comment]
Thanks @sevanspowell. You can just push to my PR branches, I don't mind.

**Pull request merged**
