### PR TITLE
Remove rest mnemonic bits

### PR DESCRIPTION
**Pull request by paweljakubas**
# Issue Number

#1601 

# Overview

- [x] I have removed FromMnemonic, FrommnemonicError and NatVal from AddressDerivation module and used stuff from Cardano.Mnemonic from cardano-addresses

# Comments

### CODE REVIEW

**Comment by paweljakubas** [comment]
bors try

**Comment by paweljakubas** [comment]
bors try

**Comment by paweljakubas** [comment]
bors try

**Comment by paweljakubas** [comment]
bors stop

**Comment by paweljakubas** [comment]
bors cancel

**Comment by paweljakubas** [comment]
bors try

**Comment by paweljakubas** [comment]
bors try

**Comment by paweljakubas** [comment]
bors try

**Review by rvl — APPROVED** [review]
Happy, if it type checks.

**Comment by paweljakubas** [comment]
bors retry

**Pull request merged**
