### PR TITLE
Add `DeltasCheckpoints` list type

### PR DESCRIPTION
**Pull request by HeinrichApfelmus**
### Issue number

ADP-1043

### Overview

This pull request is a small refactoring where…

…we introduce a `DeltasCheckpoints` to store a list of delta encodings.

Specifically, we

* define `DeltasCheckpoints a = [DeltaCheckpoints a]`
* use this for the wallet state delta

### CODE REVIEW

**Review by paolino — COMMENTED** [review]
Did you consider having a DeltaChecpointsList instead? I'm a bit perplexed with the '1' letter, but I cannot explain why.

**Review by paweljakubas — APPROVED** [review]
for me `DeltaCheckpoints` (there is `s` here) reflects in its naming that we deal with collection. But, I would rename one checkpoint action to `DeltaCheckpointAction` - it is either rollback or inscribing the checkpoint in the end. So we would have in the end: 
```
type DeltaCheckpoints a = [DeltaCheckpointsAction a]
``` 

Of course, this is just a proposal that I am slightly in favor of.

**Comment by HeinrichApfelmus** [comment]
Ah. My original motivation for the name `DeltaCheckpoints` was that it's a delta encoding for the `Checkpoints` type, not that the delta encoding itself is a collection (list) of actions. (The delta encoding does affect a collection of checkpoints, not just an individual checkpoint, hence the plural in `Checkpoints`.)

What about the combo
* `DeltasCheckpoints = [DeltaCheckpoints]`
* `DeltaCheckpoints`

? 🤔 That would put the plural with the word "Delta".

(As there each type may have multiple delta encodings associated with it, we may run into this issue of naming specific delta encodings more often. 😅 )

**Comment by paweljakubas** [comment]
@HeinrichApfelmus yes, yes. I wanted to be more revolutionary and meant 
```
type CheckpointDeltas a = [CheckpointDeltaAction a]
```
or just
```
type CheckpointDeltas a = [CheckpointDelta a]
```

**Comment by HeinrichApfelmus** [comment]
>  I wanted to be more revolutionary and meant […] `type CheckpointDeltas a = [CheckpointDelta a]`

Oh, I see. Hm, I got used to putting the `Delta` in front of the name (e.g. `DeltaMap`, `DeltaUTxO`, …). If we start putting `Delta` at the end of the name, we should probably do it for all names. 🤔

**Comment by HeinrichApfelmus** [comment]
In order to move forward, I have added a `DeltasCheckpoints` type for now. We can revisit this later. 🤓

**Comment by HeinrichApfelmus** [comment]
bors merge

**Pull request merged**
