### PR TITLE
API: get and list only assets associated with the wallet

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

ADP-603 / ADP-604

### Overview

- The list assets endpoint now returns all assets of the wallet, not just available assets.
- The get asset endpoint checks that the asset id really is associated with the wallet.

### CODE REVIEW

**Review by piotr-iohk — APPROVED** [review]
LGTM.

I wonder if we should also return `404` on list assets when there are no assets associated. Currently it returns just `[]`.

Note to self: check this on Byron wallets once #2489 is merged.

**Comment by KtorZ** [comment]
> I wonder if we should also return 404 on list assets when there are no assets associated. Currently it returns just [].

It should return 404 when the wallet id isn't found. If the wallet is found but there are no assets, then `[]` is sound.

**Comment by piotr-iohk** [comment]
> It should return 404 when the wallet id isn't found. If the wallet is found but there are no assets, then `[]` is sound.

Yeah, but get assets returns in `404` in such case:

```
{"code":"asset_not_present","message":"The requested asset is not associated with this wallet."}
```

So I was thinking it would be nice consistency if list wallet returned something similar... but maybe `[]` is fine indeed.

**Comment by rvl** [comment]
To me, the 404 response is an error which means that the request path was referring to a resource that doesn't exist.
So, when trying to look up an AssetId which is not present, 404 is the correct response.
But when looking at the `/wallets/<wid>/assets` collection, that resource exists, even if it could be empty. Same goes with the transactions list.

**Comment by rvl** [comment]
Thanks for the review and noticing the issue.

bors r+

**Pull request merged**
