### PR TITLE
make decodeTx not so strict when policy key is missing

### PR DESCRIPTION
**Pull request by paweljakubas**
adp-1549

- [x] I have make sure checking for policy key is only taking place when minting/burning is on.

### CODE REVIEW

**Comment by piotr-iohk** [comment]
I've run e2e suite against this PR -> https://github.com/input-output-hk/cardano-wallet/runs/5646577836?check_suite_focus=true

Most of the tests are now passing (i.e. the fix addresses some of the failures), but not all of them.

The remaining failures are:
 - Plutus transactions that mint some tokens
 - Constructing the minting transaction
 
**Plutus:** 
```
rspec ./spec/e2e_spec.rb:102 # Cardano Wallet E2E tests E2E Balance -> Sign -> Submit game
rspec ./spec/e2e_spec.rb:109 # Cardano Wallet E2E tests E2E Balance -> Sign -> Submit mint-burn
rspec ./spec/e2e_spec.rb:200 # Cardano Wallet E2E tests E2E Balance -> Sign -> Submit currency
```
These are Plutus scripts that actually mint some tokens and they fail with the same error:
```
{"code":"invalid_wallet_type",
"message":"It seems the wallet lacks a policy public key. It's therefore not possible to create a minting or burning transaction. Please restore the wallet from a mnemonic phrase instead of an account public key."}
```

**Construct mint tx:**
Also constructing mint transaction still fails:
```
$ curl -X POST http://localhost:8090/v2/wallets/2269611a3c10b219b0d38d74b004c298b76d16a9/transactions-construct \
-d '{"mint_burn":[{"operation":{"mint":{"receiving_address":"addr_test1qq223dyrt96yx79rz3yda2vs6xjx28ts2ax39hp8cxq2p0shpgwhzykzha0z6w27gxsps40gurvxjt2vxh26009q5wqqxpj2ey","amount":{"quantity":1,"unit":"assets"}}},"policy_script_template":"cosigner#0","asset_name":"1111"}]}' \
-H "Content-Type: application/json" | jq

{
  "code": "invalid_wallet_type",
  "message": "It seems the wallet lacks a policy public key. It's therefore not possible to create a minting or burning transaction. Please restore the wallet from a mnemonic phrase instead of an account public key."
}

```

**Comment by paweljakubas** [comment]
@piotr-iohk  plutus scripts now should pass. construct tx should not proceed when policy key is missing. I will add a way to set this key (via endpoint as it is not possible to do it with db migrations) in next PR.

**Comment by piotr-iohk** [comment]
> @piotr-iohk plutus scripts now should pass. construct tx should not proceed when policy key is missing. I will add a way to set this key (via endpoint as it is not possible to do it with db migrations) in next PR.

Executed e2e suite against this branch after changes again. 
```
>> cardano-node and cardano-wallet versions:
v2022-01-18 (git revision: 860a27c18ba5bca2392c0f4ea6cdd74812f275db)
cardano-node 1.34.1 - linux-x86_64 - git rev 73f9a746362695dc2cb63ba757fbcabb81733d23
```

All is passing now:

https://github.com/input-output-hk/cardano-wallet/actions/runs/2028501957


**Note:** Construct mint tx would still fail (there is no such test in e2e suite yet.), but I understand that's a topic for another PR.

**Review by piotr-iohk — APPROVED** [review]

**Comment by paweljakubas** [comment]
bors retry

**Pull request merged**
