### PR TITLE
wire pool's 'pledge' from the registration certificate unto the Api

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

#1719

# Overview

- 027ce66467d233607024a23a84f7a84962a9cdb9
  :round_pushpin: **wire pool's 'pledge' from the registration certificate unto the Api**
  
- 37384c6fd7add6864c27f657b5621379600199aa
  :round_pushpin: **fix typo in swagger documentation 'ommitted' -> 'omitted'**
  
- 0c615405e0f2267e5a1976b0b0233c41528873fb
  :round_pushpin: **add integration test showing that pledge is correctly discovered**

  
# Comments

Screenshot from 2020-06-25 18-17-08

### CODE REVIEW

**Review by Anviking — APPROVED** [review]
lgtm

**Comment by Anviking** [comment]
We can add a check in the integration tests though.

**Comment by KtorZ** [comment]
bors retry

**Pull request merged**
