### PR TITLE
Build Jörmungandr in CI 

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

#242 

# Overview

# Comments

### CODE REVIEW

**Comment by KtorZ** [comment]
@Anviking Make sure to also try this on an empty cache. I believe we will have to split the `Compiling` job into two jobs; we were already approaching 45/46 minutes build-time on empty cache. Adding Jormungandr will probably put us above the 50minutes limit..

**Comment by Anviking** [comment]
@KtorZ 

I guessed that would mean split it like I've done now into two ~stages~ jobs.

Before I rebased, the integration tests failed because of missing `cardano-http-bridge`. They passed when re-running that stage 🤔

**Comment by Anviking** [comment]
Skärmavbild 2019-05-20 kl  10 08 33

**Comment by KtorZ** [comment]
@Anviking Unfortunately, you can't put them as part of the same `stage`, because there's going to be some cache conflicts / races since both will try to update the cache (and actually, the second one will likely overwrite the cache of the other, this is probably what happens in your testnet job... not sure how it got resolve however :thinking: ). I'd suggest to have the `compile dependencies` done first, and then, have another stage that is just about compiling the Haskell part.

**Comment by Anviking** [comment]
Closing in favour for #284

**Pull request closed without merging**
