### PR TITLE
Rename projects, executables and update travis deploy step

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

None.

# Overview

- [ ] WIP: Make sure binaries are uploaded to travis
- [x] Instead of `cardano-wallet-byron` and `cardano-wallet-jormungandr`, let's have `cardano-wallet` and `cardano-wallet-itn`.

# Comments

### CODE REVIEW

**Comment by Anviking** [comment]
bors try

**Comment by KtorZ** [comment]
I am afraid of the number of things this would break in the nix pipeline, hydra and al ... We should just go with the Travis change (and the binaries renamed there first) and possibly, rename then the cabal packages.

**Comment by Anviking** [comment]
Superseded by #1544

**Comment by rvl** [comment]
@Anviking @KtorZ One thing that could also be done is move the Cabal packages up to the top-level, instead of having them inside `lib`.

**Pull request closed without merging**
