### PR TITLE
Make sure application exits when Daedalus IPC channel closes

### PR DESCRIPTION
**Pull request by rvl**
# Issue Number

TBA

# Overview

The wallet was failing to exit in time if the DaedalusIPC channel was disconnected during jormungandr's bootstrap phase. This was because it was waiting for bootstrap to complete before exiting.

- This change makes the wallet exit as soon as the DaedalusIPC channel is closed.

# Comments

- I have undisabled the integration test for DaedalusIPC and added a patch that should hopefully prevent the random test failures due to HPC.

### CODE REVIEW

**Comment by KtorZ** [comment]
> added a patch that should hopefully prevent the random test failures due to HPC.

:s ... This makes me anxious.

**Review by KtorZ — APPROVED** [review]
LGTM for the fix. I am slightly worried about re-enabling the IPC integration scenario right now... We've already a sufficiently big pile of issues with integration tests on windows.. :'(

**Comment by rvl** [comment]
Sure, we can leave the test disabled. Or - disable it first time there is the failure. We know what it looks like.

**Pull request merged**
