### PR TITLE
Draft an initial interface for a DB layer

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

#23

# Overview

- [ ] I have sketched a initial DB layer, just to give the gist of it such that it can be used in the wallet layer.

# Comments

### CODE REVIEW

**Review by paweljakubas — APPROVED** [review]
LGTM, although still not so sure why we need separate `PrimaryKey` and do not want to use some construction from `Cardano.Wallet.AddressDerivation` module

**Comment by KtorZ** [comment]
@paweljakubas how address derivation would help here 🤔?

**Comment by paweljakubas** [comment]
I was wondering if using for example first account public key ( `::Key 'AccountK XPub`) as unique wallet identifier is not ok here (instead of `PrimaryKey`)..

**Comment by KtorZ** [comment]
It could be okay. And we might choose that. Though, requiring this as a key for the DB layer would be introducing needless coupling and a bit of confusion I believe. Plus, we will need to define some serialization instances on the key probably, or have a way to transform it to a suitable format for the underlying DB engine. Doing that on a `Key 'AccountK XPub` would require us to define the corresponding instances in the `Cardano.Wallet.AddressDerivation` module which doesn't make sense (or have an orphan instance which is also, not desirable). Instead, we need here a new type from for the db layer and, we'll have a way to generate such key from a wallet; this way might be by using the public key of the first account, but that's a decision which lives outside of the DB layer.

**Comment by paweljakubas** [comment]
@KtorZ thanks for the answer! Makes sense, especially the coming demand for serialization instances when `DBLayer` will adopt Serialization constraint

**Pull request merged**
