### PR TITLE
Bump cardano-node to pioneer-3

### PR DESCRIPTION
**Pull request by Anviking**
# Issue
None, or #1657
# Overview

- [x] I have bumped cardano-node to the `pioneer-3` tag, such that the new friends-and-family testnet works

# Comments

- `nix-shell` not working yet

### CODE REVIEW

**Comment by Anviking** [comment]
Hm, not sure what is going on with hydra-eval:
```

Attempting to find eval for commit: 4d4cab6f8bd9ffeca6c035d46e9ed2f81ae80f21
--
  | No required jobset was found. check eval errors below:
  | in job ‘cardano-wallet-tests-win64’:
  | cannot coerce a list to a string, at /nix/store/54866h3jd3579lmk7zc8n3xyyj1qgax5-source/nix/windows-testing-bundle.nix:42:3
  |  
  | in job ‘required’:
  | cannot coerce a list to a string, at /nix/store/54866h3jd3579lmk7zc8n3xyyj1qgax5-source/nix/windows-testing-bundle.nix:42:3
  |  
  | in job ‘cardano-wallet-jormungandr-tests-win64’:
  | cannot coerce a list to a string, at /nix/store/54866h3jd3579lmk7zc8n3xyyj1qgax5-source/nix/windows-testing-bundle.nix:42:3
  |  
  |  
  | Traceback (most recent call last):
  | File "/nix/store/i17b2vp5n4bnn2zn3l0bvas1xy6pvwxa-hydra-eval-errors-0.0.0/bin/.hydra-eval-errors.py-wrapped", line 121, in <module>
  | main()
  | File "/nix/store/i17b2vp5n4bnn2zn3l0bvas1xy6pvwxa-hydra-eval-errors-0.0.0/bin/.hydra-eval-errors.py-wrapped", line 119, in main
  | raise BaseException
  | BaseException


```

**Comment by KtorZ** [comment]
@Anviking you need this: https://github.com/input-output-hk/cardano-wallet/pull/1661

**Review by rvl — APPROVED** [review]
It all works for me.
I added a comment to input-output-hk/cardano-haskell#16.
Don't forget to make sure that PR is merged and the `resolver` line updated here before merging this PR.

**Comment by rvl** [comment]
bors try

**Review by piotr-iohk — APPROVED** [review]
Wallet worked fine on F&F overnight. :tada:

**Pull request merged**
