### PR TITLE
cardano-node: 1.18.0 -> 1.19.0

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

None

### Overview

- Updates cardano-node and libraries to [~1.18.1~ 1.19.0 release](https://github.com/input-output-hk/cardano-node/releases/tag/1.19.0).

### Comments

Source: `cardano-node/stack.yaml`

### CODE REVIEW

**Comment by rvl** [comment]
bors try

**Review by Anviking — APPROVED** [review]
I have been running some `1.18.1` with the wallet (but not this branch), and haven't noticed any problems.

**Comment by rvl** [comment]
Your snapshot changes look correct @disassembler, thanks.

I have manually tested just restoring empty wallets on mainnet.

bors try

**Pull request merged**
