### PR TITLE
E2e tests updates

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- 3345a88b9a9e3e890353b8c9c90d1034d86d1cf2
  add decimals to HappyCoin
  
- 6fb310bb06986b62c01361ce006d600746191404
  update migration tests
  
- 097173bb309799c096ade72166eb7a29257f140b
  update construct key tests

# Comments

### CODE REVIEW

**Review by paweljakubas — APPROVED** [review]
lgtm

**Comment by piotr-iohk** [comment]
:tada:

**Pull request merged**
