### PR TITLE
Shutdown handler rework

### PR DESCRIPTION
**Pull request by rvl**
I noticed that some of my review rework from #1425 was not on the master branch.

It looks like I somehow force-pushed from 6c43eca to f10ede8, deleting my changes.

This adds them back.

### CODE REVIEW

**Comment by KtorZ** [comment]
@rvl Any reason this is a draft?

**Comment by rvl** [comment]
I still need to check it on windows.

**Comment by rvl** [comment]
The launcher unit test still works on Windows.

**Comment by KtorZ** [comment]
bors r

**Review by KtorZ — APPROVED** [review]

**Pull request merged**
