### PR TITLE
Bump version to v2020-09-22

### PR DESCRIPTION
**Pull request by Anviking**
# Issue Number

Release

# Overview

- [x] Bump version using `./scripts/make_release.sh`

# Comments

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]

**Comment by KtorZ** [comment]
bors retry

**Comment by rvl** [comment]
Looks like the integration tests are taking a long time. The macOS integration tests from that bors job have been running for 4 hours now.

**Comment by Anviking** [comment]
🎲 
bors r+

**Comment by Anviking** [comment]
🎲 
bors r+

**Comment by KtorZ** [comment]
bors retry

**Pull request merged**
