### PR TITLE
Change 'purposeIndex' for 1852'

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

N/A

# Overview

- [x] I have changed the purpose derivation index to be `1852'`

# Comments

As discussed and agreed in the HD chimeric proposal.

See also: https://github.com/input-output-hk/implementation-decisions/blob/e2d1bed5e617f0907bc5e12cf1c3f3302a4a7c42/text/1852-hd-chimeric.md

cc @SebastienGllmt

### CODE REVIEW

**Review by paweljakubas — APPROVED** [review]
yeap, important information for anyone : 
```
Why use a separate purpose
There are two main reasons:

The 44' in the purpose field is meant to indicate BIP44 so if we are not following BIP44, we should not use 44'.

Shelley requires all addresses to be in bech32 format. If we reused the same purpose, then given the derivation path m / 1852' / 1815' / 0' / 0 / 0, wallet software would not be able to know which address should be generated (legacy address OR bech32 address). By using a separate purpose, it is now clear 44' always indicates a legacy address and 1852' always indicates a bech32 address.
```
changed `legacy address of bech32 address` to `legacy address OR bech32 address` - I bet there is an small error in document

**Comment by KtorZ** [comment]
Ho dear. I probably need to re-generate all the faucet addresses :grimacing:

**Pull request merged**
