### PR TITLE
use IOHK fork for 'zip' to disable system dependency on bzlib2

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

N/A

# Overview

- [x] I have forked the `zip` library waiting for @rvl 's PR to be merged
- [x] I have used our fork in our stack.yaml
- [x] I have used the flag introduced by the PR

# Comments

Let's see if this fixes Hydra as expected :pray:

### CODE REVIEW

**Review by piotr-iohk — APPROVED** [review]
:crossed_fingers:

**Comment by KtorZ** [comment]
Some progress it seems, but not quite there yet.

**Comment by rvl** [comment]
It's merged upstream so I changed the repo link.

I also fixed the windows testing bundle build script.

**Comment by rvl** [comment]
The other tests will be fixed in #1101.

bors r+

**Comment by rvl** [comment]
The integration tests failed on [BYRON_MIGRATE_01](https://buildkite.com/input-output-hk/cardano-wallet/builds/4410#3a6a715a-53f2-4119-b047-e6fae54d1b9a/6-7120). I think this is a random error and not related to this PR, so am trying again.

bors r+

**Pull request merged**
