### PR TITLE
Add latency benchmark for shelley

### PR DESCRIPTION
**Pull request by rvl**
Relates to #1825.

### Overview

- Ports latency benchmarks to shelley backend.
- Refactors duplicate code into a shared module.
- Adds listStakePools to benchmarks

### CODE REVIEW

**Comment by piotr-iohk** [comment]
Probably not related to this pr (?), but I got this when running shelley latency benchmark locally:

```
+++ Run benchmark - shelley
    Non-cached run
        getNetworkInfo      - 0.1 ms
    Latencies for 2 fixture wallets scenario
        listWallets         - 8.2 ms
        getWallet           - 3.9 ms
        getUTxOsStatistics  - 1.4 ms
        listAddresses       - 4.9 ms
        listTransactions    - 2.3 ms
        postTransactionFee  - 196.7 ms
        getNetworkInfo      - 0.0 ms
    Latencies for 10 fixture wallets scenario
SQLite3 returned ErrorMisuse while attAction failed. Here are the captured logs:
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":65,"logMsg":"Received API request"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":65,"logMsg":"[GET] /v2/network/information"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":65,"logMsg":"200 OK in 0.000069772s"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":65,"logMsg":"Completed response to API request"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":66,"logMsg":"Received API request"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":66,"logMsg":"[GET] /v2/network/information"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":66,"logMsg":"200 OK in 0.000042714s"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":66,"logMsg":"Completed response to API request"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":67,"logMsg":"Received API request"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":67,"logMsg":"[GET] /v2/network/information"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":67,"logMsg":"200 OK in 0.000042468s"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":67,"logMsg":"Completed response to API request"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":68,"logMsg":"Received API request"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":68,"logMsg":"[GET] /v2/network/information"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":68,"logMsg":"200 OK in 0.000041473s"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":68,"logMsg":"Completed response to API request"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":69,"logMsg":"Received API request"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":69,"logMsg":"[GET] /v2/network/information"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":69,"logMsg":"200 OK in 0.000040221s"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":69,"logMsg":"Completed response to API request"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":70,"logMsg":"Received API request"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":70,"logMsg":"[GET] /v2/network/information"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":70,"logMsg":"200 OK in 0.000039737s"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":70,"logMsg":"Completed response to API request"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":71,"logMsg":"Received API request"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":71,"logMsg":"[GET] /v2/network/information"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":71,"logMsg":"200 OK in 0.000040118s"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":71,"logMsg":"Completed response to API request"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":72,"logMsg":"Received API request"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":72,"logMsg":"[GET] /v2/network/information"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":72,"logMsg":"200 OK in 0.000039731s"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":72,"logMsg":"Completed response to API request"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":73,"logMsg":"Received API request"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":73,"logMsg":"[GET] /v2/network/information"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":73,"logMsg":"200 OK in 0.000042853s"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":73,"logMsg":"Completed response to API request"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":74,"logMsg":"Received API request"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":74,"logMsg":"[GET] /v2/network/information"}
[:Info:75] [2020-07-03 13:08:49.97 UTC] {"requestId":74,"logMsg":"200 OK in 0.000039623s"}
[:Debug:75] [2020-07-03 13:08:49.97 UTC] {"requestId":74,"logMsg":"Completed response to API request"}
[:Debug:1247] [2020-07-03 13:08:50.01 UTC] {"requestId":0,"logMsg":"Received API request"}
[:Info:1247] [2020-07-03 13:08:50.01 UTC] {"requestId":0,"logMsg":"[POST] /v2/wallets"}
latency: DecodeFailure "Something went wrong"
```

**Review by paweljakubas — APPROVED** [review]
LGTM! why not to introduce the same naming here https://github.com/input-output-hk/cardano-wallet/blob/master/lib/byron/bench/Latency.hs#L150 and https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/bench/Latency.hs#L145 Your naming is better of course:-)

**Comment by rvl** [comment]
Yes thanks @paweljakubas I should do that. (edit: it's done)

**Pull request merged**
