### PR TITLE
Split up module `Control.Monad.Random.Extra`.

### PR DESCRIPTION
**Pull request by jonathanknowles**
## Issue Number

ADP-2386

## Summary

This PR:
- splits up module `Control.Monad.Random.Extra` into two separate modules:
    - `Control.Monad.Random.NonRandom`
    - `System.Random.StdGenSeed`
- removes the unused JSON instances for `StdGenSeed`.
- removes the unused JSON round-trip tests and data for `StdGenSeed`.

## Motivation

1. Better abstraction boundaries:
    - `NonRandom` exists to provide instances of `MonadRandom`, and therefore it makes sense for this module to be part of the `Control.Monad.Random` module hierarchy.
    - `StdGenSeed` relates to `System.Random.StdGen`, and therefore  it makes sense for this to be part of the `System.Random` module hierarchy.
2. Coin selection depends on the `NonRandom` data type. But it doesn't depend on `StdGenSeed`. By splitting the `Control.Monad.Random.Extra` module, we make it possible for coin selection to depend only on the type that it needs.

### CODE REVIEW

**Comment by jonathanknowles** [comment]
bors try

**Comment by jonathanknowles** [comment]
bors try

**Review by Anviking — APPROVED** [review]

**Comment by jonathanknowles** [comment]
Just tried to dig deeper into the log files of some of the jobs that failed, but it seems even the log files have been lost, or were never produced.

Screenshot 2022-11-16 at 22-02-51 Hydra - Log of build 21676848 of job Cardano cardano-wallet-bors-staging linux windows tests cardano-wallet integration

Source: https://hydra.iohk.io/build/21676848/log/tail

**Comment by jonathanknowles** [comment]
I'm going to merge this manually, as:
- Our CI system is currently unusable due to buildkite jobs failing on `packet-ipxe-1-ci1-1`.
- We have no control over which machines buildkite choose to run jobs. On any given run of `bors r+`, there's a very high chance that at least some jobs will be run on `packet-ipxe-1-ci1-1`, which will cause the whole build to fail.
- We already have evidence that this branch passes all tests here: https://bors-ng.aws.iohkdev.io/batches/27045
- I have confirmed that this branch builds and passes all tests on my local machine.

**Pull request merged**
