### PR TITLE
Bump version from 2020.4.7 to 2020.4.28

### PR DESCRIPTION
**Pull request by jonathanknowles**
# Issue Number

None.

# Overview

This PR bumps the version from `2020.4.7` to `2020.4.28`.

### CODE REVIEW

**Review by rvl — APPROVED** [review]

**Comment by jonathanknowles** [comment]
Looks as though the build is failing due to:

```
Failures:  src/Test/Integration/Scenario/API/Byron/Wallets.hs:557:9:
  1) API Specifications, BYRON_WALLETS_RESYNC_01, emptyRandomWallet - force resync eventually get us back to the same point
       uncaught exception: IOException of type UserError
       user error (waited more than 3min for action to eventually resolve. Action: "Wallet re-syncs successfully")  To rerun use: --match "/API Specifications/BYRON_WALLETS_RESYNC_01/emptyRandomWallet - force resync eventually get us back to the same point/"Randomized with seed 1129505826
```
Link to failure: https://hydra.iohk.io/build/2486693/nixlog/1/tail

**Comment by KtorZ** [comment]
bors retry

**Comment by KtorZ** [comment]
Buildkite passed, merging this anyway. force-resync is in the process of being removed anyway.

**Pull request merged**
