### PR TITLE
Fix index-state syntax

### PR DESCRIPTION
**Pull request by andreabedini**
The second index-state stanza completely ovverides the first, resetting hackage index state to HEAD. See haskell/cabal#8568

- [ ] I have ...

### CODE REVIEW

**Comment by paolino** [comment]
Hi I'm trying your patch. 

```
[paolino@nixos:~/iohk/cardano-wallet]$ nix/regenerate.sh 
No changes needed to cabal.project
warning: Git tree '/home/paolino/iohk/cardano-wallet' is dirty
error: attribute 'index-state' already defined at /nix/store/8349dd2kfqgr4n49c66a01yc08wmv39d-cabal-project-index-state.nix:2:3

       at /nix/store/8349dd2kfqgr4n49c66a01yc08wmv39d-cabal-project-index-state.nix:3:3:

            2|   index-state = "2022-09-27T00:00:00Z";
            3|   index-state = "";
             |   ^
            4|   with-compiler = "ghc-8.10.7";
(use '--show-trace' to show detailed location information)
```

**Comment by paolino** [comment]
@piotr-iohk , regarding the actual failure in the gh CI. I think it breaks because check-scope is trying to fetch from `origin` . Is this the wanted behavior?

**Comment by Anviking** [comment]
My guess would be that this has broken

https://github.com/input-output-hk/cardano-wallet/blob/44c0aec254a38a418f1b8850e7040ab26ce9cf52/nix/overlays/common-lib.nix#L30-L52

Also saw this in CI [here](https://github.com/input-output-hk/cardano-wallet/pull/3699#issuecomment-1400548239)

**Comment by andreabedini** [comment]
oh right, I didn't see you had custom nix code. What are you trying to achieve there? from what I can see you are trying to parse the index-state and the compiler name from cabal.project and pass it to `hackage-package` to build other tools of which you specify the version. Since this is nix-land, you could just skip the parsing and passing of the index-state, since haskell.nix will provide a fixed index state anyway (through hackage.nix, which you can bump independently of haskell.nix).

**Comment by jonathanknowles** [comment]
I can confirm that this branch works for me.

After switching to the branch, I can:
- successfully enter a `nix develop` shell
- successfully build everything with `cabal build all`
- successfully use HLS

@andreabedini many thanks for doing this work! 🙏🏻

**Review by jonathanknowles — APPROVED** [review]

**Comment by jonathanknowles** [comment]
bors try

**Comment by andreabedini** [comment]
Ah right, the failure is because there's no `./nix/regenerate.sh` anymore :D

**Comment by andreabedini** [comment]
I just noticed this part in `nix/haskell.nix`

```
      # The list of project packages is not automatically discovered yet,
      # instead it is generated by ./nix/regenerate.sh
      projectPackages = import ./project-package-list.nix;
# ...
      modules =
        let inherit (config) src coverage profiling;
        in
        [
          {
            packages = lib.genAttrs projectPackages (name: {
              # Mark package as local non-dep in the nix-shell.
              # fixme: Haskell.nix should set it
              package.isProject = true;

              # Enable release flag (optimization and -Werror)
              flags.release = true;
# ...
```
not sure what to do here

**Comment by Anviking** [comment]
We can drop the following lines from nix/regenerate.sh
```diff
# Regenerate materialized haskell-build-tools in ./materialized
nix build .#buildToolsGenerateMaterialized
. ./result/bin/regenerate-materialized-nix

# Regenerate materialized iohk-nix-utils in ./materialized
 nix build .#iohkNixGenerateMaterialized
./result/bin/regenerate-materialized-nix
```
which should make the CI check happy.

But I'm getting this error from `direnv reload` locally:
```
error: undefined variable 'iohk-nix-utils'

       at /nix/store/8rkfydldy0cjzxpyvz0dngv5idvr48fm-source/nix/haskell.nix:60:73:

           59|       rewriteLibsPostInstall = lib.optionalString (pkgs.stdenv.hostPlatform.isDarwin) ''
           60|         export PATH=$PATH:${lib.makeBinPath (with pkgs.buildPackages; [ iohk-nix-utils binutils nix ])}
             |                                                                         ^
           61|         rewrite-libs $out/bin $out/bin/*
(use '--show-trace' to show detailed location information)
warning: ignoring untrusted substituter 'https://hydra.iohk.io'
warning: ignoring untrusted substituter 'https://ghcide-nix.cachix.org'
warning: ignoring untrusted substituter 'https://all-hies.cachix.org'
direnv: renewed cache
direnv: export +XDG_DATA_DIRS
```
It seems the `iohk-nix-utils` was lost [here](https://github.com/input-output-hk/cardano-wallet/blob/b0309fa8628bc1869143d83de5c9e7b5d1b833a2/nix/overlays/build-tools.nix#L95-L114) with the deletion of build-tools.nix and I guess we should move it to somewhere else to preserve it, but not sure myself how to do that.

**Comment by andreabedini** [comment]
iohk-nix-utils only got renamed, I thought I changed all the occurrence but I must have missed some. I will look into it tomorrow 👍

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
@andreabedini there's this remaining problem now on windows, `set-git-rev: No such file or directory`, do you know how to fix? 🙏 
```
error: builder for '/nix/store/dgknvfr5mrzw35bprqv14j2d3ip8pkwj-cardano-cli-exe-cardano-cli-x86_64-w64-mingw32-1.35.4.drv' failed with exit code 127;
--
  | last 10 log lines:
  | > Building executable 'cardano-cli' for cardano-cli-1.35.4..
  | > [1 of 1] Compiling Main             ( app/cardano-cli.hs, dist/build/cardano-cli/cardano-cli-tmp/Main.o )
  | > Linking dist/build/cardano-cli/cardano-cli.exe ...
  | > installing
  | > Installing executable cardano-cli in /nix/store/w5iffnj5h0b1vnnw39m667gcq4mb5acn-cardano-cli-exe-cardano-cli-x86_64-w64-mingw32-1.35.4/bin
  | > Warning: The directory
  | > /nix/store/w5iffnj5h0b1vnnw39m667gcq4mb5acn-cardano-cli-exe-cardano-cli-x86_64-w64-mingw32-1.35.4/bin
  | > is not in the system search path.
  | > Symlink libffi and gmp .dlls ...
  | > /nix/store/ji83rcl8f6wlsh082sflack5qr5qrp2c-stdenv-linux/setup: line 89: /nix/store/jchrw4wd0x7258i6hdwxzklc522dfr2w-iohk-nix-utils/bin/set-git-rev: No such file or directory
  | For full logs, run 'nix log /nix/store/dgknvfr5mrzw35bprqv14j2d3ip8pkwj-cardano-cli-exe-cardano-cli-x86_64-w64-mingw32-1.35.4.drv'.
  | error: 1 dependencies of derivation '/nix/store/k371m9bgc32yx5g7h7pjqn73nsf54lca-cardano-wallet-v2022-12-14-win64.drv' failed to build


```

**Comment by andreabedini** [comment]
@Anviking I am aware but I haven't figure it out yet :-)

**Comment by andreabedini** [comment]
bors try

**Comment by jonathanknowles** [comment]
bors try

**Comment by Anviking** [comment]
bors try

**Review by HeinrichApfelmus — APPROVED** [review]
Thank you! 😊

I can find no obvious defects. The following continue to work for me:

* `nix develop`
* `hoogle`
* `ghci` (after `./scripts/gen-ghci.sh` as usual)

**Review by Anviking — APPROVED** [review]
lgtm, thanks!

It seems we've lost `haskell-language-server-wrapper`, so I had to repoint my editor LSP config to `haskell-language-server`, but not sure what the conventional approach is /  if we care enough to re-add it or not.

**Comment by andreabedini** [comment]
@Anviking I don't think there's anything I can do re `haskell-language-server-wrapper`. Dev shells in other repos seems to only offer the `haskell-language-server` binary.

**Comment by Anviking** [comment]
I was going to say the `plutus` repo was the one other repo I could find [with it](https://github.com/input-output-hk/plutus/blob/806561ad47acf861f760afb4f01ea8f4f95e77bd/nix/pkgs/default.nix#L32-L35), but it's not present on `master` anymore. To me it does seem useful to provide the wrapper for people whose editors are set up to look for it, to ensure the correct (nix-provided) HLS version is selected automatically… 🤔 but, then why are other iohk repos not doing this? 🤷‍♂️ Anyway, this is a not that important detail, and we can re-add it later if we see fit. Thanks again for this work!

bors r+

**Pull request merged**
