### PR TITLE
re-use optparse applicative definitions from cardano-addresses

### PR DESCRIPTION
**Pull request by KtorZ**
# Issue Number

N/A

# Overview

- 996bc321628d1b20a2c6ed766bf77d84864574b8
  :round_pushpin: **bump cardano-addresses revision in stack.yaml**
  To include most recent changes and in particular, the revised command-line for addresses
and key derivation.

- 4d4c1a874d3b4fc60ad54b2f0978d665261180a1
  :round_pushpin: **re-use 'key' and 'recovery-phrase' commands from cardano-addresses**
  cardano-addresses also has some great extensive tests for these commands, which means that a lot of tests
and code in cardano-wallet is now redundant. So I removed them.

- 16c741fda872c7501e1e8f3500c4aefb385e8977
  :round_pushpin: **remove redundant dependencies and weeds**
  

# Comments

### CODE REVIEW

**Review by rvl — APPROVED** [review]
LGTM - don't forget to update the wiki docs.

**Comment by KtorZ** [comment]
bors try

**Comment by KtorZ** [comment]
bors r+
please.

**Comment by KtorZ** [comment]
bors try

**Pull request merged**
