### PR TITLE
Jörmungandr v0.7.0-rc4 → v0.7.0-rc5

### PR DESCRIPTION
**Pull request by piotr-iohk**
# Issue Number

# Overview

- [x] jÖrmungandr 0.7.0 rc5
- [x] Regenerate certificates and genesis block used in integration tests.
- [x] Update `Binary` module to deserialize new block format.
- [x] Update External Tx tests: jcli interface has changed a bit.

# Comments

### CODE REVIEW

**Comment by piotr-iohk** [comment]
bors try

**Comment by rvl** [comment]
I see this message from jormungandr in the test logs:

```
Parsing error on Block0
--
  | \|-> Structure invalid: Invalid config parameter tag
  |  
```

**Review by KtorZ — APPROVED** [review]

**Review by Anviking — APPROVED** [review]

**Comment by Anviking** [comment]
```
src/Test/Integration/Framework/DSL.hs:505:23:
  2) API Specifications TRANS_DELETE_05 - Cannot forget external tx via CLI
       waited more than 60s for value to reach or exceed 11111
```
```
jcli rest v0 message logs -h http://localhost:56162/api
---
- fragment_id: f32c8bc7555b4222606b7697debafe3ec9f38e571aa15849c320b7f22e5f3eb4
  last_updated_at: "2019-11-08T11:34:34.005986+00:00"
  received_at: "2019-11-08T11:34:33.000444+00:00"
  received_from: Rest
  status:
    Rejected:
      reason: "Invalid UTxO: Transaction is not found"
- fragment_id: ad02725798e2a4e63985cb138ca789a761fbbfa0589ba435a0c973fc9179ef74
  last_updated_at: "2019-11-08T11:34:32.009754+00:00"
  received_at: "2019-11-08T11:34:31.489799+00:00"
  received_from: Rest
  status:
    InABlock:
      block: 34c1c5218c1b2b56c9cef4bb9abba1518a0e9a20f99d588c5a446fc487b4bfa8
      date: "5670271.2"
```
🤔

**Comment by piotr-iohk** [comment]
I bet it's caused by -> 
https://github.com/input-output-hk/cardano-wallet/pull/983/commits/dff630d7d4874a57c2d5275748eb2180dd17a40d

**Comment by KtorZ** [comment]
I can't reproduce locally...

**Comment by Anviking** [comment]
Running multiple tests fails: `stack test cardano-wallet-jormungandr:integration --ta '--match "/API Specifications/TRANS_DELETE"'`
But when running just one of the failing tests, it passes: `stack test cardano-wallet-jormungandr:integration --ta '--match "/API Specifications/TRANS_DELETE_05 - Cannot forget external tx via CLI/"'`

In the jcli tx preparation we use the tx hash `eee758853b87403722cbf62405a2af445f307fd02bd6a3311b6c0688d7a47963` as input, corresponding to the first fund in the genesis block. It *seems* like we cannot hard-code it anymore (since the tx is "spent"), but shouldn't that have failed before too?

*not sure if I'm missing som utxo basic here*

**Comment by KtorZ** [comment]
> since the tx is "spent"

Ah! Right!

> but shouldn't that have failed before too

No, we use to get the id by looking up in the node's UTxO, but we can't do that anymore, the endpoint was removed.

**Comment by KtorZ** [comment]
Okay, I am on it.

**Comment by KtorZ** [comment]
@Anviking @piotr-iohk 

- Now use proper faucet addresses (prefixed with `external`) from the genesis.yaml for constructing external transactions. There's a limited number, 10 of them which is sufficient for all our scenarios.
- Also moved the transaction building code outside of the DSL since it's jormungandr-specific, and moved it in the jormungandr-specific faucet code.

**Pull request merged**
