### PR TITLE
Fix `decodeUnsignedTx` to correctly try previous eras

### PR DESCRIPTION
**Pull request by paweljakubas**
### Issue Number

ADP-1110

### Comments

This PR adjusts `decodeSignedTx` so that when decoding in a given era, it also correctly tries all previous eras.

### CODE REVIEW

**Comment by piotr-iohk** [comment]
This doesn't seem to work. Actually sending HW device transaction crashes the wallet.
Cborized transaction produced by HW wallet from here -> https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1630597099119600?thread_ts=1630579153.100300&cid=GGKFXSKC6

Sending it via wallet endpoint:

```
echo "83a40082825820d61b9b69bffa67975dc6bc51c3933d2f93cf1b78a000b0e22c762c6cad5229c30182582045c12d4910d70d073374ddd0c095f6a65ff10a3be72c0cb54680803d2d709f1a00018282583900290e0fc38ad639131f37acd052d71660e3f9bd29cf3af1c8f100f36e30aa53197bc7a67d43c26bc3cebb86ba1f0ceb2426ed89c9e2c556491a009896808258390019d628aaa31ad468084c7f34328f04bff60739d1d6cf93778c50e07ceacda39105223742da1efae9dfa82004b15b50a44efa6fea0c2c2dd51a02c1bbeb021a0002ac79031a0228e1eda100828258207de65747ddbbfbb6104a8aa0f825374bb234b726a09788f61c146bacd97b959558405871d80281d42506dde3bab0c0338fae04b08bb105116033432c70a9e4f18049fd8d7529e5a08e2a6d7bfbe91fd1e456bef7976a604e93d1cdb0165864c17b038258209b9f9d1bef02e831b70e66f5339800e8bfe6e5e7d635e181d6878335d83652c5584055f1a01f34bb99b9fc95fbb9d0f7f16566873edcd80d2c107ac35289d4bad12860203b9d349baaef023674005d1005ec15141b0e40a532fb5c32c294309bf20ff6" | xxd -r -p -> tx.bin

curl --header "Content-Type: application/octet-stream" \
-X POST \
--data-binary "@tx.bin" \
http://localhost:8090/v2/proxy/transactions

curl: (52) Empty reply from server
```
In the wallet log there is:

```
[cardano-wallet.main:Debug:4] [2021-09-07 15:05:45.60 UTC] Logging shutdown.
cardano-wallet: ExceptionInLinkedThread (ThreadId 14) unsafeSerializeCbor: DeserialiseFailure 431 "Size mismatch when decoding \nRecord RecD.\nExpected 3, but found 4."
CallStack (from HasCallStack):
  error, called at src/Cardano/Wallet/Unsafe.hs:163:12 in cardano-wallet-core-2021.8.27-7kvgZ5I8PBYLTDU4OW4Sil:Cardano.Wallet.Unsafe
  unsafeDeserialiseCbor, called at src/Cardano/Wallet/Shelley/Compatibility.hs:1199:7 in cardano-wallet-2021.8.27-6kBffRH7vq3GRVwBxOvC08:Cardano.Wallet.Shelley.Compatibility
  unsealShelleyTx, called at src/Cardano/Wallet/Shelley/Network.hs:496:41 in cardano-wallet-2021.8.27-6kBffRH7vq3GRVwBxOvC08:Cardano.Wallet.Shelley.Network
  withNetworkLayerBase, called at src/Cardano/Wallet/Shelley/Network.hs:309:5 in cardano-wallet-2021.8.27-6kBffRH7vq3GRVwBxOvC08:Cardano.Wallet.Shelley.Network
  withNetworkLayer, called at src/Cardano/Wallet/Shelley.hs:278:9 in cardano-wallet-2021.8.27-6kBffRH7vq3GRVwBxOvC08:Cardano.Wallet.Shelley


```

**Comment by jonathanknowles** [comment]
I've done some manual testing of this branch with the following transaction submission command:
```
stack exec cardano-wallet -- transaction submit 83a40082825820d61b9b69bffa67975dc6bc51c3933d2f93cf1b78a000b0e22c762c6cad5229c30182582045c12d4910d70d073374ddd0c095f6a65ff10a3be72c0cb54680803d2d709f1a00018282583900290e0fc38ad639131f37acd052d71660e3f9bd29cf3af1c8f100f36e30aa53197bc7a67d43c26bc3cebb86ba1f0ceb2426ed89c9e2c556491a009896808258390019d628aaa31ad468084c7f34328f04bff60739d1d6cf93778c50e07ceacda39105223742da1efae9dfa82004b15b50a44efa6fea0c2c2dd51a02c1bbeb021a0002ac79031a0228e1eda100828258207de65747ddbbfbb6104a8aa0f825374bb234b726a09788f61c146bacd97b959558405871d80281d42506dde3bab0c0338fae04b08bb105116033432c70a9e4f18049fd8d7529e5a08e2a6d7bfbe91fd1e456bef7976a604e93d1cdb0165864c17b038258209b9f9d1bef02e831b70e66f5339800e8bfe6e5e7d635e181d6878335d83652c5584055f1a01f34bb99b9fc95fbb9d0f7f16566873edcd80d2c107ac35289d4bad12860203b9d349baaef023674005d1005ec15141b0e40a532fb5c32c294309bf20ff6
```
(The above is a serialized Mary-era transaction.)

On `master`, the above command produces the following error:
```
I couldn't verify that the payload has the correct binary format. Therefore I couldn't send it to the node. Please check the format and try again.
```

With **_this_** branch, we see the following error:
```hs
HardForkApplyTxErrFromEra S (S (S (S (Z (WrapApplyTxErr {unwrapApplyTxErr = ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (ValueNotConservedUTxO (Value 0 (fromList [])) (Value 56426212 (fromList []))))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = SafeHash "45c12d4910d70d073374ddd0c095f6a65ff10a3be72c0cb54680803d2d709f1a"}) 0,TxInCompact (TxId {_unTxId = SafeHash "d61b9b69bffa67975dc6bc51c3933d2f93cf1b78a000b0e22c762c6cad5229c3"}) 1])))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (OutsideValidityIntervalUTxO (ValidityInterval {invalidBefore = SNothing, invalidHereafter = SJust (SlotNo 36233709)}) (SlotNo 36705607))))]})))))
```

However, I believe this last error is expected, as this transaction has already been previously submitted to testnet. Therefore, it's attempting to spend already-spent UTxOs, which produces a failure, as expected.

**Review by jonathanknowles — APPROVED** [review]
I've reviewed the code, and it looks good.

I've made some minor changes to error strings (to make them more understandable), and removed a small amount of code duplication.

I've also confirmed that this branch produces the "expected" failure (see https://github.com/input-output-hk/cardano-wallet/pull/2874#issuecomment-914902540).

I haven't merged this yet, as I still need to be convinced that we've done a sufficient amount of testing.

**Comment by jonathanknowles** [comment]
bors try

**Comment by piotr-iohk** [comment]
Nice! I was able to produce serialized tx with Ledger Nano S and Daedalus and successfully send over:

```
curl --header "Content-Type: application/octet-stream" -X POST --data-binary "@tx.bin" http://localhost:8090/v2/proxy/transactions

{"id":"68400f96fa46cd4f1045583fcf84f3e9bcebe8d41d047893c2f4e9b18627da8a"}
```

(edit: confirmed also with Trezor and Ledger nano S on testnet and mainnet)

**Review by piotr-iohk — APPROVED** [review]
lgtm

**Review by rvl — APPROVED** [review]
Looks like a good short term solution, thanks @paweljakubas, @jonathanknowles.

The test cases we are interested in are:
1. wallet and node in alonzo era, transaction in {mary,allegra,shelley} era (current testnet).
2. wallet and node in mary era, transaction in {mary,allegra,shelley} era (test cluster set to mary era, or mainnet).

As an indicator of successful decoding, transaction rejection by the node due to validation seems fine to me.

At present, it's not really feasible to test with a wide range of example transactions. For this, we should use signTx.

**Pull request merged**
