### PR TITLE
stack.yaml: Bump cardano-node to 1.28.0 tag

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

ADP-1025

### Overview

- [x] Bump stack.yaml resolver to input-output-hk/cardano-haskell#50
- [x] Update cabal.project
- [x] Fix type errors resulting from LTS-18.4 bump.
- [x] Does ` nix-shell nix/cabal-shell.nix --run "scripts/buildkite/cabal-ci.sh build"` still work?

### Comments

- [Hydra jobset](https://hydra.iohk.io/jobset/Cardano/cardano-wallet-pr-2763)

### CODE REVIEW

**Comment by Anviking** [comment]
```
This version of stackage.nix does not know about the Stackage resolver lts-18.4.
You may need to update haskell.nix to one that includes a newer stackage.nix.
```
@rvl If you want to keep the 18.4 resolver I think either you our some guidance is needed here. I tried to bump haskell.nix, but don't think it worked:

```
$ ./nix/regenerate.sh --cache /dev/null
cannot build derivation '/nix/store/af4csla0ggb54vi7dgy0l77b5hxw3cyj-nix-tools-regenerate.drv': 1 dependencies couldn't be built
error: build of '/nix/store/af4csla0ggb54vi7dgy0l77b5hxw3cyj-nix-tools-regenerate.drv' failed
./nix/regenerate.sh: line 8: --cache: command not found
```
I could try switching to an older LTS if you want though.

**Comment by Anviking** [comment]
Actually, CI pushed 1749f8d, but there are now some of these errors in buildkite:

```
building '/nix/store/37incwn192cw67gldl9lz89p78w4hi4k-haskell-project-plan-to-nix-pkgs.drv'...
--
  | warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy
  | error: while evaluating the attribute 'NIX_GHC_LIBDIR' of the derivation 'cardano-wallet-shell' at /nix/store/r2ygiv90x2qg2bpxilzabfad1ixnprv6-nixpkgs-unstable-src/pkgs/stdenv/generic/make-derivation.nix:201:11:
```

Some of the other errors I should probably be able to figure out…

**Comment by rvl** [comment]
Yeah there were evaluation errors because some necessary packages were removed from the snapshot:
```
in job ‘macos.checks.cardano-wallet-cli.unit’:
The Haskell package set does not contain the package: ntp-client (build dependency).
If you are using Stackage, make sure that you are using a snapshot that contains the package.
Otherwise you may need to update the Hackage snapshot you are using, usually by updating haskell.nix.
```
Fixed now.

**Review by Anviking — APPROVED** [review]

**Comment by rvl** [comment]
For some reason, the executables have gained a dependency on `libstdc++`.
So when we try to run the executables under wine for testing, it complains about a missing DLL.
Under Windows you generally need the DLLs either next to the EXE, or in some place like `C:\WINDOWS`.

**Comment by Anviking** [comment]
It still says "cached failure" on the windows builds 🤔 Shouldn't it have re-run?

**Comment by rvl** [comment]
Looks like some more things need DLLs copied in then.

You can see [here](https://hydra.iohk.io/jobset/Cardano/cardano-wallet-pr-2778) that 9 jobs were fixed but the rest were exactly the same.

**Comment by rvl** [comment]
Actually, no the fix didn't work and actually it made 9 more failures. :crying_cat_face:

**Comment by Anviking** [comment]
Also, seems like we still have
```
Copying extra test libraries ...
Copying library dependencies...
Could not load wine-gecko. HTML rendering will be disabled.
Native IE detected, not doing registration
wine: configuration in '/build' has been updated.
002a:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\nix\\store\\51vhwb1fdckhx4xiammryf97ip8m3h9d-cardano-wallet-launcher-test-unit-x86_64-w64-mingw32-2021.6.11\\bin\\unit.exe") not found
002a:err:module:attach_dlls Importing dlls for L"Z:\\nix\\store\\51vhwb1fdckhx4xiammryf97ip8m3h9d-cardano-wallet-launcher-test-unit-x86_64-w64-mingw32-2021.6.11\\bin\\unit.exe" failed, status c0000135
builder for '/nix/store/7ssdwhn0gani60q7pwkw13aavbm4ygw1-cardano-wallet-launcher-test-unit-x86_64-w64-mingw32-2021.6.11-check-x86_64-w64-mingw32.drv' failed with exit code 53
```
So my 9a4fded didn't work ☹️ 

But, ah, I might just have gotten the component name wrong?

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
@rvl if you drop 0dff297 and clear the buildkite cache, I think this will work now!

**Pull request merged**
