### PR TITLE
cli: Add cardano-wallet --database option

### PR DESCRIPTION
**Pull request by rvl**
Issue number #154
This PR is based on the branch of #373 

# Overview

- Changes the DBLayer to use SQLite.
- Without a given filename, it just uses the in-memory database.

### CODE REVIEW

**Review by jonathanknowles — COMMENTED** [review]
> Without a given filename, it just uses the in-memory database.

Just to confirm that my understanding is correct, is this in-memory database supposed to be in-memory-SQLite?

I found the following snippet:
```hs
createSqliteBackend :: Maybe FilePath -> LogFunc -> IO SqlBackend
createSqliteBackend fp logFunc = do
    conn <- Sqlite.open (sqliteConnStr fp)
    enableForeignKeys conn
    wrapConnection conn logFunc

sqliteConnStr :: Maybe FilePath -> Text
sqliteConnStr = maybe ":memory:" T.pack  
```

With this change, is there any way to specify the `MVar` database on startup? (Not sure if we want to keep it around.)

**Review by jonathanknowles — COMMENTED** [review]
> Without a given filename, it just uses the in-memory database.

Just to confirm that my understanding is correct, is this in-memory database supposed to be in-memory-SQLite?

I found the following snippet:
```hs
createSqliteBackend :: Maybe FilePath -> LogFunc -> IO SqlBackend
createSqliteBackend fp logFunc = do
    conn <- Sqlite.open (sqliteConnStr fp)
    enableForeignKeys conn
    wrapConnection conn logFunc

sqliteConnStr :: Maybe FilePath -> Text
sqliteConnStr = maybe ":memory:" T.pack  
```

With this change, is there any way to specify the `MVar` database on startup? (Not sure if we want to keep it around.)

**Comment by piotr-iohk** [comment]
It would be nice to add _integration_ test for `--database` option.
Could be here -> https://github.com/input-output-hk/cardano-wallet/tree/master/lib/http-bridge/test/integration/Test/Integration/Scenario/CLI

**Comment by KtorZ** [comment]
Closing in favor of #377 

@piotr-iohk -> Will enable integration tests on the file-based SQLite in another PR.

**Pull request closed without merging**
